boost: updated to 1.69.0
New Libraries

Safe Numerics:
A library for guaranteed correct integer arithmetic for C++14 and later, from Robert Ramey.

Updated Libraries

Any:
Fixed issue with visibility. Now boost::any variables constructed in one shared library with hidden visibility could be used and destroyed in other shared library with hidden visibility.
Maintenance: dropped some dependencies on other Boost libraries, fixes for docs.

Asio:
Fixed a problem with the detection of std::future availability with libstdc++.
Fixed compile error in regex overload of read_until.
Fixed a timer heap corruption issue that can occur when moving a cancelled timer.
Fixed detection of std::experimental::string_view and std::string_view with newer clang/libc++.
Fixed MSVC version detection for availability of std::invoke_result.
Fixed the buffer sequence traits to test the new requirements, if decltype is available.
Fixed an MSVC issue when building with exceptions disabled.
Added SSL context options for TLS v1.3.
Added a compile-time test for TLS v1 support.
Fixed the macro used to test for TLS v1.2 support.
Prevented global objects from being created once per thread on Windows.
Fixed a crash when using size(), max_size() or empty() on default-constructed resolver results.
Changed to move the return value in basic_resolver_results::begin() to avoid copying.
Enabled move support for the Intel Compiler.
Fixed std::string_view detection issue when using clang-cl.
Fixed the handler tracking operation name for io_context::executor_type::dispatch.
Fixed a buffer overflow that could occur when parsing an address string with a 64-bit scope id.
Added examples showing how to write composed operations.
Added C++11 versions of the Timeouts, Timers, SOCKS4 and SSL examples.
Fixed minor issues in documentation and examples.

Assign:
Add rvalue reference, perfect forwarding, and variadic template support
Avoid conversion to container's allocator

Beast:
This version fixes some issues in the examples, and provides a new experimental socket which supports built-in timeouts on asynchronous operations.
New CppCon 2018 websocket chat example and presentation video.
For a complete list of changes, please view the official Release Notes.

CircularBuffer:
Use the empty base optimization for storing allocators that are empty and not final (Glen Fernandes).

Concept Check:
Removed dependency on mpl.

Context:
duplicate alias should be missing GCC alias
the clang-win toolset (clang-cl.exe) uses masm from the underlying msvc
remove useless lines in Jamfile.v2
add .file section for *_elf_gas.S files

Core:
Implemented boost::empty_value, for library authors to conveniently leverage the Empty Base Optimization to store objects of potentially empty types (Glen Fernandes). This facility is now used in Boost.Beast, Boost.CircularBuffer, Boost.MultiArray, and more.
Implemented boost::quick_exit to provide the C++11 standard library facility std::quick_exit functionality (Peter Dimov).
Reduced the number of statics in Lightweight Test, and employ lighter abort behavior for MSVC compilers upon failure to call boost::report_errors (Glen Fernandes).

DLL:
Resolved link issues with the smart library
Maintenance: fixes for docs and tests.
Dynamic Bitset:
Performance improvements (over 2x in some cases).
Added range-based set, reset, flip methods

Fiber:
unbuffered_channel push not return
Remove UTF-8 BOM at begining of the file
Fix boost-install use; should only be issued once

Filesystem:
Don't use readdir_r on Linux and Android since the readdir function is already thread-safe.
Fixed crashes in boost::filesystem::copy due to undefined behavior in the implementation.
Fixed undefined behavior in boost::filesystem::directory_iterator implementation.
Fixed compilation errors when using directory iterators with BOOST_FOREACH.
Removed workarounds for older PGI C++ compiler versions to fix compilation on the newer ones.
Fixed MSVC warnings about narrowing conversions.
Flyweight:
Fixed some issues in GCC related to Boost.MPL placeholder expression handling.
Maintenance fixes.

Function:
Removed dependencies on mpl, test

Geometry:
Karney's solution of direct geodesic problem for internal use
Discrete Frechet and Hausdorff distance algorithms
New run-time and upgraded compile-time SRS transformation interfaces (undocumented for now due to potential interface changes).

Integer:
boost/pending/integer_log2.hpp header is deprecated and will be removed in future releases. Use boost/integer/integer_log2.hpp instead.

Iostreams:
Remove call to nonexistent member seekpos() of std::fpos

Iterator:
Fixed compilation problems with ambiguous unqualified calls to advance and distance on iterators whose types involve types in the namespace boost.

LexicalCast:
Fixed sign-conversion warnings
Maintenance: dropped some dependencies on other Boost libraries, fixed build system warnings.

Log:
General changes:
Updated syslog sink backend to avoid using deprecated Boost.ASIO interfaces.
Bug fixes:
Fixed a possible incorrect estimation of the total size of rotated files in the target directory of a text file sink in some cases.
See changelog for more details.

Logic:
Breaking change: Use explicit operator bool when available

Math:
Add LambertW functions.
Update integration routines to support complex valued integrands and contour integrals.
Added the derivative of the Barycentric rational approximation.
Minor fixes to better support variable precision floating point types.
Removed use of deprecated Boost.Endian in favour of Predef.
Updated continued fraction and series evaluation code to support complex types.
Prevent logic error leading to infinite loop in toms748_solve.
Fix mean and standard_deviation for extreme_value_distribution.
Improve heuristics used in newton_raphson_iterate.
Fix result of erf(NaN).
Big push to reduce GCC warnings.
Refactor polynomial addition.
Fix for vxWorks having a real function in the global namespace.
Improve sinc approximations and add better tests.
Fix typo in Student's T hypothesis testing documentation,

Mp11:
Implemented the mp_starts_with facility (Glen Fernandes).

MultiArray:
Improve C++11 allocator model support including: Support for C++11 minimal allocators, support for stateful allocators, using the allocator for construction and destruction of the value type, and using the empty base optimization for storing empty or stateless allocators (Glen Fernandes).

Multi-index Containers:
Introduced an alternative terse key specification syntax for C++17 compliant environments.

Multiprecision:
Big update to better support variable precision types so that the precision of the result is always the largest of all the arguments.
Add support for allocators that are final in __cpp_int (Glen Fernandes).
Removed use of deprecated Boost.Endian in favour of Predef.
Add support for std::string_view.
Fixed minor bug in constant initialization.
Make assignment of non-finite value to cpp_int a runtime errors.
Added typedefs for cpp_bin_float_oct and cpp_complex_oct.

PolyCollection:
Added Bost.PolyCollection-specific versions of algorithms std::for_each_n and std::sample.

Pool:
Replace boost::mutex use to avoid a dependency on Boost.Thread

Preprocessor:
Supports the new C++ standard conforming preprocessor in VC++ 14.1, which is currently enabled by using the /experimental:preprocessor switch, in Visual Studio 2017 15.8 on up.
Rational:
Add constexpr support

Spirit.X3:
Drop own FP routines in favor of boost::math
Missing visibility mark on exception types
to_utf8: Fixed wchar_t handling on Windows

Spirit V2
Drop own FP routines in favor of boost::math
Missing visibility mark on exception types
Fixed transform_attribute ambiguity
to_utf8: Fixed wchar_t handling on Windows

Spirit.Classic:
Missing visibility mark on exception types

Stacktrace:
libbacktrace usage was significantly improved. BOOST_STACKTRACE_USE_BACKTRACE or boost_stacktrace_backtrace users are encouraged to update:
Memory consumprion dropped down.
Stack capturing became faster by an order of magnitude.
syminfo fallback enabled to provide information for visible symbols even without debug information
Exact location of the backtrace.h header now can be specified via BOOST_STACKTRACE_BACKTRACE_INCLUDE_FILE, to allow backtrace.h header usage on platforms and compilers where that header is unreachable otherwise (for example Ubuntu Xenial + Clang)
Optimized stack capturing if max_depth is set
Added to_string(const stacktrace& ) functions for fast conversion of stacktraces to std::string

System:
Boost.System is now header-only. A stub library is still built for compatibility, but linking to it is no longer necessary.
Even more functions have been marked constexpr.
The destructor of error_category is now protected and no longer virtual. This is a potentially breaking change, but its impact is expected to be limited.
error_category now has a constructor that accepts a 64 bit identifier, enabling distinct category objects to compare equal.
The constructors of error_category are now protected.
A non-allocating, nonthrowing overload of message has been added.
A virtual function failed has been added, allowing categories for which success is not synonymous with 0.
The deprecated boost::system::throws object has been removed.
boost::throws() is now deprecated and its use is discouraged.
The constructor of system_error taking a single error_code argument is now explicit.
system_error::code() now returns by value.

Test:
Boost.test v3.9 see the Changes log for more details.
New feature:
Official support of header-only variant of Boost.Test with multiple translation units.
Now possible to manually add a test case by specifying its name, with BOOST_TEST_CASE_NAME
Better support of boost::exception in the logs

TypeIndex:
Fix the regression and speed up parsing of the boost/type_traits.hpp header by 30%

Utility:
Added support for non-inheritable empty types to boost::compressed_pair by avoiding the empty base optimization for types which are declared as final (Glen Fernandes).

Variant:
Fixed issue with visibility. Now boost::bad_visit exception could cross the boundaries of shared library with hidden visibility and could be catched in other shared library with hidden visibility.

YAP:
Minor changes to support MSVC++ version 14.15 (Visual Studio 2017 version 15.8).
Doc fixes.