rust: fix typo in "old" path in i586-unknown-netbsd patch
Some patch(1) implementations, such as OpenBSD patch and GNU patch,
choose the file name with the fewest path components if neither the
old or new file exist. This missing slash causes the old name
(compiler/rustc_target/src/speci586_unknown_netbsd.rs.orig) to have
fewer components, so it is created instead of the new name as
intended.

This results in build error when one of these patch(1) implementations
is used:

  error[E0583]: file not found for module `i586_unknown_netbsd`