math/lapack: Restore build on DragonFly
Linking lapack with the gold linker fails with this error:
fatal error: --sysroot=: must take a non-empty argument

DragonFly has been using the gold linker by default for a while now.
Since I don't have time to track down this linking problem, I'm going
to restore the build on DragonFly by setting an environment variable
that forces DF to use the classic GNU linker instead.

This was already fixed on math/blas which uses the lapack common
makefile, so just relocate the fix to lapack.