py-test: updated to 8.2.0
pytest 8.2.0 (2024-04-27)

Deprecations

A deprecation warning is now raised when implementations of one of the following hooks request a deprecated py.path.local parameter instead of the pathlib.Path parameter which replaced it:

pytest_ignore_collect - the path parameter - use collection_path instead.
pytest_collect_file - the path parameter - use file_path instead.
pytest_pycollect_makemodule - the path parameter - use module_path instead.
pytest_report_header - the startdir parameter - use start_path instead.
pytest_report_collectionfinish - the startdir parameter - use start_path instead.
The replacement parameters are available since pytest 7.0.0. The old parameters will be removed in pytest 9.0.0.

See py.path.local arguments for hooks replaced with pathlib.Path for more details.

Features

Added support for reading command line arguments from a file using the prefix character @, like e.g.: pytest @tests.txt. The file must have one argument per line.

See Read arguments from file for details.

Improvements

pytest.importorskip() will now issue a warning if the module could be found, but raised ImportError instead of ModuleNotFoundError.

The warning can be suppressed by passing exc_type=ImportError to pytest.importorskip().

See pytest.importorskip default behavior regarding ImportError for details.

For unittest-based tests, exceptions during class cleanup (as raised by functions registered with TestCase.addClassCleanup) are now reported instead of silently failing.

Text is no longer truncated in the short test summary info section when -vv is given.

Improved namespace packages detection when consider_namespace_packages is enabled, covering more situations (like editable installs).

Added PYTEST_VERSION environment variable which is defined at the start of the pytest session and undefined afterwards. It contains the value of pytest.__version__, and among other things can be used to easily check if code is running from within a pytest run.

Bug Fixes

Fixed a regression in pytest 8.0.0 where test classes containing setup_method and tests using @staticmethod or @classmethod would crash with AttributeError: 'NoneType' object has no attribute 'setup_method'.

Now the request.instance attribute of tests using @staticmethod and @classmethod is no longer None, but a fresh instance of the class, like in non-static methods. Previously it was None, and all fixtures of such tests would share a single self.

Fixed issue where fixtures adding their finalizer multiple times to fixtures they request would cause unreliable and non-intuitive teardown ordering in some instances.

Fixed a bug with --importmode=importlib and --doctest-modules where child modules did not appear as attributes in parent modules.

Fixed some instances where teardown of higher-scoped fixtures was not happening in the reverse order they were initialized in.

Trivial/Internal Changes

pluggy>=1.5.0 is now required.
cache: create supporting files (CACHEDIR.TAG, .gitignore, etc.) in a temporary directory to provide atomic semantics.