mariadb105: Update to 10.5.24
                           MariaDB 10.5.24 Changelog

 * Includes all fixes from MariaDB 10.4.33
  * MDEV-32837 long unique does not work like unique key when using
    replace
  * MDEV-29954 Unique hash key on column prefix is computed
    incorrectly
  * cleanup: MY_STRNNCOLLSP_NCHARS_EMULATE_TRIMMED_TRAILING_SPACES
  * cleanup: unused and undefined methods
  * MDEV-11628 mysql.slow_log reports incorrect start time
  * cleanup: main.log_tables test
  * disable perfschema in mtr bootstrap
  * MDEV-28651 quote(NULL) returns incorrect result in view ('NU'
    instead of 'NULL')
  * MDEV-33290: Disable ColumnStore based on boost version
  * sql_test.cc compile fix
  * MDEV-33165 Incorrect result interceptor passed to
    mysql_explain_union()
  * MDEV-33283: Binlog Checksum is Zeroed by Zlib if Part of Event
    Data is Empty
  * MDEV-32968 InnoDB fails to restore tablespace first page from
    doublewrite buffer when page is empty
  * Replace incorrect message `mariadb-safe` with correct
    `mariadbd-safe`
  * MDEV-27666 User variable not parsed as geometry variable in
    geometry function
  * MDEV-32968 InnoDB fails to restore tablespace first page from
    doublewrite buffer when page is empty
  * MDEV-32111: Debian Sid/Trixie will not have libncurses 5 anymore
  * MDEV-29298 INSERT ... SELECT Does not produce an optimizer trace
  * Fix test failures on s390x in test following
    main.column_compression_rpl
  * MDEV-32235: mysql_json cannot be used on newly created table
  * Revert "MDEV-32235: mysql_json cannot be used on newly created
    table"
  * MDEV-32235: mysql_json cannot be used on newly created table
  * MDEV-32790: Output result in show create table for mysql_json
    type should be longtext
  * MDEV-30170 ha_spider::delete_table() should report table not
    exist
  * MDEV-29002 Spider: remove SPIDER_CONN::loop_check_meraged_last
  * MDEV-33092 Undefined reference to concurrency on Solaris
  * MDEV-32984 Update federated table and column privileges
  * MDEV-33098: Fix some instrumentation for innodb.doublewrite_debug
  * MDEV-33156 Crash on innodb_buf_flush_list_now=ON and
    innodb_force_recovery=6
  * MDEV-33098 The test innodb.doublewrite_debug occasionally fails
    to start up InnoDB
  * MDEV-32549 Cluster inconsistent after SAVEPOINT is rolled back
  * MDEV-31905 GTID inconsistency
  * MDEV-33046 fixup. Do not try to schedule timer without
    dict_stats_start()
  * MDEV-33046 - delete unnecessary synchronization with
    dict_stats_mutex
  * MDEV-24481 : galera_3nodes.galera_vote_rejoin_mysqldump MTR
    failed: mysql_shutdown failed
  * Fix main.type_timestamp: Change 10.10 in "End of 10.10 tests" to
    10.5
  * MDEV-33062 innodb_undo_log_truncate=ON prevents fast shutdown
  * MDEV-33052 MSAN use-of-uninitialized-value in
    buf_read_ahead_linear()
  * MDEV-33009 Server hangs for a long time with
    innodb_undo_log_truncate=ON
  * MDEV-33006 Missing required privilege CONNECTION ADMIN
  * MDEV-32839 LONG UNIQUE gives error when used with REPLACE
  * cleanup: remove innodb-specific code around
    update_auto_increment()
  * cleanup: remove partition-specific code around
    update_auto_increment()
  * [fixup] galera: Fix an accidental logical inversion in a recent
    merge
  * MDEV-29816 rpl.rpl_parallel_29322 occasionally fails in BB
  * MDEV-16264 fixup: Remove a useless test
  * MDEV-17226 Column Data in Truncated on UNION to the length of the
    first value if using REPLACE
  * Cleanup: Removing the unused method
    Type_handler::get_handler_by_cmp_type
  * MDEV-32971 Assertion !recv_sys.is_corrupt_fs() failed on recovery
  * MDEV-31939 Adaptive flush recommendation ignores dirty ratio and
    checkpoint age
  * MDEV-32242 innodb.doublewrite test case always gets skipped
  * [fixup] post-merge spider fixup
  * Followup for fix for MDEV-20169: enable main.partition_innodb
  * MDEV-32725 innodb.import_update_stats accesses uninitialized
    ib_table->stat_n_rows
  * fix for the test (real fixes will be in 10.4)
  * MDEV-32212 DELETE with ORDER BY and semijoin optimization causing
    crash
  * MDEV-32269 InnoDB after ALTER TABLE…IMPORT TABLESPACE may not be
    crash safe
  * MDEV-28682 gcol.gcol_purge contaminates further execution of
    innodb.gap_locks
  * Remove deprication from mariadbd --debug
  * MDEV-32879 Server crash in my_decimal::operator= or unexpected
    ER_DUP_ENTRY upon comparison with INET6 and similar types
  * MDEV-31611: mariadb-setpermission - Can't use string as an ARRAY
    ref while strict refs in use
  * MDEV-32861 InnoDB hangs when running out of I/O slots
  * MDEV-32820 Race condition between trx_purge_free_segment() and
    trx_undo_create()
  * MDEV-22243 type_test.type_test_double fails with 'NUMERIC_SCALE
    NULL'
  * Revert "MDEV-22243 type_test.type_test_double fails with
    'NUMERIC_SCALE NULL'"
  * MDEV-24784 JSON_ARRAYAGG charset issue
  * MDEV-26055: Correct the formula for adaptive flushing
  * MDEV-26055: Improve adaptive flushing
  * MDEV-32757 innodb_undo_log_truncate=ON is not crash safe
  * MDEV-32689: Remove Ubuntu Bionic from 10.5
  * MDEV-32798 innodb_fast_shutdown=0 hang after incomplete startup
  * bump the VERSION
  * galera: cleanup of the lists of disabled tests
  * MDEV-31413: post-fix for 10.5+ (galera_restart_replica test
    failures)
  * MDEV-32737 innodb.log_file_name fails on Assertion `after_apply
    || !(blocks).end in recv_sys_t::clear
  * Fix random test failures in testcase perfschema.mdl_func
  * MDEV-32672: Don't hold LOCK_thd_data over commit_ordered
  * MDEV-32462: mysql_upgrade -s still checks for non system tables
  * MDEV-32462: mysql_upgrade -s still checks for non system tables
  * MDEV-26875: Wrong user in SET DEFAULT ROLE error
  * galera: post-fix after migrating changes from 10.4