update to 2.5.5 changes: many bugfixes and compatibility fixes
The 2.5.0 version in pkgsrc was broken:
>>> from pysqlite2 import dbapi2
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/pkg/lib/python2.5/site-packages/pysqlite2/dbapi2.py", line 27, in <module>
from pysqlite2._sqlite import *
ImportError: /usr/pkg/lib/python2.5/site-packages/pysqlite2/_sqlite.so: Undefined PLT symbol "sqlite3_enable_load_extension" (symnum = 158)