fix compile time error on Darwin in player/lib/audio/portaudio:
In file included from pa_mac_core.c:124:
pa_host.h:55: error: conflicting types for 'uint32'
/System/Library/Frameworks/Security.framework/Headers/cssmconfig.h:64: error: previous declaration of 'uint32' was here

use <inttypes.h> and uint32_t instead.

note that according to player/lib/audio/Makefile.am, this old portaudio
lib is used only if HAVE_MAC_OSX.