www/ruiby-rails72: update to 7.2.4
Ruby on Rails 7.2.4 (2026-09-24) is last 7.2 release.

Active Support

* Improve number_to_delimited performance when delimiter_pattern is not
  specified.

  Shinichi Maeshima

* Silence Dalli 4.0+ warning when using ActiveSupport::Cache::MemCacheStore.

  zzak

* Fix ActiveSupport::Inflector.humanize with international characters.

	ActiveSupport::Inflector.humanize("áÉÍÓÚ")  # => "Áéíóú"
	ActiveSupport::Inflector.humanize("аБВГДЕ") # => "Абвгде"

  Jose Luis Duran

Active Record

* Fix performance regression in method_missing for virtual SELECT alias
  attributes.  Fixes #57183.

  Hammad Khan

* Fix support for table names containing hyphens.

  Evgeniy Demin

* Improve PostgreSQLAdapter resilience to Timeout.timeout.

  Better handle asynchronous exceptions being thrown inside the reconnect!
  method.

  This may fixes some deep errors such as:

	undefined method `key?' for nil:NilClass (NoMethodError)
		if !type_map.key?(oid)

  Jean Boussier

* Fix eager_load when loading has_many assocations with composite primary
  keys.

  This would result in some records being loaded multiple times.

  Martin-Alexander

Action View

* Fix strict locals parsing to handle multiline definitions.

  Said Kaldybaev

Action Pack

* Fix ActionController::UnknownHttpMethod to return 405 Method Not Allowed
  instead of 500 Internal Server Error.

  Nicolas Vandenbogaerde

Railties

* Fixed the default Dockerfile to properly include the vendor/ directory
  during bundle install.

  Zhong Sheng

Active Model
Active Job
Action Mailer
Action Cable
Active Storage
Action Mailbox
Action Text

* No changes.