py-tqdm: updated to 4.68.2
4.68.2

revert accidental change to ascii default
UnicodeEncodeError: 'charmap' codec can't encode characters in position 6-7: character maps to <undefined> can be fixed by installing tqdm!=4.68.0,!=4.68.1
misc docs updates
fix links
replace stray rst -> md syntax
consistent "progress bar" terminology
tests: fix coverage