Update to 1.0.5 Based on PR #46593 submitted by Wen Heping(myself)
Upstream changes:
v1.0.5 - 2012-09-03
made automatic protocol links more strict: Only whitespace before and at the end are allowed.
Bugfix: Don't allow ftp:/broken (Only one slash) to be a link.

v1.0.4
html2rest: Handle double link/image substitution and raise better error messages
Bugfix in unittests (include test README file in python package). Thanks to Wen Heping for reporting this.


v1.0.3
Bugfix: AttributeError: 'module' object has no attribute 'interesting_cdata' from HTMLParser patch. Thanks to Wen Heping for reporting this.
Fix a bug in get_long_description() ReSt test for Py3k and his unittests.
Use Travis CI, too.

v1.0.2
Fix "AttributeError: 'NoneType' object has no attribute 'parent'" in html2creole.

v1.0.1
Fix "TypeError: expected string or buffer" in rest2html.
Bugfix in exception handling.

v1.0.0
Change API: Replace 'parser_kwargs' and 'emitter_kwargs' with separate arguments. (More information on API Wiki Page)

v0.9.2
Turn zip_safe in setup.py on and change unittests API.

v0.9.1
Many Bugfixes, tested with CPython 2.6, 2.7, 3.2 and PyPy v1.6

v0.9.0
Add Python v3 support (like http://python3porting.com/noconv.html strategy)
move unittests into creole/tests/
Tested with Python 2.7.1, 3.2 and PyPy v1.6.1 15798ab8cf48 jit

v0.8.5
Bugfix in html2creole: ignore links without href

v0.8.4
Bugfix in html parser if list tag has attributes: https://code.google.com/p/python-creole/issues/detail?id=19#c4

v0.8.3
Better error message if given string is not unicode: https://code.google.com/p/python-creole/issues/detail?id=19

v0.8.2
Bugfix in get_long_description() error handling (local variable 'long_description_origin' referenced before assignment)

v0.8.1
Bugfix for installation under python 2.5
Note: setup helper changed: rename GetLongDescription(...) to get_long_description(...)

v0.8
New GetLongDescription() helper for setup.py, see: https://code.google.com/p/python-creole/wiki/UseInSetup

v0.7.3
Bugfix in html2rest:
table without <th> header
new line after table
create reference hyperlinks in table cells intead of embedded urls.
Don't always use raise_unknown_node()
Add child content to raise_unknown_node()


v0.7.2
Activate ---- to <hr> in html2rest
Update demo.py

v0.7.1
Bugfix if docutils are not installed
API change: rest2html is now here: from creole.rest2html.clean_writer import rest2html

v0.7.0
NEW: Add a html2reStructuredText converter (only a subset of reSt supported)

v0.6.1
Bugfix: separate lines with one space in "wiki style line breaks" mode

v0.6
NEW: html2textile converter
some API changed!

v0.5
API changed:
Html2CreoleEmitter optional argument 'unknown_emit' takes now a callable for handle unknown html tags.
No macros used as default in creole2html converting.
We remove the support for callable macros. Only dict and modules are allowed.
remove unknown html tags is default behaviour in html2creole converting.

restructure and cleanup sourcecode files.

v0.4
only emit children of empty tags like div and span (contributed by Eric O'Connell)
remove inter wiki links and doesn't check the protocol

v0.3.3
Use  when {{{ ... }}} is inline and not <pre>, see: PyLucid Forum Thread
Bugfix in html2creole: insert newline before new list. TODO: apply to all block tags: issues 16

v0.3.2
Bugfix for spaces after Headline: issues 15

v0.3.1
Make argument 'block_rules' in Parser() optional

v0.3.0
creole2html() has the optional parameter 'blog_line_breaks' to switch from default blog to wiki line breaks

v0.2.8
bugfix in setup.py

v0.2.7
handle obsolete non-closed <br> tag

v0.2.6
bugfix in setup.py
Cleanup DocStrings
add unittests