py-subprocess32: update to 3.5.1.
-----------------
2018-05-21 3.5.1
-----------------
* Fix AttributeError: 'module' object has no attribute 'Signals' when
  constructing a CalledProcessError exception.  [#49]

-----------------
2018-05-13 3.5.0 (3.5.0rc3)
-----------------

* Fixed the packaging problem where the stdlib python3_redirect shim is
  supposed to be installed on Python 3.
* Renamed _posixsubprocess to _posixsubprocess32 for consistency.
* Unset CLOEXEC on file descriptors given to Popen pass_fds. (GH #4)
* Drop support for Python 2.4 and 2.5.
* Adds a configure script - run by setup.py - to supply the missing feature
  #define's for the _posixsubprocess32 extension module for the things that
  Python 2's own configure generated pyconfig.h does not already provide.

-----------------
2017-10-18 3.5.0rc1
-----------------

* Backport the new subprocess.run() API from Python 3.5.
* Backport subprocess.DEVNULL support from 3.3.
* Allow stderr to be redirected to stdout even when stdout is not redirected.
  https://bugs.python.org/issue22274
* Fix subprocess.Popen.wait() when the child process has exited to a
  a stopped instead of terminated state (ex: when under ptrace).
  https://bugs.python.org/issue29335
* Include the private API needed by the multiprocessing module for people who
  want to drop subprocess32 in as a replacement for their standard library
  subprocess module.
* Fix a compilation issue regarding O_CLOEXEC not being defined on ancient
  Linux distros such as RHEL 5.