doxygen: updated to 1.18.16
Release 1.8.16
Bug 136299 - attributes to <p> tag get lost
Bug 141919 - Wrong param and exception style in RTF output
Bug 304793 - paramType does not contain attribute element in compound.xsd schema
Bug 322353 - C variable argument list doesn't work in @param
Bug 399222 - SORT_BRIEF_DOCS produces wrong results
Bug 437181 - The -d Preprocessor option doesn't work for php, should be in the doc.
Bug 489766 - Wrong MSC syntax rejected *silently*
Bug 535853 - C consts incorrectly placed under instance variables
Bug 566109 - unable to resolve links to java functions with array arguments
Bug 616379 - doxygen result by nested comment incorrectly
Bug 626582 - Function overloads are not actually sorted in member function list
Bug 632754 - The \copydoc Command Requires The Use of C++ Syntax in C Code
Bug 642126 - @mscfile <filename> does not process mscgen code
Bug 645910 - Segfault on recursion while parsing "\subpage A" in "\page A"
Bug 685714 - false positives reporting parameters or return value not being documented
Bug 757574 - Warning regarding subsection with anchor in markdown
Bug 766508 - missing comments of overridden methods
Bug 781306 - *** Error in `doxygen': realloc(): invalid pointer: 0x0000000001d45ba0 @ exit
Bug 783759 - PERL_PATH config option: when is this needed? Still used?
Bug 796582 - Doxygen has stopped working
Issue 6039: Links on image in Markdown (Origin: bugzilla 769223)
issue 6607 Don't warn about missing parameter documentation for deleted functions
issue 6679 Multiple use of section label warning for Setex-stype headers in markdown
issue 6707 The INSTALL file contains a dead link to install.html
issue 6708 Invalid UTF-8 characters in hover title
Issue 6714: Don't crash or generate invalid XML for empty TOC
issue 6716 mainpage notitle causes notitle to appear in index bar
issue 6725 Doxygen 1.8.15 CMake 3.13 incompatibility
issue 6727 SHOW_NAMESPACES = NO breaks latex PDF
issue 6732 align environment for formula (\f{align}) no longer working
issue 6733 invalid cite anchor id when using crossref
issue 6734 parsing performance worsened
issue 6744 Ampersand in Markdown image URL is not escaped in XML output
issue 6748 1.8.15 regression with C internal modifier
issue 6749 doxygen 1.8.15 segfault
issue 6754 False positives for "multiple @param sections"
issue 6764 Incorrect parsing of C enum comments defined using a macro
issue 6769 Tabu is broken
issue 6775 LaTex package newunicodechar: "package won't work "
issue 6781 Unable to use math in markdown table headers
issue 6791 TOC not generated when using a particular Markdown header style
issue 6796 Bad link to section, subsection if pointing at item past suspicious text
issue 6800 Markdown line ending problems in 1.8.15 and master
issue 6812 Empty lines are lost when copy-pasting from code section.
Issue 6814: Inconsistent whitespace removal for operators in 1.8.15
Issue 6818 Certain regex pattern in class constant causes PHP class to be ignored
issue 6828 Physical newlines (^^) in ALIASES configuration tags not working with sections, subsections, subsubsections and paragraphs
issue 6830 Message: graph_legend:39: error: Prevented to copy file <path_to_html_output>/graph_legend.png onto itself!
issue 6831 Failure to recognize class array with PHP in @var
issue 6840 Hash character in Markdown code span not rendered correctly
issue 6847 Physical newlines (^^) in ALIASES produce a mismatch between documentation and source code
issue 6856 Doxygen only expands macro defined in header file once when referred multiple times
issue 6869 SVG image generated by \dot or \dotfile does not render properly in HTML
issue 6880 mscgen links placed in the wrong place when using SVG output
issue 6892 xml not well-formed (invalid token) for c++
issue 6896 empty sections in latex output
issue 6917 Crash in php with UTF-8 character
issue 6925 Missing ATX headings in markdown pages
issue 6939 Build fail in Windows with build_parse turn ON (unistd.h does not exist in Windows)
issue 6941 Tcl : separate continued lines joined in source listing
issue 6945 \class after \brief doesn't count as a new line - resulting docs show merged descriptions
issue 6946 Compilation error (clangparser.cpp)
issue 6950 XML - <initializer> for array of structure only contains references in first array element
issue 6968 INLINE_INHERITED_MEMB doesn't respect EXTRACT_PRIVATE=NO
issue 6979 Method parameters documented inline are not present in documentation of overriding/implementing methods
issue 6986: C++ static template methods: duplication as non-static and specialization
issue 6990 Dot produces no Graphs
issue 7009 Python class diagram not created for the base class while works for the derived class
issue 7015 Parsing issue with @includedoc and @startuml
issue 7021 Warning about missing item in INCLUDE_PATH
issue 7033 Syntax highlighting doesn't work when calling \dontinclude from Markdown files
issue 7038 Broken refman.tex with SHOW_FILES=NO and doxygen groups
issue 7043 html output for markdown: different output when using ' Header {mainpage}' and 'Header {mainpage}\n===='
issue 7050 Physical newlines (^^) not working in group names and without spaces in 1.8.15
issue 7091 HEAD fails to build on macOS with stock `bison`
issue 7102 Doxygen does not generate error/warning message for unbalanced group markers "@{"..."@}"
issue 7104 Warning with preprocessor
issue 7109 Doxyapp can't use "[source_file | source_dir]" parameter
issue 7110 URL Encoding for Hyperlinks in PDF
issue 7113 Doxygen doesn't process markdown tables correctly
issue 7120 Markdown generator does not consider extension mapping for files with no extension
issue 7124: some code line are missed in the xml file for java
issue 7126 Latex output format fixes
issue 7127 Broken links on generated documentation
issue 7140 DoxygenLayout does not support UTF8 BOM format
issue 7143 note block not generated properly if there are blanks after it
issue 7147: No warning when same page created
issue 7151 Doxygen 1.8.15 TOC_INCLUDE_HEADINGS >0 stops html links being generated in markdown
issue 7166: Doxygen calls DOT differently depending on the output optimization selected.
issue 7068: "QGDict::hashAsciiKey: Invalid null key" error messages
Improve performance of drawing PlantUML diagrams
(X)HTML warning when `[` or `]` in constructed ids
Add 'ins' and 'del' style tags to XML schema
Add colon to section names in latex output
Add possibility of checking XML against XSD in doxygen tests
Added 'constexpr' as attribute label and to XML output
Added .editorconfig.
Added declfile, declline, and declcolumn attributes to the location element in the XML output
Added instructions to build a statically linked doxygen binary from sources
Added noexcept attribute to the XML output
Added virtual destructor to DotGraph base class and disabled copy constructor and assignment operator
Adding HTML tags ins and del
Adjustment of xhtml1-transitional.dtd
Aligned license statement for javascripts with general license statement
Allow Javadoc-style comment blocks with a Doxyfile variable
Allow \r\n as line continuation as well
Ambiguous file name in file command
Avoid calling non-const member aliases and 0 pointer dereference in sqlite3
Avoid endless namespace lookup for C code.
Broken links in documentation
Change DoxyParagraph to use DoxyDesc inside in latex style
Class definition with collections
Conflict between RCS tag and (e.g.) php description
Consistency not generated inheritance diagram
Consistency of configuration parameters
Continuation lines and labels
Correcting command name in output
Correcting errors in xml generation and xsd schema
Correction obvious documentation errors in mscgen
Correction warning message
Count user comment lines
Crash in case of usage of \line without \include
Create option to enable CLANG_ASISTED_PARSING in test suite
Cygwin should by default also have `CASE_SENS_NAMES=NO`
Disabled "inheritance by dominance" warning
Don't try to load htags filemap in case htags fails
Don't write the plantuml cache file in case there are no plantuml diagrams.
Double defined operator in test 74
Double id for tooltips in XHTML Possible.
Doxygen crash on ceph project
Email address not seen
Enable compiler extension to avoid build issues
Enable example doxmlparser possibilities for cmake build
End comment marker in \code section.
Fast Plantuml
Fix 6906
Fix for printlex after destroying the scanner context
Fix for race conditions introduced when refactoring dot classes.
Fix for unmatched </p> when using \until as the first command
Fix for warning about deletion of pointer to incomplete type 'DotFilePatcher'
Fix for warning about deletion of pointer to incomplete type 'DotWorkerThread'
Fix gd_intern.h for Windows build
Fix naming and indenting.
Fix windows build
Fixed C++17-namespace assignment bug
Fixed a few compiler warnings on win32
Fixed alt attribute appearing in <object> tag for SVG images
Fixed issue in doxmlparser in getter function
Fixed issue with counting member lists
Fixed issues in introduced by making file name escapes lower case
Fixed memory leak in reentrant lexers
Fixed missing end paragraph marker when inline image appeared as last item.
Fixed range and added code comment
Fixed segmentation fault in do_warn
Fixed two compilation issues
Fixed type in javascript license text and moved it to one location
Fixed typo
Fixed windows build issue in gd.h
Fixes 6860.
Forgot to comment out debug print
Give warning when a retval is used multiple times
Handling digraph versus label
High consequence coverity mesages
Image not seen as svg image
Implement a new EXTRACT_PRIVATE_VIRTUAL option.
Implementing `<hr>` for LaTeX
Improvement of performance : Reduce the Java running count
Improve handling < for expressions inside template argument defaults
Improved code structure a bit
Improved const correctness and added support for inline namespaces
Incorrect (X)HTML code when generating source code.
Incorrect Reached end of file while still inside a (nested) comment for TCL / Python
Incorrect XHTML of changelog for 1.8.15
Incorrect joining documentation sections.
Incorrect layout of class index (HTML)
Incorrect output tag order
Incorrect paragraph numbers in secref list.
Incorrect warning message
Indentation of paragraphs in LaTeX
Inline VHDL code
Invalid id possible with tooltips
JAVA_ONCE -> FAST
Latex code double minus goes to endash
Made MSCGEN_PATH obsolete now that mscgen code is part of doxygen
Make conanfile creation more readable
Markdown file as internet link
Merge: moved example from 081 to 084, improved check if last char is newline
Merge: reorder tests
Minimum required version for CMake
Missing brief descriptions with `\defgroup`
Missing debug statements sqlcode and xmlcode lexers
Missing warning about ambiguous files
Missing warning for "double comment"
Missing white space in warning
More than 26 appendices in LaTeX manual
Moved check for page having a title to hasTitle() method
Multiple use of HTML attributes
No space when replacing `\copydoc` by `\copydetails`
No translation of markdown in <pre>
Non existing MSC file crashes doxygen
Option for 'input buffer overflow'
Option syntax for commands is unclear
PLANTUML_RUN_JAVA_ONCE is working well. But some specific plantuml has error on ver 1.8.15
Portuguse translators updated to Doxygen 1.8.16.
Possibility to show converted fixed form
Problem with just an asterisks on a `\code` line
Problem with with comment recognition for group open and closing commands
Properly handle empty TOC in XML output.
Reduce code duplication when printing version string
Refactored Definition and derived classes such that they are abstract interfaces
Regression 6836 URL contains $ sign on second run in map of images
Regression on Definition and derived classes that are abstract interfaces
Regression: python file with comment caused "Reached end of file while still inside a comment" warning.
Regression: unbalanced grouping commands
Remove compilation warnings from doxmlparser
Remove dead code
Remove some doxygen warnings in internal documentation
Remove superfluous paragraph tags
Removed page restriction with `\anchor` command in documentation
Removed superfluous character
Revert "Disabled "inheritance by dominance" warning (try 2)"
Revert "alternate fix for .dot file handling"
Revert "issue 6856 Doxygen only expands macro defined in header file once when referred multiple times"
Section title runs into margin
Shortened EXTRACT_PRIVATE_VIRTUAL to EXTRACT_PRIV_VIRTUAL to deal with max length limitation
Show git version information
Show line numbers in "split" examples
Simplified code a bit
Special handling of the UTF8 nbsp sequence
Speed up AppVeyor build by using miktex setup tool and activating build cache
Split off lodepng functionality in a separate library
Store inline attribute for namespaces
Terminate brief in case of `-` list
Terminating brief command
Tests are unsorted
Travis build fails due to problem with cmake
Travis macOS: Update Qt to 5.12.0
Travis macOS: Use Travis addons for homebrew
Travis macOS: Use shared Qt until upstream bugs are fixed
Travis: Handle linux-ppc64le differently
Travis: Install libiconv and libxml via Conan
Travis: Output CMake version
Travis: Removing sudo keyword as this will be soon deprecated anyway
Travis: Workaround to differ between x86 and ppc64le
Travis: macOS Remove permission workaround
Truncated warning message
USE_HTAGS = YES, there are _no_ call / caller graphs in the documentation
Undo the addition of colons
Unified various image file types in the XML schema
Update documentation for msc
Update internal Doxyfile to current version / situation
Updated build instructions to get rid the libtinfo.so dependency on Linux with static libclang.
Updated jquery and worked around performance issues in powertip plugin
Upper case characters in filename despice CASE_SENSE_NAME=NO
Warning for documented return of void type function
Warning if no file specified for special reading commands
Warning messages of test 66
Warning when preprocessing conditionals
Windows crash in case of incorrect end statement
XML validation \msc... \dot... \dia...
a named anchor does not need custom attributes and minor other corrections.
add blurb to docblocks
add format in writePlantUMLSource() and gathered in one pu file. But it is not final
add list of file extensions on doxyparse config
add plantuml.h in doxygen.cpp
added check if .dot file is already queued for processing before adding a new processing job
at sign (`@`) not handled correctly in preprocessor
at sign (`@`) not handled correctly in preprocessor (more fixes)
built-in
changed numbering of dot nodes to prevent different contents being generated for the same .dot file
chmod +x runtest.py
code.l: make CallContext independent of global variables
constexp.l,y: generate a reentrant scanner and parser
constexp.l: group the flex options
constexp.y: drop the = from name-prefix
declinfo.l: enable reentrant
declinfo.l: group flex options toghether
declinfo.l: move function declarations before
delayed creation and update of .md5 files after successful creation of output files
do not clobber version placeholder
doxyparse addon new features and bugfixes
doxysearch: added wildcard, partial and phrase sesarch
enable debug for re-entrant lexers
https link to sourceforge.net
make similar javadoc banner change for stripping special comments from code
node numbers removed for md5 calculation to avoid false md5 mismatches
qglobal.h: Fix build on AIX
refactoring dot.cpp
regression 6885 mscgen links placed in the wrong place when using SVG output
regression 7061 Rename test file
regression 7105 Correct counting in case of `\name`
regression 7105 correct counting for group close counting
remove PLANTUML_RUN_FAST because FAST is default.
secref command output shows in 1 column (HTML)
source arrangement
spelling error: suported -> supported
sqlcode.l: generate a reentrant scanner
take doc group out of commentscan.l
testing: add a test for TOC levels in the XML output.
testing: add a test for XML output with an empty TOC.
testing: improve tests for \ref.
testing: make runtests.py executable.
update jQuery version mentioned in README to 3.4.1
updated manual, included examples in documentation
updated test case to reflect new node numbering
warning: Member func2InGroup1() (function) of class Memgrp_Test is not documented.
warning: More endif's than if's found.
warning: Reached end of file while still inside a (nested) comment.