py-gsutil: updated to 4.52
Release 4.52
Bug Fixes
- Fix tests using wrong AWS credentials if AWS CLI is installed.
- Fix `AttributeError: module 'gslib' has no attribute 'USER_AGENT'`.
- Fix encoding error in `user_agent_helper`.
- Fix stdout ordering issue in hash command.
- Fix multithread race condition for cp/mv command when multiple operations are attempting to create the same directory.
- Fix OSError on interrupted rsync -d.