py-libxml2: in nodeWrap deal with name is None case
Should fix gtk-doc build with itstool 2.0.4:

Error: Could not merge translations:
'NoneType' object is not subscriptable