libX11: update to 1.6.9.
1.6.9

A collection of build and documentation fixes, one preparatory change
for a new xorgproto release, and a fix for a deadlock bug in _XReply.
Thanks to all who contributed.

Adam Jackson (3):
      makekeys: Detach ourselves from X headers entirely
      xkb: Provide <X11/extensions/XKBgeom.h> ourselves
      libX11 1.6.9

Dmitry Osipenko (1):
      Fix lockup in _XReply() caused by recursive synchronization

Ross Burton (1):
      src/util/Makefile: explicitly reset LINK to not use libtool

Thomas E. Dickey (6):
      the last commit overlooked some fake-quote pairs
      another fake-quote fix
      trim trailing whitespace from manpages
      split lines at sentence endings
      fix a substitution error from recent commit, e.g, "s/^\.EE/XDe/"
      improve some formatting

Walter Harms (8):
      note that we can handle kbd==NULL
      remove in-text macros
      replace home grown .ZN with std, .B and .BR
      fix TBL format
      Replace home-grown .Ds .De macro with man page .EX/.EE macro
      remove all private macro defines
      get rid of ``fake quotes''
      fix ``fake quotes'' in text

1.6.8

Adam Jackson (2):
      _XDefaultIOError: Reformat to be less ugly
      _XDefaultIOError: Do better at detecting explicit shutdown

Alan Coopersmith (23):
      Remove documentation of obsolete B16 & B32 tags in specs/libX11
      Update README for gitlab migration
      Import reallocarray() from OpenBSD
      Convert main src directory to use reallocarray()
      Convert src/XKB to use reallocarray()
      Convert src/xcms to use reallocarray()
      Add some missing allocation failure checks in src/xcms
      Replace _XkbTypedRealloc & _XkbClearElems with new _XkbResizeArray
      Replace Xmalloc+strcpy pairs with strdup calls
      Convert src/xlibi18n to use reallocarray()
      Fix out-of-tree builds after commit 8a62e26515e528bb47917ec4a55cc2b492419eeb
      Remove no-longer-used name variable in _XGetAtomName
      Fix implicit conversion warnings in _XlcCreateDefaultCharSet
      Avoid use-after-free in _XimProtoSetIMValues()
      Fix man page typo: XkbAllBellNotifyMask -> XkbAllBellEventsMask
      XkbAllocGeomOverlayKey man page should be named XkbAllocGeomOverlayKeys
      specs/XKB: Fix misprint in documentation of XkbGetNamedGeometry()
      specs/XKB: Fix misprint in documentation of XkbAllocGeomOverlayRows()
      specs/XKB: Fix misprint in documentation of XkbAllocGeomOverlayKeys()
      specs/XKB: Fix misprint in documentation of XkbFreeGeomOverlayKeys()
      XlibInt.c: include headers needed for ioctl(...FIONREAD...) on Solaris
      Include reallocarray.h in tarballs so "make distcheck" passes
      Add missing close paren to XrmGetStringDatabase synopsis in man page

Albert Astals Cid (2):
      compose.dir: Add ast_ES.UTF-8
      locale.dir: Add ast_ES.UTF-8

Jon Turney (4):
      Add autoconf checks for headers we include for FIONREAD
      Remove makekeys dependency on X headers
      Use EXEEXT_FOR_BUILD for makekeys
      Avoid using libtool wrapper for makekeys

Josh Triplett (1):
      compose.dir.pre: Give the C.UTF-8 locale a full set of UTF-8 compose sequences

Matt Turner (2):
      Use AC_SYS_LARGEFILE
      libX11 1.6.8

Matthias Dieter Wallnöfer (5):
      locale.dir.pre - fix the de_LI latin15 locale
      Update locale.alias.pre - introduce the de_LI aliases (equivalent to de_CH)
      compose.dir.pre - add de_IT locale
      locale.dir.pre - add the de_IT locale
      locale.alias.pre - add the de_IT locale

Pavel Labath (1):
      Fix a leak in XCreateFontSet

Ran Benita (1):
      Compose.man: fix escaped hexadecimal char description

Samuel Thibault (1):
      Braille: Fix typing quickly

Tapani Pälli (1):
      Protect colormap add/removal with display lock

ojab (1):
      Compose sequences for rouble sign