openjpeg: updated to 2.5.0
v2.5.0

Merged pull requests:

tools/travis-ci/install.sh: git clone with https:// to fix 'The unaut…
Java Support 1.8 now...
Separate fuzz targets to increase coverage
CMakeLists.txt: do not set INSTALL_NAME_DIR for MacOS builds for CMake >= 3.0 (fixes
Avoid integer overflows in DWT. Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=44544
Updated "added support for partial bitstream decoding"
opj_encoder_set_extra_options(): add a GUARD_BITS=value option
More overflow related bug fixes
opj_j2k_setup_encoder(): validate number of tiles to avoid illegal values and potential overflow (fixes
Missed conversion from unsigned int to OPJ_INT32
Added check for integer overflow in get_num_images
Added overflow check for CVE-2021-29338
Fix integer overflow in num_images
Remove duplicate assignments in function tiftoimage
Fix some typos (found by codespell)
CI: Add CIFuzz action
Feature/decimation
API: deprecate 'bpp' member in favor of 'prec'
Added support for high throughput (HTJ2K) decoding.
verify-indentation.sh: fix for pull request from bar/master to foo/master
Change integer for version libtiff 4.3.0
Port continuous integration to github actions
Avoid integer overflows in DWT.
LGTM warning: Comparison result is always the same
A couple typos found by codespell
cmake: add install interface include directory
fix issues 1368: exist a issues of freeing uninitialized pointer in src/bin/jp2/opj_decompress.c，that will cause a segfault
opj_j2k_is_imf_compliant: Fix out of bounds access
opj_j2k_is_imf_compliant: Fix argument formatting for warnings.
CMakeLists.txt/appveyor.yml: update version number to 2.5.0…
.travis.yml: try to fix gcc 4.8 config by updating to xenial
Add support for enabling generation of TLM markers in encoder
Fix various compiler warnings
fix
Remove obsolete components JPWL, JP3D and MJ2
tools/travis-ci/install.sh: fix links to Kakadu and jpylyzer binaries
emscripten: disable big endian test
Fix cmake file with DESTDIR
CMakeLists.txt: Don't require a C++ compiler
Import files tiff and yuv(raw)
Fix year in NEWS
Fix lcms2 static linking using pgk config
fix static build only against tiff and its indirect dependencies

Closed issues:

integer constant is too large for 'long' type
Openjpeg3D lossy compression not working
mj2: Array overflow
OPJ fails to decode image that KDU manages correctly
yuvtoimage() bug in v1 and v2 for 16-Bit: please apply ASAP
JP3D: Fix CVE-2013-4289 CVE-2013-4290
MJ2 libraries are installed in lib
MJ2: realloc is misused and may leak memory
MJ2 wrapper not functional
JPWL is broken in trunk
MJ2 files not using OPENJPEG API correctly
Maximum bit depth supported by the OpenJPEG implementation of JP3D
does openjpeg support either visually lossless or numerically lossless jpeg2000 compression?
extract jpeg2000 tile without decompression
openjpeg doesn't install a relocatable shared lib on macOS
pull request - the cinema industry awaits!
Integer overflows in j2K
why lossly compression performance worse than jpeg when compress png？
cect
the docs don't describe bpp and prec in opj_image_comp very well
converting .png to .jp2 by opj_compress is different from the original image
Comparison result is always the same
Exist a issues of freeing uninitialized pointer in src/bin/jp2/opj_decompress.c，that will cause a segfault
[TEST NOT RUNNING]: bigendian test
opj_decompress 2.4.0 built with library 2.3.0.
New library htjpeg2000
Integer Overflow in num_images
All IMF Profile Selections Result in PART1
grayscale image
error C2169: 'lrintf': intrinsic function, cannot be defined
Generate lower-case extension
color of reconstructed png file much darker
CVE-2019-6988, CVE-2018-20846 and CVE-2018-16376
opj 2.4.0: opj_free missing in opj3d
Not able to compress volumetric data
HTML documents are not installed in specified place
Can't find openjpeg.h when cross-compile.
OpenJPEG is available with EasyConfig
Building Test Programs
Builds are not reproducible
strange behaviour of opj_jp3d_compress/decompress utility
Potential heap-based buffer overflow in function t2_encode_packet in src/lib/openmj2/t2.c and src/lib/openjp3d/t2.c
Function tgatoimage in src/bin/jpwl/convert.c need to check that the file is big enough to avoid excessive memory allocations
memory & cpu are exhausted when converting jp2 file into png
Cannot compress PGX into JP3D despite following the directions?
sscanf buffer overflow in opj_jp3d_compress.c
integer underflow may lead to writing garbage
sscanf buffer overflow
strcpy overflows
sprintf buffer overflows
strcpy buffer overflow
integer overflow in malloc()
out of bounds writes
out of bounds writes
divide by zero, perhaps multiplication overflow
missing format string parameter
leaks from cppcheck in lib folder
How to initialize DEBUG_PROFILE in color.c?
JP3D sample files
BIG_ENDIAN bug in jpwl.c
OpenJPEG fails to decode partial j2c where kdu succeeds
building mj2 binaries fails
openmj2\mj2.c: Out of bounds
bin\mj2\opj_mj2_decompress.c 101 wrong check / leak