Move comments explaining why jsdk20 and dependent packages are not enabled by default onto the same line as SUBDIR+= for the package, so that lintpkgsrc notices the comments.
Fixes:

ERROR:    www/jsdk20 is disabled without a reason being listed in www/Makefile
          Please add a comment to www/Makefile indicating why www/jsdk20 is disabled
ERROR:    www/jssi is disabled without a reason being listed in www/Makefile
	  Please add a comment to www/Makefile indicating why www/jssi is disabled