py-exceptiongroup: updated to 1.3.1
1.3.1

- Fixed ``AttributeError: 'TracebackException' object has no attribute 'exceptions'``
  when formatting unpickled TBEs from another Python process which did not apply the
  ``exceptiongroup`` patches