rlwrap: Properly include <util.h> for openpty(3)
Previously on NetBSD and probably other system that has openpty(3)
in util.h the compilation lead to a:

 ptytty.c: In function 'ptytty_get_pty':
 ptytty.c:72:7: warning: implicit declaration of function 'openpty' [-Wimplicit-function-declaration]
    if (openpty(&pfd, fd_tty, tty_name, NULL, NULL) != -1) {
        ^~~~~~~

due a missing <util.h> inclusion.

Add a patch for configure.ac (and auto* tools to USE_TOOLS) in
order to address that.

Originally reported by Matthew Mondor via PR pkg/46190 and thanks
to Matthew and <wiz> for their analysis!