www/seamonkey: fix build on NetBSD 8
ERROR: Only GCC 6.1 or newer is supported (found version 5.5.0).

Note that GCC_REQD must be added above any .include lines since otherwise
it is silently ignored.  This needs to be fixed in mk/compiler.mk.