Add patch to check the gettext implementation correctly -- so it  doesn't build with its own libintl.
The error was: error: too many arguments to function `const
char* _nl_expand_alias()'

Include devel/gettext-lib/buildlink3.mk.

Bump PKGREVISION.

This is for PR 30993.