c-icap: bump from gnu89 to gnu99
In file included from /pbulk/work/www/c-icap/work/.buildlink/lib/perl5/5.44.0/x86_64-netbsd-thread-multi/CORE/perl.h:8004,
                 from perl_handler.c:29:
/pbulk/work/www/c-icap/work/.buildlink/lib/perl5/5.44.0/x86_64-netbsd-thread-multi/CORE/inline.h: In function 'Perl_cx_poploop':
/pbulk/work/www/c-icap/work/.buildlink/lib/perl5/5.44.0/x86_64-netbsd-thread-multi/CORE/inline.h:4357:9: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
 4357 |         for (SV **svp = cx->blk_loop.itervar_u.svp + 1; how_many; svp++, how_many--) {
      |         ^~~