Do not pass --as-needed to ld(1). This can lead to bogus errors like "/usr/lib/libstdc++.so: undefined reference to `log'" when using gcc4. The suggested workaround from bmpx is to pass --enable-ld-workaround to configure which in turn passes --noinhibit-exec to ld(1), but I don't like this as it can mask real bugs.
Bump PKGREVISION.