php-pdflib: update to 4.1.2
Use maintained pdflib-lite for build and runtime dependency.

Changelog:

4.1.2
- fix problem in PHP 7 that when extending the PDFlib class it was not possible to access any members of the extended class.

4.1.1
- fix build problem when compiling statically into PHP

4.1.0
- add support for PDFlib 9.1

4.0.1
- fix bug #73249
- improve PHP7 wrapper (fixed crash when extending PDFlib class)

4.0.0
- add support for PHP7

3.0.4
- avoid deprecated warnings for API's which are not yet deprecated when building against an older PDFlib Version.

3.0.3
- fixed bug #66346 (undefined reference to `pdf_begin_pattern_ext')

3.0.2
- support PDFlib 9.0.2

3.0.1
- support PDFlib 9.0.1
- fix bug https://bugs.php.net/bug.php?id=64455
- support for PDFlib 7/8/9 and PDFlib Light
- dropped support for PDFlib 6 and earlier