alsa-lib: update to 1.2.15.2.
Core

    Release v1.2.15.2

Use Case Manager API

    ucm: add some traces for the config filenames

/Makefile.am

    Makefile: remove dist-hook and remove tar option 'follow symlinks'

Error handler

    error: fix the "return old snd_lib_error_set_handler() behaviour"
    error: fix indendation in snd_lib_log_filter()
    error: return old snd_lib_error_set_handler() behaviour