nss: Update to 3.51
Changelog:
Notable Changes in NSS 3.51

* Updated DTLS 1.3 implementation to Draft-34. See Bug 1608892 for details.

Bugs fixed in NSS 3.51

* Bug 1608892 - Update DTLS 1.3 implementation to draft-34.
* Bug 1611209 - Correct swapped PKCS11 values of CKM_AES_CMAC and
CKM_AES_CMAC_GENERAL
* Bug 1612259 - Complete integration of Wycheproof ECDH test cases
* Bug 1614183 - Check if PPC __has_include(<sys/auxv.h>)
* Bug 1614786 - Fix a compilation error for ‘getFIPSEnv’ "defined but not
used"
* Bug 1615208 - Send DTLS version numbers in DTLS 1.3 supported_versions
extension to avoid an incompatibility.
* Bug 1538980 - SECU_ReadDERFromFile calls strstr on a string that isn't
guaranteed to be null-terminated
* Bug 1561337 - Correct a warning for comparison of integers of different
signs: 'int' and 'unsigned long' in
security/nss/lib/freebl/ecl/ecp_25519.c:88
* Bug 1609751 - Add test for mp_int clamping
* Bug 1582169 - Don't attempt to read the fips_enabled flag on the machine
unless NSS was built with FIPS enabled
* Bug 1431940 - Fix a null pointer dereference in BLAKE2B_Update
* Bug 1617387 - Fix compiler warning in secsign.c
* Bug 1618400 - Fix a OpenBSD/arm64 compilation error: unused variable
'getauxval'
* Bug 1610687 - Fix a crash on unaligned CMACContext.aes.keySchedule when
using AES-NI intrinsics