boehm-gc: update to 8.2.12.
== [8.2.12] 2026-02-05 ==

* Do not prevent shared builds on OpenBSD/alpha
* Eliminate 'argument unused' gcc warning in push_all_stack_partially_eager
* Eliminate 'assign long to void*' gcc warning in get_stack_base on Serenity
* Eliminate 'format expects argument of type' gcc warnings in dump_meminfo
* Eliminate 'GC_push_all_stack not used' gcc warning if fix-up pointers
* Eliminate 'GC_remove_roots_subregion not used' gcc warning on Solaris
* Eliminate 'unused parameter' clang warnings in GC_darwin_sigbus
* Fix 'KERN_PROTECTION_FAILURE while world is stopped' error on MacOS X
* Fix 'MA_FETCHOP undeclared' gcc error if USE_PROC_FOR_LIBRARIES on Solaris
* Fix 'PIOCNMAP undeclared' gcc error if USE_PROC_FOR_LIBRARIES on Solaris
* Fix 'reserved' argument handling in GC_DllMain
* Fix 'undefined errno' compiler error in strdup/strndup on WinCE
* Fix a cycle in NORMAL freelist if malloc is redirected on Linux
* Fix assertion in GC_wait_for_reclaim if DllMain-based thread registration
* Fix code defect of LOCK/UNLOCK in separate 'if' in GC_generic_malloc_many
* Fix missing new-line in help message of console variant of cord/de
* Fix race in DllMain by deferring delete_thread call to GC_start_world
* Fix redirected 'free' for callers from libdl/libpthread if IGNORE_FREE
* Fix reliance on glibc-specific '__data_start' for some Linux platforms
* Fix shared library build on MinGW if disable_single_obj_compilation
* Fix SIGSEGV during pthread_setname_np if redirect malloc on FreeBSD
* Fix SIGSEGV if pthread_detach is called before collector initialization
* Fix SIGSEGV in remove_all_threads_but_me if fork from unregistered thread
* Fix typos (about getcontext) in printed message in setjmp_test
* Fix various typos in comments and documentation
* Prevent collection if fork from an unregistered thread
* Refine USE_PROC_FOR_LIBRARIES macro documentation for Solaris
* Remove unneeded '__MINGW_EXCPT_DEFINE_PSDK' macro define for mingw32
* Remove unused GC_VERSION in configure
* Remove unused redefinition of GC_free in gctest
* Revert 'Avoid abort on ResumeThread failure if DllMain closes thread'
* Revert 'Fix GC_suspend abort when the thread is deleted by DllMain'
* Turn on pthread_atfork usage on Hurd
* Workaround locals not pushed in sanitized binaries by disabling fake stacks


== [8.2.10] 2025-10-18 ==

* Add missing test_cpp dependency on gc_allocator.h in build scripts
* Add Serenity OS to list of platforms with POSIX threads in configure
* Avoid abort on ResumeThread failure if Win32 DllMain closes thread handle
* Avoid code duplication in GC_dyld_image_add/remove on Darwin
* Do not define GC_SysVGetDataStart on AIX
* Do not produce '-lpthread' by threadlibs on Tru64/OSF1
* Do not search for data start using GC_find_limit on Haiku
* Do not use deprecated _dyld_bind_fully_image_containing_address (Darwin)
* Do not use deprecated get_etext and get_end on Darwin
* Do not use deprecated getsectbynamefromheader_64 (Darwin)
* Duplicate abort message in system app crash dialog on Haiku
* Eliminate 'allocating insufficient size 0 for char` gcc warning in gctest
* Eliminate 'compare signed/unsigned in check_finalizer_nested' bcc warning
* Eliminate 'conversion from void* to ptr_t' g++ warning in PS_ALLOCA_BUF
* Eliminate 'int-to-ptr cast' gcc warning in GC_push_all_stacks on Solaris
* Eliminate 'int-to-ptr cast' gcc warning in GC_restart_all on OpenBSD
* Eliminate 'int-to-ptr cast' gcc warnings in DEBUG_THREADS code
* Eliminate 'message number 726 is invalid' wcc warning
* Eliminate 'unused parameter fd' gcc warning in NOSYS GC_write
* Eliminate 'value exceeds maximum obj size' gcc warning in hugetest on x32
* Ensure no GC_proc_buf overrun on Solaris
* Export CMake libraries with aliases
* Fix 'cannot implement AO_compare_and_swap_full' error by wcc in tests
* Fix 'cannot locate assembly file' bcc32 error in CMake script
* Fix 'conflicting types for sbrk' gcc error on Solaris if redirect malloc
* Fix 'missing GNU-stack section in atomic_ops_sysdeps' ld warning
* Fix 'symbol undefined _snprintf' dmc linker error in cordtest
* Fix 'undefined STACKBOTTOM' preprocessor error for no-OS PowerPC target
* Fix 'undefined symbol GC_arrays` in tools on Solaris
* Fix 'undefined symbol sbrk' linker error on FreeBSD
* Fix all broken URLs in documentation (as of Nov 2024)
* Fix assertion violation about GC_mark_lock_holder in fork_child_proc
* Fix blocked signals in fork_prepare_proc on HP/UX
* Fix cast of struct-based pthread_t to void pointer on Win32
* Fix code blocks formatting in .md files
* Fix compilation error regarding locks initialization in GC_init on HP_PA
* Fix CPP_WORDSZ for LoongArch
* Fix deprecation warning about support of CMake older than v3.10
* Fix extraneous '#' symbol before comment near USE_WINALLOC for Cygwin
* Fix GC_GRANULE_BYTES for SPARC V9
* Fix GC_suspend abort when the thread is deleted by DllMain
* Fix GC_threads alignment caused by 1-byte global AO_TS_t variables (wcc)
* Fix GETPAGESIZE and USE_M[UN]MAP for Nintendo Switch
* Fix getting memory from OS on Haiku
* Fix I_HOLD_LOCK assertion violation in child process
* Fix mark lock in child process after fork
* Fix missing export for Symbian-specific GC_init_global_static_roots
* Fix missing parentheses in SIG_THR_RESTART macro definition
* Fix print_heap_obj call with the lock held in backgraph add_edge
* Fix pthread id stored in GC_threads of child process
* Fix pthread id stored in key thread_specific_data of child process
* Fix pthread_sigmask result checking in GC_start_mark_threads_inner
* Fix reading async proc maps when GC is single-threaded but process is not
* Fix rounding up in STACKBOTTOM for OSF1
* Fix stack base detection on Haiku by using pthread_getattr_np()
* Fix stack direction detection in setjmp_t on E2K
* Fix symbols alignment checking for CRIS and M68K
* Fix undefined reference to GC_objfreelist and GC_bytes_allocd
* Fix usage of new structured procfs interface on Solaris
* Fix various typos in comments and documentation
* Force use of spin locks to improve performance on Haiku
* Grow GC_proc_buf to required size in GC_proc_read_dirty instead of WARN
* Handle sparc-sun-solaris3 (SunOS6) in configure to use sparc_mach_dep.S
* Initial support of Serenity OS on x86[_64]
* Refine comment in fork_child_proc() about GC_allocate_ml attribute
* Refine description of 'more background' links in Overview document
* Remove always-false check if C++ allocator.allocate returns null in test
* Remove comment about limited support of memory unmapping
* Remove improper comment about returned value of CORD_extend_path
* Remove outdated comment about 'make distcheck' from Makefile.am
* Support RISC-V ILP32 ABI (rv64ilp32)
* Suppress 'missing return value' wcc warning for AO asm primitives
* Suppress 'unreachable code' wcc warnings in win32 threads ASSERT (CMake)
* Turn off thread suspend/resume API support explicitly
* Update libatomic_ops repo URL in README after repo transfer
* Update URLs in documentation after repo transfer to bdwgc organization
* Workaround '__stdcall__ ignored for this target' clang warning on Cygwin64
* Workaround 'array index 4096 is above bounds' gcc warning in malloc_kind
* Workaround 'REFERENCED_DYNAMICALLY flag' linker error on macOS 15.4
* Workaround incremental collection fails on Haiku
* Workaround tests crash if mprotect-based VDB is manually selected (bcc)
* Workaround undefined GC_ptr_store_and_dirty MinGW error in Makefile.direct
* Workaround vpush/vpop instructions generation for non-FPU ARMv5 target


== [8.2.8] 2024-09-08 ==

* Allow GC_size() argument to be null
* Disable backtrace saving at garbage collections if DONT_SAVE_TO_LAST_STACK
* Eliminate 'cast signed to bigger unsigned' CSA warnings in GC_find_limit
* Eliminate 'x might be clobbered by longjmp' gcc warning in setjmp_t.c
* Fix 'un-mprotect vdb failed' abort with out-of-memory reason on Linux
* Fix ADD_CALL_CHAIN() placement to follow GC_store_debug_info_inner call
* Fix GC_debug_realloc to support custom kind
* Fix GC_is_visible for case of arg pointing exactly to object upper bound
* Fix GC_print_trace_inner to print the last element of the circular buffer
* Fix cordtst2.tmp file deletion in cordtest on Windows
* Fix double lock in GC_malloc called from backtrace()
* Fix handling of page-unaligned boundaries in soft_set_grungy_pages
* Fix heap blocks size computation by GC_get_memory_use
* Fix indent of a closing curly braces in GC_apply_to_all_blocks
* Fix infinite resend lost signals if a thread is restarted by SIGQUIT
* Fix null pointer dereference in GC_is_visible if type_descr is null
* Fix per_object_helper() after changing hb_sz units
* Fix pointer relational comparison in GC_do_enumerate_reachable_objects
* Fix poor thread-local allocation performance because of double EXTRA_BYTES
* Fix potential GC_add_roots_inner call with an overflowed pointer (Win32)
* Fix potential address overflow in GC_add_to_heap
* Fix potential buffer overrun during read in GC_text_mapping
* Fix various typos in comments
* Prevent GC_noop_sink from scanning by the collector
* Prevent redirected malloc call from a garbage collection routine
* Redirect malloc_usable_size() in leak_detector.h
* Remove redundant dirty/reachable_here calls in GC_malloc_explicitly_typed
* Update and fix diagrams describing the tree structure for pointer lookups
* Use atomic store to set GC_first_nonempty in GC_do_parallel_mark
* Use atomic store to set entry id and update cache_ptr in slow_getspecific
* Workaround '.obj file not found' error reported by watcom wlib


== [8.2.6] 2024-02-04 ==

* Avoid unexpected heap growth in gctest for the case of VERY_SMALL_CONFIG
* Change gc.man to include gc/gc.h
* Check for out-of-memory on every memory allocation in tests
* Do not compile pthread_start.c on Cygwin even if build shared libs (CMake)
* Eliminate 'alloc_small declared but unused' gcc warning in gctest
* Eliminate 'make_key is defined but unused' gcc warning in threadkeytest
* Eliminate 'old_segv_handler is defined but unused' gcc warning on OpenBSD
* Eliminate 'rand() may return deterministic values' warning
* Eliminate 'unused parameter' compiler warnings reported by MS clang
* Eliminate 'unused parameter' gcc warning in free() if IGNORE_FREE
* Eliminate 'unused value' gcc warnings in init_global_static_roots (Symbian)
* Eliminate GCC warning of unsafe __builtin_return_address(1) in Cmake script
* Eliminate compiler warning of missing cast in LONG_MULT after shift
* Eliminate warning of unused expression result in GC_FreeBSDGetDataStart
* Ensure _GNU_SOURCE is defined if HAVE_DLADDR is defined by configure
* Fix 'g++ not found' error on OpenBSD (Makefile.direct)
* Fix 'implicit declaration of function pthread_atfork' gcc error on MinGW
* Fix 'implicit declaration of function sbrk' gcc error on Symbian
* Fix 'implicit declaration of iscntrl()' warning in cord/de_win (MinGW)
* Fix 'info' buffer potential overrun in GC_save_callers
* Fix 'l-value specifies const object' MSVC error in GC_push_many_regs
* Fix 'linker input unused' error inside check_c_compiler_flag (CMake)
* Fix 'missing binary operator before token' gcc error in gcconfig.h
* Fix 'missing sysconf() prototype' gcc error in setjmp_t tool (OpenBSD)
* Fix 'sigset_t undeclared' MS VC error if pthreads-w32 is used
* Fix 'undefined reference' linker errors if shared build on OpenBSD (CMake)
* Fix 'unused GC_set_and_save_fault_handler' warning on OS X
* Fix GC_push_stack_for() to push also Xmm registers on Windows/x64
* Fix GC_set_handle_fork(1) on Darwin when MPROTECT_VDB but no threads
* Fix MACH_TYPE macro redefinition on Symbian/arm
* Fix SVR4 macro definition order
* Fix asm constraint in LONG_MULT for gcc/x86
* Fix assertion violation in GC_get_maps on Linux if malloc redirection
* Fix back graph and checksums support in WCC_MAKEFILE
* Fix bitwise negation and rounding direction in setjmp_t tool
* Fix checksums GC_record_fault invocation on Darwin
* Fix closing bracket placement for case statement in configure
* Fix deprecation warning about support of CMake older than v3.5
* Fix extra 'extern C' for include signal.h in gcconfig.h
* Fix getcontext() detection by CMake on OpenBSD
* Fix handling of GC_gc_no counter wrap in GC_clear_stack
* Fix handling of GC_gc_no counter wrap in GC_notify_or_invoke_finalizers
* Fix indent of a closing curly brace in GC_forward_exception
* Fix lock assertion violation in GC_try_to_collect_inner on OS X
* Fix missing GC_pthread_sigmask on FreeBSD and NetBSD
* Fix missing _setjmp() on djgpp
* Fix missing atomic barriers in CORD_from_file_lazy
* Fix missing outermost parentheses in CORD_pos_cur_char_addr and hugetest
* Fix missing redirect and implementation of pthread_sigmask() on OpenBSD
* Fix missing type widening before left shift in GC_MAKE_PROC
* Fix misspelled GC_HEADERS_H macro in gc_priv.h
* Fix null dereference in check_finalizer_nested if redirect malloc on Linux
* Fix posix_memalign() to overwrite pointer storage only on success
* Fix race in init_lib_bounds on Linux with glibc v2.34+ if redirect malloc
* Fix skipped removal of page protection in case of address hash collision
* Fix typos in comments
* Fix undefined GC_real_pthread_sigmask if redirect malloc on OS X
* Fix update of last_back_trace_gc_no if KEEP_BACK_PTRS is not defined
* Handle GC_gc_no counter overflow properly in GC_print_trace
* Include Darwin CoreFoundation.h only if 32-bit ARM
* Make gc_allocator<void> members public
* Re-enable incremental mode on OS X (arm64)
* Remove .log and cordtest .tmp files by 'make clean' (Makefile.direct)
* Remove a redundant check of HOST_ANDROID in gcconfig.h
* Remove duplication of random numbers generator formula
* Specify constexpr in GC allocators if C++20 or later
* Support NetBSD/riscv64
* Support non-msys MinGW build by CMake
* Turn on handle fork by default on Darwin (multi-threaded only)
* Use AO primitives in GC_RAND_NEXT instead of no_sanitize attribute
* Workaround 'malloc inconsistent dll linkage' MS VC error in CMake script
* Workaround MS Clang failure to compile de_win.rc
* Workaround mark stack overflow in GC_push_finalizer_structures on MinGW