net/DarwinStreamingServer: fix build for SUBST_NOOP_OK=no
Two of the mentioned files did not actually contain the optimization
flag, which triggered this error during the build:

ERROR: [subst.mk:makefile] The filename patterns
"QTFileTools/QTBroadcaster.tproj/Makefile.POSIX
QTFileTools/QTFileInfo.tproj/Makefile.POSIX" have no effect.

Since the files need not be listed individually, the new definition is
shorter and will also apply to any newly added subdirectories.