www/ruby-faraday: update to 1.4.2
1.4.2 (2021-05-22)

Fixes:

* Add proxy setting when url_prefix is changed (#1276, @ci)
* Default proxy scheme to http:// if necessary, fixes #1282 (#1283, @gurgeous)

Documentation:

* Improve introduction page (#1273, @gurgeous)
* Docs: add more middleware examples (#1277, @gurgeous)

Misc:

* Use external em_http and em_synchrony adapters (#1274, @iMacTia)


1.4.1 (2021-04-18)

Fixes

* Fix dependencies from external adapter gems (#1269, @iMacTia)


1.4.0 (2021-04-16)

Highlights

* With this release, we continue the work of gradually moving out adapters
  into their own gems
* Thanks to @MikeRogers0 for helping the Faraday team in progressing with
  this quest
* And thanks to @olleolleolle efforts, Faraday is becoming more inclusive
  than ever
* Faraday's master branch has been renamed into main, we have an official
  policy on inclusive language and even a rubocop plugin to check for
  non-inclusive words!
* Checkout the "Misc" section below for more details!

Fixes

* Fix NoMethodError undefined method 'coverage' (#1255, @Maroo-b)

Documentation

* Some docs on EventMachine adapters. (#1232, @damau)
* CONTRIBUTING: Fix grammar and layout (#1261, @olleolleolle)

Misc

* Replacing Net::HTTP::Persistent with faraday-net_http_persistent (#1250,
  @MikeRogers0)
* CI: Configure the regenerated Coveralls token (#1256, @olleolleolle)
* Replace Excon adapter with Faraday::Excon gem, and fix autoloading issue
  with Faraday::NetHttpPersistent (#1257, @iMacTia)
* Drop CodeClimate (#1259, @olleolleolle)
* CI: Rename default branch to main (#1263, @olleolleolle)
* Drop RDoc support file .document (#1264, @olleolleolle, @iMacTia)
* CONTRIBUTING: add a policy on inclusive language (#1262, @olleolleolle)
* Add rubocop-inclusivity (#1267, @olleolleolle, @iMacTia)


1.3.1 (2021-04-16)

Fixes

* Escape colon in path segment (#1237, @yarafan)
* Handle IPv6 address String on Faraday::Connection#proxy_from_env (#1252,
  @cosmo0920)

Documentation

* Fix broken Rubydoc.info links (#1236, @nickcampbell18)
* Add httpx to list of external adapters (#1246, @HoneyryderChuck)

Misc

* Refactor CI to remove duplicated line (#1230, @tricknotes)
* Gemspec: Pick a good ruby2_keywords release (#1241, @olleolleolle)