(converters/orcus) +USE_CXX_FEATURES = c++20, implying for gcc12
NetBSD/amd64 9.x fails with following line, later releases are OK.

In file included from /usr/include/g++/memory:80:0,
                 from ../../include/orcus/stream.hpp:13,
                 from stream.cpp:8:
/usr/include/g++/bits/unique_ptr.h: In instantiation of 'typename std::_MakeUniq<_Tp>::__single_object std::make_unique(_Args&& ...) [with _Tp = orcus::file_content::impl; _Args = {std::basic_string_view<char16_t, std::char_traits<char16_t> >&}; typename std::_MakeUniq<_Tp>::__single_object = std::unique_ptr<orcus::file_content::impl>]':
stream.cpp:191:44:   required from here
/usr/include/g++/bits/unique_ptr.h:821:30: error: no matching function for call to 'orcus::file_content::impl::impl(std::basic_string_view<char16_t>&)'
     { return unique_ptr<_Tp>(new _Tp(std::forward<_Args>(__args)...)); }
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~