sysutils/ruby-inspec-core: update to 5.21.29
5.21.29 (2023-01-24)

Merged Pull Requests

* Trivial README change to trigger new omnibus build #6203 (clintoncwolfe)
* Docs spellcheck #6214 (IanMadd)
* CFINSPEC-400 Fix for verify pipeline failure #6218 (Vasu1105)
* CFINSPEC-237 Added enhanced_outcomes option #6145 (Nik08)
* Adds podman resources. #6183 (Vasu1105)
* Fix the dependabot adding ffi (1.15.5-x64-unknown) to omnibus bump #6213
  (Vasu1105)
* Sync up the default branch as main #6239 (tnir)
* Enhance lxc resource to test properties #6243 (ahasunos)
* CFINSPEC-462: Fixes inspec sign breaks when there is period n the profile
  name #6261 (Vasu1105)
* CFINSPEC-374 DSL keyword only_applicable_if added #6229 (Nik08)
* CFINSPEC-458 Oracle DB session resource compatibility with AIX-C shell
  #6257 (Nik08)
* Replace faraday_middleware with faraday-follow_redirects #6238 (tnir)
* Faraday gem update #6267 (Vasu1105)
* Bump test-kitchen from 3.3.1 to 3.3.2 in /omnibus #6227 (dependabot[bot])
* Bump omnibus-software from 1d540dc to 7d0e0fe in /omnibus #6274
  (dependabot[bot])
* Fix for omnibus build failure on Windows #6289 (Vasu1105)
* RESOURCE-527 Add an inspec init template for alicloud #6304 (soumyo13)
* Fix Ruby 2.7 Bundle Installs on CI Verify Pipeline #6324 (clintoncwolfe)
* CFINSPEC-493 update signing_identity #6298 (sathish-progress)
* Cfinspec 488 fix nokigiri omnibus #6305 (sathish-progress)
* Remove Windows Ruby 3.0 testing #6330 (clintoncwolfe)
* Prevent negative status from crashing launchctl service resource #6262
  (dtheyer)
* Update chefstyle from 2.0.x to 2.2.2 to use RuboCop 1.25.1 #6240 (tnir)
* Update readme for usage via Docker (CFINSPEC-516) #6329 (ahasunos)
* CFINSPEC-393 - Fix train-kubernetes plugin load issue #6334 (Vasu1105)
* CFINSPEC-517: Fix for habitat buld failure #6340 (Vasu1105)
* CFINSPEC-528 Upgraded mock Ubuntu fixture to latest LTS version. #6351
  (Nik08)
* Fixing typo in user_permissions #6344 (magicmicah)
* Fix env smoke test by updating ERB.new in inspec env; add additional test
  #6342 (clintoncwolfe)
* CFINSPEC-533: Fix undefined method 'summary' for Gem::SourceFetchProblem
  (NoMethodError) when airgapped #6337 (Vasu1105)
* Use Ruby 3.1.2 in Omnibus build #6341 (clintoncwolfe)
* Revert "CFINSPEC-240 Extended file format support for waivers" #6366
  (Nik08)
* Revert the nokogiri dependency from omnibus project configuration #6372
  (Vasu1105)
* CFINSPEC-553: Fix failing verify pipeline builds on ruby 3.0 #6378
  (Vasu1105)
* Ruby 3.1 support: Adds ucrt platform to resolve windows omnibus
  build. #6381 (Vasu1105)
* CFINSPEC-240 Extended file format support for waivers: JSON & CSV #6369
  (Nik08)
* CFINSPEC-542 Bug fix for profiles with dependent profiles #6377 (Nik08)
* Bump version of omnibus-software #6385 (Vasu1105)
* adding new private verify, as this will kick off the expeditor bump
  v... #6397 (sean-simmons-progress)
* Update copyright year in README, attempt 2 #6395 (clintoncwolfe)