archivers/star: Build fix
Error with CentOS 7:
|
| defaults.c: In function 'star_get_cmd_flags':
| defaults.c:353:2: error: 'for' loop initial declarations are only allowed in C99 mode
|   for (int i=0; i < prog_name_len; i++)
|   ^
| defaults.c:353:2: note: use option -std=c99 or -std=gnu99 to compile your code

Declare that C99 is required.
Bump PKGREVISION.