py-django-stubs-ext: updated to 5.2.7
5.2.7

Fix PK field lookup for Django < 5.2
Version 5.2.7 release


5.2.6

Improvements

Update add_ordering signature too
Support related_query_name in Model._meta.get_fields
django.urls.resolve can also take _StrPromise
Add strict_model_abstract_attrs setting to allow models.Model.objects access
Refactor _replace_type_var that can potentially cause cache problems
Fix union / intersection / difference to support QuerySet using values_list and values
fix: allow to query decimal fields with int
Fix the log_action deprecation notice
BaseForm.add_error: Use covariant types
Allow to annotate existing model field de-selected via prior .values/.values_list calls
Support GenericPrefetch
Also typecheck aget calls
Validation of the fields argument to bulk_update

Housekeeping & CI

Add mypy_primer workflow
Remove magically added django.contrib.contenttypes installed app in tests
Use consistent indentation in pyproject.toml
Version 5.2.6 release

Ruff

Bump ruff to 0.13.0
Add some RET plugin ruff rules
Enable more ruff rules
Fix merge conflict + re-run pre-commit on all files

uv package manager

Update release documentation, workflow and build-and-check job to uv
Switch to uv_build build system & cleanup
Use same uv workspace for django-stubs-ext also
Test updated release workflow - Version 5.2.6a1 release