py-pylint-django: updated to 2.4.0
Version 2.4.0
- Allowed configuration of the Django settings module to be used via a
  commandline argument
- If Django settings are not specified via a commandline argument or environment
  variable, an error is issued but defaults are loaded from Django, removing the
  fatal error behaviour.
- Fixed tests to work with pylint>2.6
- Fixed ``AttributeError: 'Subscript' object has no attribute 'name'`` error.
- Pin Faker version to Prevent Asteroid Crash
- Remove Python 3.5 Support (EOL since Sept 2020 and Faker requires 3.6 anyway)
- Fixed reverse manager ``update_or_create`` calls