Update to 1.424.3
Changelog:
What's new in 1.424.3 (2012/02/27)
    upgrade Apache Maven Wagon to 2.0 (issue 11164)
    ERROR at Matrix-based security (issue 9519)
    NPE: Failed to record SCM polling (issue 11592)
    JDK Auto install throws FATAL: org/apache/xml/utils/PrefixResolver (issue 11420)
    NoSuchMethodError on slf4j (issue 11960)