Pullup ticket #3178 - requested by tnn www/seamonkey: security update and build fix
Revisions pulled up:
- www/seamonkey/Makefile			1.38
- www/seamonkey/distinfo			1.51-1.54
- www/seamonkey/patches/patch-directory_c-sdk_configure.in 1.1-1.2
- www/seamonkey/patches/patch-directory_c-sdk_ldap_include_portable.h 1.1-1.3
- www/seamonkey/patches/patch-directory_c-sdk_ldap_libraries_libldap_Makefile.in 1.1-1.2
- www/seamonkey/patches/patch-mp		1.2
---
Module Name:	pkgsrc
Committed By:	tnn
Date:		Mon Jul 12 11:57:00 UTC 2010

Modified Files:
	pkgsrc/www/seamonkey: distinfo
Added Files:
	pkgsrc/www/seamonkey/patches: patch-directory_c-sdk_configure.in
	    patch-directory_c-sdk_ldap_include_portable.h
	    patch-directory_c-sdk_ldap_libraries_libldap_Makefile.in

Log Message:
Add some DragonFlyBSD fixes, contributed by Francois Tigeot.
---
Module Name:	pkgsrc
Committed By:	tnn
Date:		Mon Jul 12 13:57:29 UTC 2010

Modified Files:
	pkgsrc/www/seamonkey: distinfo
	pkgsrc/www/seamonkey/patches: patch-directory_c-sdk_configure.in
	    patch-directory_c-sdk_ldap_include_portable.h
	    patch-directory_c-sdk_ldap_libraries_libldap_Makefile.in

Log Message:
Add upstream bug ref.
---
Module Name:	pkgsrc
Committed By:	tnn
Date:		Wed Jul 21 11:48:06 UTC 2010

Modified Files:
	pkgsrc/www/seamonkey: distinfo
	pkgsrc/www/seamonkey/patches:
	    patch-directory_c-sdk_ldap_include_portable.h

Log Message:
Fix undefined reference to re_comp/re_exec on dragonfly.
Reported by Francois Tigeot.
---
Module Name:	pkgsrc
Committed By:	tnn
Date:		Wed Jul 21 18:25:06 UTC 2010

Modified Files:
	pkgsrc/www/seamonkey: Makefile distinfo
	pkgsrc/www/seamonkey/patches: patch-mp

Log Message:
Update to seamonkey-2.0.6

MFSA 2010-47 Cross-origin data leakage from script filename in error messages
MFSA 2010-46 Cross-domain data theft using CSS
MFSA 2010-45 Multiple location bar spoofing vulnerabilities
MFSA 2010-42 Cross-origin data disclosure via Web Workers and importScripts
MFSA 2010-41 Remote code execution using malformed PNG image
MFSA 2010-40 nsTreeSelection dangling pointer remote code execution
MFSA 2010-39 nsCSSValue::Array index integer overflow
MFSA 2010-37 Plugin parameter EnsureCachedAttrParamArrays remote code execution
MFSA 2010-36 Use-after-free error in NodeIterator
MFSA 2010-35 DOM attribute cloning remote code execution vulnerability
MFSA 2010-34 Miscellaneous memory safety hazards (rv:1.9.2.7/ 1.9.1.11)