gcc48: update to 4.8.5
Reset PKGREVISION, set gcc48-libs PKGREVISION to 1 (+1 of gcc48)

The following list of 74 PRs have been resolved in the 4.8.5 release
(non-exhaustive list):

64557 get_addr in true_dependence_1 cannot handle VALUE inside an expr
66215 [4.8/4.9/5/6 Regression] Wrong after label NOP emission for -mhotpatch
66233 [4.8/4.9 Regression] internal compiler error: in expand_fix
65550 [4.8/4.9 Regression] ICE (segfault) with pch
62642 [4.8/4.9 Regression] x86 rdtsc is moved through barrier
63608 [4.8/4.9 Regression] error: type mismatch in binary expression
59626 [4.8 Regression] /usr/include/bits/unistd.h:173:1: error: inlining failed in call to always_inline 'readlinkat': recursive inlining
65549 [4.9 Regression] crash in htab_hash_string with -flto -g
59990 [4.8 regression] incorrect memcpy optimization
60656 [4.8 regression] x86 vectorization produces wrong code
66470 [4.8/4.9/5/6 Regression] TLS ICE due to ix86_split_long_move
66481 Implicit lambda capture of variable named ""closure"" causes crash
66275 __attribute__((sysv_abi)) with x86_64-w64-mingw32-gcc generates incorrect code
65680 [4.8/4.9 Regression] ICE at -O1 and above on x86_64-linux-gnu in expand_assignment
65368 [4.8/4.9 Regression]_bzhi_u32 intrinsic generates incorrect code when -O1 or above is specified and index is an immediate
64634 [4.8/4.9 Regression] gcov reports catch(...) as not executed
66123 [4.8 Regression] Array of labels as values + ternary operator + pointer arithmetic = internal compiler error
65518 [4.8 Regression] gcc consumes all memory with -O3
66140 ICE at extract_insn
65721 [4.8/4.9/5/6 Regression] Internal compiler error segmentation fault
65727 [4.8/4.9/5/6 Regression] Segfault With Decltype In Lambda Expression Used To Initialize Static Class Member
59016 f951: internal compiler error: Segmentation fault
65693 [4.8/4.9 Regression] ICE in assign_by_spills
61977 [4.8/4.9/5 Regression] powerpc preprocessor breaks on lines that end with ""vector
59513 [4.8/4.9/5 Regression] Fortran runtime error: Sequential READ or WRITE not allowed after EOF marker
65279 [4.8/4.9 Regression] std::scoped_allocator_adaptor is not assignable
65543 rvalue stream insertion and extraction operators incorrectly implemented
61138 [4.8/4.9/5 Regression] Wrong code with pointer-bounds remapping
65072 Segfault when parsing dectlype in trailing return type
65327 GCC rejects ""constexpr volatile int i = 5;
65409 [4.8/4.9/5 Regression] ICE in store_field
52579 [4.8/4.9/5 regression] i386_w32_fallback_frame_state should care ffi raw-closure stub function
60898 [4.8/4.9/5 Regression] model compile error with gfortran 4.7 and gcc 4.9
57059 [4.8/4.9/5 Regression] Host configuration of loose_warn breaks for build components for Canadian crosses
52664 [4.8 Regression]: gcc.dg/tree-ssa/pr31261.c fails
65220 [4.8/4.9/5 Regression] integer division in stack alignment for VLA allocation
43701 [4.8/4.9/5 Regression] ICE: SIGSEGV (too deep recursion) with -mno-sse and __float128
35330 [4.8/4.9/5 regression] ICE with invalid pragma weak
46102 [4.8/4.9/5 Regression] ICE: SIGSEGV in dwarf2out_finish (dwarf2out.c:8490) with -feliminate-dwarf2-dups when using precompiled headers
61634 [4.8 Regression] ICE in in vect_get_vec_def_for_operand
65063 [4.8 Regression] gcc.dg/vect/vect-double-reduc-6.c FAILs with -O3 -fno-tree-loop-ivcanon -fno-tree-vectorize
63593 ICE: verify_gimple failed: incompatible types in PHI argument 0 with -O3 -fno-tree-vectorize
63844 [4.8 Regression] open mp parallelization prevents vectorization
64493 [4.8 Regression] ICE at -O3 on x86_64-linux-gnu
64495 [4.8 Regression] ICE at -O3 for trunk and wrong code for 4.8/4.9 on x86_64-linux-gnu
64199 [4.8 Regression] ICE: tree check: expected class 'constant'
56273 [4.8 regression] Bogus -Warray-bounds warning
58123 [4.8/4.9/5 Regression] debug line not tracked for last autovariable dtor
45402 [4.8/4.9/5 Regression]  ICE in extract_insn
64768 [4.8/4.9/5 Regression] internal compiler error: tree check: expected tree that contains ‘decl with RTL’ structure
63744 [4.8/4.9/5 Regression] Duplicate use-statement causes error
64979 [4.8 Regression] stdarg optimization not able to find escape sites in phi nodes
57653 [4.8/4.9 Regression] filename information discarded when using -imacros
60718 [4.8/4.9 regression] Test case gfortran.dg/select_type_4.f90 fails on ARM
64479 [4.8 Regression][SH] wrong optimization delayed-branch
39722 [4.8/4.9 Regression][cond-optab] worse code with bitfields on v850
64882 ICE on valid code at -O3 with -g enabled in simplify_subreg
61058 [4.8/4.9 Regression] ICE: RTL check: expected elt 3 type 'B'
64513 [4.8/4.9 Regression] ICE: in maybe_record_trace_start
64766 [4.8/4.9 Regression] internal compiler error: tree check: expected block
64487 [4.8/4.9 Regression] internal compiler error: in fold_offsetof_1
62044 [4.8/4.9 Regression] ICE in USE statement with RENAME for extended derived type
57748 [4.8 Regression] ICE when expanding assignment to unaligned zero-sized array
57023 [4.8 Regression] Not packing arrays with changing variable used for size
52306 [4.8 regression] ICE in cselib_record_set
52714 [4.8 regression] ICE in fixup_reorder_chain
58369 [4.8 regression] ICE in subreg_get_info when compiling boost for m68k-linux
63733 [4.8/4.9/5 Regression] [OOP]  wrong resolution for OPERATOR generic