Update clutter to 1.20.0
Clutter 1.20.0                                                       2014-09-22
===============================================================================

  # List of changes since Clutter 1.19.10

    - Translations updated
    Greek

  # List of bugs fixed since Clutter 1.19.10

    - #736826 - clutter_text_set_font_name invalid example using "pt"

Clutter 1.19.10                                                      2014-09-17
===============================================================================

  # List of changes since Clutter 1.19.8

    - Honour the desktop window scaling factor in the GDK backend
    The GDK backend will become the default backend in the next cycle, so we
    need to improve its functionality out of the box.

    - Ensure accessibility support is correctly initialized
    We need to make sure that the accessibility implementation that Clutter
    relies on is initialized the way we expect it to.

    - Improve default paint volume computation
    We should reduce the cases that lead to an invalid paint volume.

    - Improve input handling on Wayland and X11

    - Translations updates
    Hebrew

  # List of bugs fixed since Clutter 1.19.8

    #736682 - clutter-actor: Don't ask children that have no allocation for
              a paint volume
    #736413 - USB mouse doesn't register slow movements to the right or down
              in Gnome on Wayland
    #734480 - Handle CLUTTER_SCALE envvar
    #734115 - Deprecated property crashes /actor/transforms/anchor-point
    #735388 - xi2 device manager gets a "0" client pointer if queried very
              early in app lifetime
    #735244 - shell forgets the DPI of screen sometimes

Many thanks to:

  Bastien Nocera, Adel Gadllah, Alejandro Pineiro, Carlos Garnacho, Jonas
  Adahl, Yosef Or Boczko

Clutter 1.19.8                                                       2014-08-21
===============================================================================

  # List of changes since Clutter 1.19.6

    - Improve the GDK backend
    The GDK backend is now reporting touch events, as well as supporting
    foreign Wayland surfaces for the Stage window. The goal is to make the
    GDK backend the preferred one in the next development cycle.

    - Fix drawing transparent Canvas content inside transparent actors

    - Translation updates
    German, Assamese

  # List of bugs fixed since Clutter 1.19.6

    #733202 - evdev: Add API to set the xkb layout index
    #734934 - Add touch event translation code to GDK backend
    #734935 - Add support for wayland foreign windows in GDK backend
    #734761 - Memory leak in implicit transition

Many thanks to:

  Lionel Landwerlin Christian Kirbach, Rui Matos, Tom Beckmann, ngoswami,
  Sunjin Yang

Clutter 1.19.6                                                       2014-07-24
===============================================================================

  # List of changes since Clutter 1.19.4

    - Add a signal for the end of the frame on ClutterStage
    The ::after-paint signal is useful to execute custom code after all the
    painting on a specific ClutterStage has been performend, but before the
    frame contents have been presented on the screen.

    - Improvements in the reliability of the evdev input backend

    - Improvements in the GestureAction implementation

  # List of bugs fixed since Clutter 1.19.4

    #732342 - ClutterStage: Add an ::after-paint signal
    #732907 - Allow for calling clutter_gesture_action_cancel() within the
              ::gesture-end handler
    #733062 - Evdev: set button state in input devices
    #733300 - ClutterAnimation: fix memory leak
    #733561 - Make a GType for ClutterEventSequence
    #733562 - evdev: update xkb_state when resuming input
    #733560 - Touch events trigger enter events on press, but no leave events
              on release

Many thanks to:

  Carlos Garnacho, Giovanni Campagna, Owen W. Taylor

Clutter 1.19.4                                                       2014-06-25
===============================================================================

  # List of changes since Clutter 1.19.2

    - Depend on libinput 0.4
    The evdev input backend now depends on libinput 0.4.0.

  # List of bugs fixed since Clutter 1.19.2

    #731268 - Events being clamped to the pre-fullscreen window size when
              stage goes fullscreen
    #731178 - evdev: Used floating point instead of fixed point numbers
    #731254 - evdev: Follow libinput enum rename
    #731536 - evdev: Add clutter_evdev_warp_pointer
    #732234 - Touch events may leave a stage-less device, or happen on one
    #732235 - clutter gesture actions may mistakenly handle enter/leave events

Many thanks to:

  Jonas Adahl, Chun-wei Fan, Gustavo Noronha Silva, Jasper St. Pierre,
  Carlos Garnacho.

Clutter 1.19.2                                                       2014-05-28
===============================================================================

  # List of changes since Clutter 1.18

    - Improve event handling on evdev input backend
    Clutter now allows writing applications and compositors that can respond
    to eventts from touch devices, as well as reporting correct smooth
    scrolling deltas.

  # List of bugs fixed since Clutter 1.18

    #723560 - wayland: Generate better smooth scroll deltas
    #730577 - Do not compress touch events so eagerly
    #728968 - evdev: Implement touch support
    #728967 - evdev: Add libinput-specific helpers
    #730215 - Add a way to pause the ClutterMasterClock

Many thanks to:

  Carlos Garnacho, Jasper St. Pierre, Jonas Adahl.

Clutter 1.18.2                                                       2014-04-14
===============================================================================

  # List of changes since Clutter 1.18.0

    - Fix the list of dependencies
    Clutter 1.18 depends on Cogl 1.17.5 when building the EGL/KMS backend.

    - Fixes for the Visual Studio build files
    Use the new symbol visibility annotations when building with MSVC.

    - Fix event handling on Windows
    An optimization led to a crash on the Windows backend when delivering
    events without an associated ClutterStage.

    - Ensure that set_child_above/below work on the Stage
    ClutterStage should respect the paint order when using the Actor API.

    - Skip conformance test suite on X11 when DISPLAY is unset
    Instead of bailing out when initializing the test suite we should just
    tell the test suite API to skip the units. This allows the TAP driver
    to catch the skipped tests and avoid warnings.

    - Translation updates
    Danish, French, Indonesian, Greek.

  # List of bugs fixed since Clutter 1.18.0

    #728177 - Cannot collect coverage with lcov 1.10
    #727020 - wayland: Add missing CLUTTER_AVAILABLE annotations
    #711645 - clutter_actor_set_child_above_sibling() not working in
              ClutterStage
    #726762 - Fix Import of Clutter Version Constants
    #726703 - build error: undefined reference to
              `cogl_kms_renderer_set_kms_fd'

Many thanks to:

  Chun-wei Fan, Adel Gadllah, Andika Triwidada, Ask H. Larsen, David Warman,
  Emilio Pozuelo Monfort, Vadim Rutkovsky, maria thukididu, teuf.

Clutter 1.18.0                                                       2014-03-18
===============================================================================

  # List of changes since Clutter 1.17.6

    - Update build environment for Visual Studio

    - Improve the API for implementing Wayland compositors
    Allow integrating with logind and KMS; provide clipped redraws on both
    Wayland clients, and direct KMS.

    - Port the documentation to MarkDown

    - Use symbol annotations to ensure the public ABI

    - Translations updates
    Korean, Traditional Chinese (Hong Kong and Taiwan), Chinese, Portuguese,
    Latvian, Russian, French.

  # List of bugs fixed since Clutter 1.17.6

    #725716 - Fix build of clutter-test-utils.c on Windows
    #725873 - Fix the Win32 backend for newer Visual Studio Versions
    #725722 - Grid layout actor width/height swapped
    #726199 - evdev changes needed for logind integration work
    #726341 - eglnative: Add clutter-stage-window implementation
    #726315 - clutter-stage-wayland: Enable clipped redraws
    #726313 - stage-cogl: Fix feature check in clutter_stage_cogl_redraw
    #726198 - egl: Add a way to set the KMS FD
    #708781 - wayland: Keep track of button modifier state
    #711857 - Avoid needless event copies when queueing from a backend
              to a stage

Many thanks to:

  Jasper St. Pierre, Chun-wei Fan, Adel Gadllah, Bastian Winkler, Changwoo Ryu,
  Chao-Hsiung Liao, Duarte Loreto, Jonas Adahl, Rui Matos, R#dolfs Mazurs,
  Wylmer Wang, Yuri Myasoedov, teuf.

Clutter 1.17.6                                                       2014-03-03
===============================================================================

  # List of changes since Clutter 1.17.4

    - Use libinput instead of libevdev
    The evdev input backend is now based on libinput instead of directly
    using the evdev API; this allows for shared input behaviour with
    different toolkits.

    - Improvements in the X11 input handling
    Remove the chance of input devices going out of sync; avoid excessive
    round trips when asking for the client pointer; retrieve the text
    direction for the current keymap.

    - Improve RTL handling in ClutterText
    Try to use the correct text direction based on the contents, keymap,
    and actor's direction instead of just the latter.

    - Translation updates
    Brazilian Portuguese, Lithuanian, Czech, Hungarian, Serbian, Polish,
    Galician.

  # List of bugs fixed

    #
    #724788 - stage-cogl: Fix buffer_age code path
    #724971 - Avoid stale ClutterInputDevice pointers in the device list
    #720566 - [RFC] evdev: Port evdev input backend to libinput
    #725102 - Patches to rework the evdev backend's keymap handling
    #725103 - evdev: Set the initial core pointer coordinates to a sane value
    #705779 - The text in the search-entry isn't aligned to right in RTL text
    #725561 - DeviceManagerXi2: Cache the client pointer

Many thanks to:

  Rui Matos, Adel Gadllah, Jasper St. Pierre, Aurimas Cernius, Balazs Ur,
  Carlos Garnacho, Fran Dieguez, Jonas Adahl, Marek Cernocky, Piotr Drag,
  Rafael Ferreira, ######## #######.

Clutter 1.17.4                                                       2014-02-19
===============================================================================

  # List of changes since Clutter 1.17.2

    - Add per-gesture thresholds
    It is possible to give horizontal and vertical thresholds to each
    ClutterGestureAction instance; if unset, the default is to use the
    dnd threshold from ClutterSettings.

    - Allow negative factors in ClutterActor scale properties
    The functions already accepted these values, but the properties did not.

    - Depend on Cogl 1.17.3

    - Translation updates
    Spanish, Hebrew, Czech, Brazilian Portuguese, Traditional Chinese (Hong
    Kong and Taiwan), Serbian, Galician, Indonesian, Italian, Aragonese,
    Norwegian bokmål, Ukranian.

  # List of bugs fixed since Clutter 1.17.2

    #711540 - Fix bad logic in checks
    #662818 - Fix documentation of 'hsla()' parsing
    #710232 - Mention that ClutterTransition is abstract in the documentation
    #706311 - Extend :scale-[xyz] factors in the negative range
    #724242 - Add per-action thresholds

Many thanks to:

  Bastien Nocera, Daniel Mustieles, Kjartan Maraas, Milo Casagrande, Adel
  Gadllah, Andika Triwidada, Chao-Hsiung Liao, Daniel Korostil, Fran Dieguez,
  Jorge Perez Perez, Marek Cernocky, Rafael Ferreira, Yosef Or Boczko,


Clutter 1.17.2                                                       2014-01-22
===============================================================================

  # List of changes since Clutter 1.16.4

    - Allow ClutterScript definitions for Interval and Transition classes
    ClutterInterval instances can be defined, and used, in ClutterScript
    UI definition files.

    - Add generic API for event filtering
    Event filtering is meant to be used to intercept events before they
    reach the scene graph.

    - Deprecated ClutterTableLayout
    The Table layout manager is fully superceded by ClutterGridLayout, which
    supports dynamic grid layouts, RTL flipping, expansion and alignment of
    children using the ClutterActor flags, and implicit animations using the
    actor's easing state.

    - Allow GestureAction subclasses to change the trigger edge
    GestureAction can emit the ::gesture-begin signal depending on the
    value of the :threshold-trigger-edge property. Using this property it
    is possible to specify whether the gesture begins after a certain
    threshold is passed; before a certain threshold is passed; or
    immediately.

    - Use the window scaling factor when creating Cairo surfaces
    ClutterCanvas will use the window scaling factor setting when creating
    Cairo surfaces; it is also possible to set the scaling factor on a
    per-instance basis, for future compatibility.

    - Detect window scaling factor automatically on X11
    Use the XSETTING exposed by the environment to change the window
    scaling factor.

    - Support ClutterStage cursor visibility in the Wayland backend
    It is possible to show and hide the cursor on the Stage on Wayland.

    - Translations updates
    Czech, Greek, Hebrew, Chinese simplified, Brazilian Portuguese,
    Galician, Italian, Spanish.

  # List of bugs fixed since Clutter 1.16.4

    705915 - Support high dpi displays
    722322 - check coordinate validity in do_pick()
    710229 - Restore initial ClutterGestureAction behavior
    719900 - ClutterStageCogl: Clip in the right coordinate system
    719716 - Make test-clip friendly for people with only one mouse button
    719368 - Don't queue redraws when reallocating actor that haven't moved
    719367 - Bind constraints: Don't force redraws on source relayout
    712816 - device-manager-evdev: Stop using deprecated libevdev API
    712812 - Crash and memory leak fixes for device removals
    712563 - Fixes for cogl journal usage when picking
    707560 - Event filter
    712322 - input-device-xi2: Calculate the correct state for button events

Many thanks to:

  Jasper St. Pierre, Rui Matos, Owen W. Taylor, Alejandro Pineiro, Lionel
  Landwerlin, Bastian Winkler, Neil Roberts, Rafael Ferreira, Chun-wei Fan,
  Daniel Mustieles, Dimitris Spingos, Enrico Nicoletto, Florian Mullner, Fran
  Dieguez, Jonas Adahl, Marek Cernocky, Milo Casagrande, Piotr Drag, Robert
  Bragg, Sphinx Jiang, Yosef Or Boczko