The ABI and API changed in 2.4.2. So get rid of BUILDLINK_ABI_DEPENDS.fontconfig. And increase BUILDLINK_API_DEPENDS.fontconfig to fontconfig>=2.4.2.
Noticed this when using a binary package for qt4-libs built on
different system:

/usr/pkg/qt4/lib/libQtGui.so: undefined reference to `FcFreeTypeQueryFace'

I am not bumping the PKGREVISIONs for all the dependents, since the
upgrade to fontconfig 2.4.2 happened ten months ago.