libcdr: update to 0.1.6.
2020-02-02  Fridrich Štrba  <fridrich.strba@bluewin.ch>  [bd969c36b580f5de0cc30fe1badf4f1b8361c05d]

	Fix txsm for version 15


2020-02-02  Fridrich Štrba  <fridrich.strba@bluewin.ch>  [496e288d9e5450ed7db8324b51a1767377f0125a]

	improve readFild for versions 13 and up


2019-10-09  Albert Astals Cid  <aacid@kde.org>  [4b28c1a10f06e0a610d0a740b8a5839dcec9dae4]

	CDROutputElementList::draw: Micro perfomance improvement

	make the auto variable of the for loop const &, otherwise there's a copy
	involved. Copying a shared_ptr is not very expensive but not copying it
	is cheaper :)

2019-10-08  Albert Astals Cid  <aacid@kde.org>  [012bce64e08d45c9ce37c9c6758e8556cebf8688]

	Fix -Wdeprecated-copy warnings

	New gcc complains when you're using the default defined operator= but
	your class has an explicitely defined copy constructor.

	This is because if you implemented the copy constructor is usually
	because you needed something special, so you'll need that special in the
	assignment operator.

	In the cases here it's not really a problem since the explicitely
	defined constructors where just doing the same as the default so i've
	just marked them as default as well as the assignment operator

	Example:

	CDRParser.cpp: In member function ‘void libcdr::CDRParser::readFont(librevenge::RVNGInputStream*, unsigned int)’:
	CDRParser.cpp:2550:53: warning: implicitly-declared ‘libcdr::CDRFont& libcdr::CDRFont::operator=(const libcdr::CDRFont&)’ is deprecated [-Wdeprecated-copy]
	 2550 |     m_fonts[fontId] = CDRFont(fontName, fontEncoding);
	      |                                                     ^
	In file included from CDRParser.h:18,
	                 from CDRParser.cpp:10:
	CDRTypes.h:372:3: note: because ‘libcdr::CDRFont’ has user-provided ‘libcdr::CDRFont::CDRFont(const libcdr::CDRFont&)’
	  372 |   CDRFont(const CDRFont &font)
	      |   ^~~~~~~

2019-07-02  Stephan Bergmann  <sbergman@redhat.com>  [5da3e01b9aa19f8676e052e98815b861311222b9]

	Avoid UB converting from double to int via unsigned

	See <https://gerrit.libreoffice.org/#/c/73181/> "external/libcdr: Avoid UB
	converting from double to int via unsigned" for details.

2019-01-29  Miklos Vajna  <vmiklos@collabora.com>  [d89355ea031e2ecaa66a0c397bd043ab43051bbc]

	Fix too small loop variables

	These loop variables had narrower type than the iteration's upper bound.


2019-01-28  Miklos Vajna  <vmiklos@collabora.com>  [00c4b331df8157dff7c251323d00ec2d63691dfb]

	Add missing include

	CMXParser.cpp:42:43: error: expected ')'
	    CDR_DEBUG_MSG(("invalid tag length %" PRIu16 "\n", tagLength));
	                                          ^
	CMXParser.cpp:42:19: note: to match this '('
	    CDR_DEBUG_MSG(("invalid tag length %" PRIu16 "\n", tagLength));
	                  ^
	1 error generated.


2018-12-29  David Tardon  <dtardon@redhat.com>  [10211e95bb95d05c2261819c88b7f48d9db20b32]

	fix conditional