Update to 1.1.4:
This release provides the fixes for the recently announced security issues
CVE-2013-2002 & CVE-2013-2005, along with other code & doc cleanups, build
fixes, automake compatibility changes, and packaging improvements.

Adam Jackson (1):
      configure: Remove AM_MAINTAINER_MODE

Alan Coopersmith (5):
      unifdef -U__UNIXOS2__
      Unchecked return values of XGetWindowProperty [CVE-2013-2005]
      unvalidated length in _XtResourceConfigurationEH [CVE-2013-2002]
      Remove old strtoul workaround for SunOS 4
      libXt 1.1.4

Colin Walters (1):
      autogen.sh: Implement GNOME Build API

Egbert Eich (2):
      Install ErrorDB into a $datarootdir-path, not $libdir.
      Add XtErrorDB directory to pkg-config file.

Eric S. Raymond (2):
      Eliminate use of tab stops.
      Remove unused macros that are temptations to presentation-level klugery.

Julien Cristau (1):
      Add copyright notice and license from the X Consortium to COPYING

Thierry Reding (1):
      Use AM_CPPFLAGS instead of INCLUDES

Thomas Klausner (2):
      Avoid referencing something that isn't defined. Bring in the definition from another manual page.
      Fix DEBUG build (TMparse.c:376:1: error: overflow in implicit constant conversion)