gam: update to 7.32.06
Changes since 7.29.01:

7.32.06

Added options to gam <UserTypeEntity> copy drivefile ... copysubfiles to limit copying to files whose modifiedTime meets specified requirements.

    start|starttime <Date>|<Time> - If specified, modifiedTime must be >= the value
    end|endtime <Date>|<Time> - If specified, modifiedTime must be <= the value
    range <Date>|<Time> <Date>|<Time> - first value <= modifiedTime <= second value

7.32.05

Fixed bug in gam <UserTypeEntity> print messages|threads ... headers <SMTPHeaderList> where headers other than those specified in <SMTPHeaderList> were displayed.

Updated gam info users <UserTypeEntity> to display the following data when the Licensing API does not return data due to quota limits. Previously, no License data was displayed and there was no way to know if it was omitted due to API quota limits vs the user has no license?

  Licenses: (1)
    Not available/incomplete

If a user has no licenses, this will be displayed.

  Licenses: (0)

You should use license_skus = <SKUIDList> in gam.cfg to list all of the licensing SKUs used in your workspace. Without this list, GAM has to make 70+ API calls to get the licenses for a user; this can cause quota limit errors.

7.32.04

Support for student groups in Google Classroom no longer requires Developer Preview membership.

Upgraded to OpenSSL 3.6.1.

7.32.03

Added option template as an additional formating option for gam <UserTypeEntity> show signature that displays just the HTML data; this simplifies capturing the data for use as input to GAM.

$ gam redirect stdout ./SigTemplate.html user user@domain.com show signature template
$ more SigTemplate.html
<div dir="ltr"><div dir="ltr"><div dir="ltr">
<p style="margin:0px;font-size-adjust:none;font-stretch:normal;font-size:12px;line-height:normal;font-family:Monaco;color:rgb(0,0,0)">
<span style="background-color:rgb(82,208,206)">{RT}Email: {Email}{/RT}</span></p>
<p style="margin:0px;font-size-adjust:none;font-stretch:normal;font-size:12px;line-height:normal;font-family:Monaco;color:rgb(0,0,0)">
<span style="background-color:rgb(82,208,206)">{RT}Phone: {Phone}{/RT}</span></p>
<p style="margin:0px;font-size-adjust:none;font-stretch:normal;font-size:12px;line-height:normal;font-family:Monaco;color:rgb(0,0,0)">
<span style="background-color:rgb(82,208,206)">{RT}Mobile: {Mobile}{/RT}</span></p>
</div><br></div>\n</div>

7.32.02

Added variable oauth2_txt_lock_mode to gam.cfg, the default is 644 and valid values are: 644, 664, 666. This value is used to set the file permissions on the oauth2.txt.lock file. In very special cases where daemon processes, e.g. Apache/httpd, are running GAM, the value 666 may have to be used.

7.32.01

Added option (addcsvdata <FieldName> <String>)* to gam <CrOSTypeEntity> issuecommand command <CrOSCommand> csv and gam <CrOSTypeEntity> getcommand commandid <CommandID> csv that adds additional columns of data to the CSV file output.

    See: https://github.com/GAM-team/GAM/wiki/ChromeOS-Devices#bulk-action-example

7.32.00

Added option verifyallowexternal to gam print cigroup-members|group-members that causes GAM to only display external members in groups with `allowExternalMembers=False'. This option can be used to help verify that internal-only groups don't have external members.

Updated option internaldomains for the following commands:

gam info|print groups
gam print|show group-members
gam info|print cigroups
gam print|show cigroup-members
gam <UserTypeEntity> print|show filesharecounts

Which domains are considered internal domains:

    internaldomains all - All of your workspace domains; this is the default
    internaldomains primary - Your workspace primary domain
    internaldomains <DomainNameList> - A list of domain names

Added option csv to gam <CrOSTypeEntity> issuecommand command <CrOSCommand> and gam <CrOSTypeEntity> getcommand commandid <CommandID> so that command details are displayed in CSV format. This can be used to log commands issued to devices and then monitor the results.

Added option filemimetype category <MimeTypeNameList> to gam <UserTypeEntity> copy drivefile to support copying of files based on their MimeType category.

Added option attendeeslist to gam calendars <CalendarEntity> print events and gam <UserTypeEntity> print events that causes GAM to display the attendee email addresses in a single column attendeesList; no attendee details are displayed. The email addresses are separated by csv_output_field_delimiter from gam.cfg.

Fixed bug in gam sendemail ... replyto <EmailAddress> that caused a message delivery error if <EmailAddress> did not include a domain name.

Added support for users's chat sections.

    See: https://github.com/GAM-team/GAM/wiki/Users-Chat#manage-chat-users-sections
    This is in Deveoper Preview; you must have a developer_preview_api_key in gam.cfg to use these commands.

7.31.06

Added option batchsize <Integer> to gam calendar <CalendarEntity> delete|purge events and gam <UserTypeEntity> delete|purge events <UserCalendarEntity> that causes GAM to delete events with batch API calls rather than with individual API calls.

7.31.05

Added option variables <RESearchPattern> to gam select section <SectionName> verify and gam config verify that causes GAM to only display variables with names selected by <RESearchPattern>.

gam select School verify variables "^(customer|domain)"
Section: School
  customer_id = C03abc123
  domain = school.edu

gam config verify variables  'dir'
Section: DEFAULT
  cache_dir = ~/GamConfig/gamcache ; /Users/gamteam/GamConfig/gamcache
  config_dir = ~/GamConfig ; /Users/gamteam/GamConfig
  drive_dir = ~/GamWork ; /Users/gamteam/GamWork
  gmail_cse_incert_dir = ~/GmailCSE/Certs ; /Users/gamteam/GmailCSE/Certs
  gmail_cse_inkey_dir = ~/GmailCSE/Keys ; /Users/gamteam/GmailCSE/Keys
  input_dir = .

7.31.04

Fixed bug in gam report admin|chrome that caused to events to not be displayed.

Updated gam <UserTypeEntity> print|show messages|threads ... query <QueryGmail> to display the query.

7.31.03

Due to the following Calendar API update, the gam <UserTypeEntity> transfer calendars command has been removed.

    See: https://developers.google.com/workspace/calendar/release-notes#October_27_2025 Data ownership can be transferred in the Google Calendar UI.

7.31.02

Added the following options to gam <UserTypeEntity> copy drivefile to limit copying to those files owned by selected users.

    copysubfilesownedby users <EmailAddressList> - Only files owned by users in <EmailAddressList> are copied.
    copysubfilesownedby notusers <EmailAddressList> - Only files not owned by users in <EmailAddressList> are copied.
    copysubfilesownedby regex <REMatchPattern> - Only files owned by users whose email addresses match <REMatchPattern> are copied.
    copysubfilesownedby notregex <REMatchPattern> - Only files owned by users whose email addresses do not match <REMatchPattern> are copied.

7.31.01

Code cleanup for addcsvdata <FieldName> <String>.

7.31.00

Fixed bug in gam report chrome (user <UserItem>)|(select <UserTypeEntity>) where no activities were returned. report chrome does not use the parameter userKey=<EmailAddress> as do other applications but requires parameter filter DEVICE_USER==<EmailAddress>.

Updated gam report admin (user <UserItem>)|(select <UserTypeEntity>) to use parameter filter USER_EMAIL==<EmailAddress> to display activiities affecting the user <EmailAddress>. Use option userisactor to use the parameter userKey=<EmailAddress> that displays activities where user <EmailAddress> executed the command that generated the activity.

Fixed bug in gam print cros|filelist|users ... (addcsvdata <FieldName> <String>)+ formatjson where the addcsvdata columns were not displayed but the additional field values were included in the JSON data. Now, the addcsvdata columns are displayed but the additional field values are only included in the JSON data when option includdecsvdatainjson is specified.

Added option addcsvdata <FieldName> <String> to gam <UserTypeEntity> print cigroups|groups that adds additional columns of data to the CSV file output.

Added option addcsvdata <FieldName> <String> to gam <UserTypeEntity> print cigroupmembere|group-members that adds additional columns of data to the CSV file output.

7.30.05

Added option gmaileventtypes <NumberRangeList> to gam report gmail that can be used to limit the event types displayed.

<NumberRange> ::= <Number>|(<Number>/<Number>)
<NumberRangeList> ::= "<NumberRange>(,<NumberRange>)*"

gam report gmail user user@domain.com gmaileventtypes 1,10/11

    See: https://developers.google.com/workspace/admin/reports/v1/appendix/activity/gmail

Updated sorting of column headers in gam report <ActivityApplicationName>.

7.30.04

Updated gam report gmail to avoid the following error when incomplete start/end time information is provided.

ERROR: Invalid request: Start time and end time should both be provided, and the scan duration should not be greater than 30 days.

    No time information provided - GAM sets range -30d today
    Only start <Time> provided - GAM sets end <Time>+30d
    Only end <Time> provided - GAM sets start <Time>-30d

7.30.03

Updated gam report <ActivityApplicationName> to reflect the changes described here:

    See: https://workspaceupdates.googleblog.com/2025/12/google-workspace-audit-log-api.html

Added option resourcedetailsfilter <String> to gam report <ActivityApplicationName> described here:

    See: https://developers.google.com/workspace/admin/reports/reference/rest/v1/activities/list#query-parameters

For gam <UserTypeEntity> print <Objects>, expanded the list of <Objects> covered by gam.cfg csv_output_users_audit = True.

7.30.02

Added option conferencedata meet <MeetID> to <EventAttribute> that allows specifying a reference to an existing Google Meet when creating/updating a calendar event.

Upgraded to Python 3.14.2.

7.30.01

Fixed bug introduced in 7.30.00 that caused errors when reading CSV files.

Added the following options to gam <UserTypeEntity> create focustime|outofoffice:

((date yyyy-mm-dd)|
 (range yyyy-mm-dd yyyy-mm-dd)|
 (daily yyyy-mm-dd N)|
 (weekly yyyy-mm-dd N))

Added the following options to gam <UserTypeEntity> create focustime|outofoffice|workinglocation:

noreminders|(reminder email|popup <Number>)+

7.30.00

Added input_dir directory variable to gam.cfg that is used to select a directory for reading files with non-absolute file names. The default is an empty string that matches the current behavior where these files are read from the current working directory. This will be most useful in multiple domain situations where each domain will have distinct drive_dir and input_dir values.

Added support for the new resource calendar setting autoAcceptInvitations.

7.29.04

Updated gam delete chromepolicy chrome.users.apps.InstallType ou <OrgUnitItem> appid <AppID> to allow deleting an app, i.e., explicitly remove it from management. <OrgUnitItem> must specify where it was added for management.

7.29.03

Remove debugging message from gam <UserTypeEntity> move drivefile <DriveFileEntity>.

7.29.02

Fixed bug in gam <UserTypeEntity> move drivefile <DriveFileEntity> where the following options were only applied to top level files or folders re-created in the destination. Now, domain and email address mappings apply to all moved files/folders.

excludepermissionsfromdomains <DomainNameList>
includepermissionsfromdomains <DomainNameList>
mappermissionsdomain <DomainName> <DomainName>
mappermissionsemail <EmailAddress> <EmailAddress>
mappermissionsemailfile <CSVFileInput> endcsv

Upgraded to Python 3.14.1.