py-djangorestframework: updated to 3.9.0
3.9.0:
Improvements to ViewSet extra actions
Fix action support for ViewSet suffixes
Allow action docs sections
Deprecate the Router.register base_name argument in favor of basename.
Deprecate the Router.get_default_base_name method in favor of Router.get_default_basename.
Change CharField to disallow null bytes. To revert to the old behavior, subclass CharField and remove ProhibitNullCharactersValidator from the validators. python class NullableCharField(serializers.CharField): def __init__(self, *args, **kwargs): super().__init__(*args, **kwargs) self.validators = [v for v in self.validators if not isinstance(v, ProhibitNullCharactersValidator)]
Add OpenAPIRenderer and generate_schema management command.
Add OpenAPIRenderer by default, and add schema docs.
Allow permissions to be composed
Allow nullable BooleanField in Django 2.1
Add testing of Python 3.7 support
Test using Django 2.1 final release.
Added djangorestframework-datatables to third-party packages
Change ISO 8601 date format to exclude year/month
Update all pypi.python.org URLs to pypi.org
Ensure that html forms (multipart form data) respect optional fields
Allow hashing of ErrorDetail.
Correct schema parsing for JSONField
Render descriptions (from help_text) using safe
Removed input value from deault_error_message
Added min_value/max_value support in DurationField
Fixed instance being overwritten in pk-only optimization try/except block
Fixed AttributeError from items filter when value is None
Fixed Javascript e.indexOf is not a function error
Fix schemas for extra actions
Improved get_error_detail to use error_dict/error_list
Imprvied URLs in Admin renderer
Add "Community" section to docs, minor cleanup
Moved guardian imports out of compat
Deprecate the DjangoObjectPermissionsFilter class, moved to the djangorestframework-guardian package.
Drop Django 1.10 support
Only catch TypeError/ValueError for object lookups
Handle models without .objects manager in ModelSerializer.
Improve ModelSerializer.create() error message.
Fix CSRF cookie check failure when using session auth with django 1.11.6+
Updated JWT docs.
Fix autoescape not getting passed to urlize_quoted_links filter