libuv: updated to 1.39.0
Changes since version 1.38.1:
* unix: use relaxed loads/stores for clock id
* build,win: link to user32.lib and advapi32.lib
* unix: squelch harmless valgrind warning
* include: fx c++ style comments warnings
* build,cmake: Change installation location on MinGW
* linux: use copy_file_range for uv_fs_copyfile when possible
* win,tcp: avoid reinserting a pending request
* docs: improve the descriptions for get memory info
* test: add udp-mmsg test
* udp: add uv_udp_using_recvmmsg query
* doc: add more error constants
* zos: fix potential event loop stall
* include: add internal fields struct to uv_loop_t
* core: add API to measure event loop idle time
* win,fs: use CreateDirectoryW instead of _wmkdir
* win,nfc: fix integer comparison signedness
* win,nfc: use
* win,nfc: removed some unused variables
* win,nfc: add missing return statement
* win,nfc: disable clang-format for
* darwin: use IOKit for uv_cpu_info
* test: fix thread race in process_title_threadsafe
* win,fs: avoid implicit access to _doserrno
* test: give hrtime test a custom 20s timeout
* build: add more failed test, for qemu version bump
* unix: handle src, dest same in uv_fs_copyfile()
* unix: error when uv_setup_args() is not called
* aix: protect uv_exepath() from uv_set_process_title()
* fs: clobber req->path on uv_fs_mkstemp() error
* cmake: fix compile error C2001 on Chinese Windows
* test: avoid double evaluation in ASSERT_BASE macro
* tcp: fail instantly if local port is unbound
* doc: fix most sphinx warnings
* nfci: address some style nits
* unix: don't use _POSIX_PATH_MAX