gcc48: fix build error on netbsd/arm
configs for gcc on netbsd don't build -march=native support, but this
stray prototype was left, causing build errors:

gcc.o:(.rodata+0x58c4): undefined reference to
`host_detect_local_cpu(int, char const**)'