Move comment explaining that swing must be downloaded manually and is thus disabled by default onto the same line with the swing SUBDIR+=, so that lintpkgsrc doesn't complain.  Fixes:
ERROR:    x11/swing is disabled without a reason being listed in x11/Makefile
          Please add a comment to x11/Makefile indicating why x11/swing is disabled