Update to latest release, 0.24.3. Remove bl3 file, as this package does not install any shared libraries. Clean up Makefile. Update patch. DEPENDS on py-logilab-common>=0.53.0 instead of using old bl3 file from that package.
2013-04-16  --  0.24.3
    * #124360 [py3.3]: Don't crash on 'yield from' nodes
    * #123062 [pylint-brain]: Use correct names for keywords for urlparse
    * #123056 [pylint-brain]: Add missing methods for hashlib
    * #123068: Fix inference for generator methods to correctly handle yields
      in lambdas.
    * #123068: Make sure .as_string() returns valid code for yields in
      expressions.
    * #47957: Set literals are now correctly treated as inference leaves.
    * #123074: Add support for inference of subscript operations on dict
      literals.

2013-02-27  --  0.24.2
    * pylint-brain: more subprocess.Popen faking (see #46273)
    * #109562 [jython]: java modules have no __doc__, causing crash
    * #120646 [py3]: fix for python3.3 _ast changes which may cause crash
    * #109988 [py3]: test fixes

2012-10-05  --  0.24.1
    * #106191: fix __future__ absolute import w/ From node
    * #50395: fix function fromlineno when some decorator is splited on
      multiple lines (patch by Mark Gius)
    * #92362: fix pyreverse crash on relative import
    * #104041: fix crash 'module object has no file_encoding attribute'
    * #4294 (pylint-brain): bad inference on mechanize.Browser.open
    * #46273 (pylint-brain): bad inference subprocess.Popen.communicate

2012-07-18  --  0.24.0
    * include pylint brain extension, describing some stuff not properly understood until then.
      (#100013, #53049, #23986, #72355)
    * #99583: fix raw_building.object_build for pypy implementation
    * use `open` rather than `file` in scoped_nodes as 2to3 miss it

2011-12-08  --  0.23.1
    * #62295: avoid "OSError: Too many open files" by moving
      .file_stream as a Module property opening the file only when needed
    * Lambda nodes should have a `name` attribute
    * only call transformers if modname specified

2011-10-07  --  0.23.0
    * #77187: ancestor() only returns the first class when inheriting
      from two classes coming from the same module
    * #76159: putting module's parent directory on the path causes problems
      linting when file names clash
    * #74746: should return empty module when __main__ is imported (patch by
      google)
    * #74748: getitem protocal return constant value instead of a Const node
      (patch by google)
    * #77188: support lgc.decorators.classproperty
    * #77253: provide a way for user code to register astng "transformers"
      using manager.register_transformer(callable) where callable will be
      called after an astng has been built and given the related module node
      as argument

2011-07-18  --  0.22.0
    * added column offset information on nodes (patch by fawce)
    * #70497: Crash on AttributeError: 'NoneType' object has no attribute '_infer_name'
    * #70381: IndendationError in import causes crash
    * #70565: absolute imports treated as relative (patch by Jacek Konieczny)
    * #70494: fix file encoding detection with python2.x
    * py3k: __builtin__ module renamed to builtins, we should consider this to properly
      build ast for builtin objects

2011-01-11  --  0.21.1
    * python3: handle file encoding; fix a lot of tests
    * fix #52006: "True" and "False" can be assigned as variable in Python2x
    * fix #8847: pylint doesn't understand function attributes at all
    * fix #8774: iterator / generator / next method
    * fix bad building of ast from living object w/ container classes
      (eg dict, set, list, tuple): contained elements should be turned to
      ast as well (not doing it will much probably cause crash later)
    * somewhat fix #57299 and other similar issue: Exception when
      trying to validate file using PyQt's PyQt4.QtCore module: we can't
      do much about it but at least catch such exception to avoid crash