ImageMagick: update to 7.1.1.26.
7.1.1-26 - 2024-01-07
Merged

    Make Magick++-config work from non-standard places #7008

Fixed

    Make Magick++-config work from non-standard places (#7008) #7007

Commits

    beta release 15b1a5d
    Improved name of installer artifacts 2d36d1a
    Trim version to avoid trailing - 6c76d71
    support -alpha remove-opaque option 0ce621f
    Reverted incorrect patch. 3ee902d
    reduce # threads for -alpha option 8876f13
    -alpha deactivate-if-opaque disables the alpha channel if and only if its entirely opaque 66ef758
    -alpha off-if-opaque turns off the alpha channel if its entirely opaque e9a68f0
    slight optimization e6f0530
    fix error: 'libraw_data_t' has no member named 'rawparams' 1294dac
    thread tuning c29cf7f
    Silenced warning. b8fd1e7
    thread tunuing 80cb07d
    optimize HDRI detection f8ba278
    factor is a const argument 3e2879e
    Fixed build on Windows. 0f0ccfd
    Removed duplicate define. 79e742a
    The CheckPSDChannels method should not check empty layers. e5162e6
    Use consistent casing of method names. cbf79ad
    Allow invalid webp files that incorrectly include the size of the header in the length. 99c9ee4
    ImageMagick/ImageMagick#7006 8e1b405
    cosmetic 9033dea
    improve RSVG exception checking (ImageMagick/ImageMagick#7005) 802ffae
    fix off-by-one issue for captions/labels (ImageMagick/ImageMagick#7004) e80133b
    fix caption sizing issue (ImageMagick/ImageMagick#7004) 2d24367
    correct off by one issue 90ac70a
    correct usage a5dbba6
    fix off-by-one error a12f6d1
    release 83eefaf