Update deskbar-applet to 2.26.0.
=====================
deskbar-applet 2.26.0
=====================

This is the first stable release of the 2.26 series.

Translations:
- Updated as: Amitakhya Phuka
- Updated bn_IN: Runa Bhattacharjee
- Updated el: Jennie Petoumenou
- Updated et: Priit Laes
- Updated gl: Ignacio Casal Quinteiro
- Updated gu: Ankitkumar Patel
- Updated he: Yair Hershkovitz
- Updated hu: Gabor Kelemen
- Updated lt: Gintautas Miliauskas
- Updated ml: Praveen Arimbrathodiyil, Ani Peter
- Updated mr: Sandeep Shedmake
- Updated nb: Kjartan Maraas
- Updated or: MAnoj Kumar Giri
- Updated ru: Nickolay V. Shmyrev
- Updated ta: I. Felix
- Updated te: Krishnababu K
- Updated tr: Baris Cicek

Help Manual Translations:
-Updated en_GB: Jen Ockwell

======================
deskbar-applet 2.25.92
======================

- Fixed #572291, Bookmark search doesn't match on Epiphany topics (Sebastian Pölsterl)

Translations:
- Updated ca: Gil Forcada
- Updated de: Nathan-J. Hirschauer
- Updated en_GB: Philip Withnall, David Lodge
- Updated fr: Bruno Brouard
- Updated gu: Sweta Kothari
- Updated it: Milo Casagrande
- Updated kn: Shankar Prasad
- Updated ko: Changwoo Ryu
- Updated lv: Raivis Dejus
- Updated pt_BR: Krix Apolinário, Jonh Wendell

Help Manual Translations:
- Updated de: Mario Blättermann

======================
deskbar-applet 2.25.91
======================

- Fixed bug that only local GTK bookmarks showed up.
- Searching for bookmark name is case insensitive now.
- Check if there's an default application to open the url in ShowUrlAction.is_valid
- Fixed bug that first and last category where not selectable with keyboard
- Select last item when Enter is pressed in entry when the applet is on the bottom panel
- Set correct sort order of CuemiacTreeView at startup

Translations:
- Updated be@latin: Ihar Hrachyshka
- Updated bg: Alexander Shopov
- Updated cs: Pavel Šefránek
- Updated eu: Iñaki Larrañaga Murgoitio
- Updated fi: Ilkka Tuohela
- Updated ja: Takeshi AIHANA
- Updated nb: Kjartan Maraas
- Updated pl: Tomasz Dominikowski
- Updated pt: Duarte Loreto
- Updated ro: Jani Monoses, Adi Roiban
- Updated sv: Daniel Nylander
- Updated th: Theppitak Karoonboonyanan
- Updated vi: Clytie Siddall
- Updated zh_HK: Chao-Hsiung Liao
- Updated zh_TW: Chao-Hsiung Liao

======================
deskbar-applet 2.25.90
======================
- Fixed #569260, crash in Deskbar: started typing 3 (based on patch by Tom Parker)
- Fixed #528184, Write OpenSearch module (based on work by Arthur Perton)
- Fixed #419211, Web search in new a browser window (Sebastian Pölsterl)
- Fixed #542861, Deskbar applet has a pixel border when placed at the edge of the screen (Sebastian Pölsterl)
- Fixed #557801, Results category nodes are not keyboard focusable (Sebastian Pölsterl)
- Fixed #569093, use indexer for path searches (patch by Juri Pakaste)
- Fixed #570059, Strings from .ui files missing from translation template (Sebastian Pölsterl)
- Fixed bug that same GoogleCodeSearchMatch has been added multiple times and assign priorities to matches (Sebastian Pölsterl)
- Added match to yahoo, googlesearch and googlecodesearch that opens the results in the browser (Sebastian Pölsterl)

Translations:
- Updated ca: Gil Forcada
- Updated da: Kenneth Nielsen
- Updated es: Jorge González
- Updated fi: Ilkka Tuohela
- Updated gu: Sweta Kothari
- Updated hu: Gabor Kelemen
- Updated ko: Changwoo Ryu
- Updated nb: Kjartan Maraas
- Updated pt_BR: Daniel S. Koda

=====================
deskbar-applet 2.25.5
=====================

- Fixed #567422, Add missing include to eggaccelerators.c (patch by Magnus Boman)
- Fixed launch_default_for_uri_and_scheme function to work with ghelp and mailto addresses (Sebastian Pölsterl)

Translations:
- Updated ca: Gil Forcada
- Updated he: Yair Hershkovitz, Mark Krapivner
- Updated sv: Daniel Nylander
- Updated th: Theppitak Karoonboonyanan

=====================
deskbar-applet 2.25.4
=====================

- Fixed #558858, Deskbar stops working when closing by 'x' (Sebastian Pölsterl)
- Fixed #564726, configure doesn't detect pygtk in alternative directories (patch by Frederic Peters)

Translations:
- Updated be@latin: Ihar Hračyška
- Updated el: Jennie Petoumenou
- Updated es: Jorge González
- Updated hu: Gabor Kelemen
- Updated nb: Kjartan Maraas

=====================
deskbar-applet 2.25.3
=====================

- Show windows that are part of viewport that is currently not visible (Daniel Wutke)

=====================
deskbar-applet 2.25.2
=====================

Despite bug fixes this release adds a new reboot action.

- Fixed #552204, AttributeError: 'NoneType' object has no attribute 'get_actions' in __get_match_action_for_cell (Sebastian Pölsterl)
- Fixed #559169, gnome power manager has new dbus path, this breaks some code in gdmaction module (patch by Christian Assing)
- Fixed #560190, Added RebootAction and RebootMatch (Sebastian Pölsterl)
- Fixed #561181, Support both simplejson and json module (Sebastian Pölsterl)

Translations:
- Updated es: Jorge González
- Updated pt_BR: Leonardo Gregianin, Og Maciel
- Updated sv: Daniel Nylander

=====================
deskbar-applet 2.25.1
=====================

In this release all gnomevfs calls have been ported
to gio and from glade files are replaced GTK builder UI
files. Therefore, pygobject 2.15.3 or later is required.

- Fixed #557570, Crash when proxy port changed (Sebastian Pölsterl)
- Fixed #551218, Use of strings "Croation" and "Croatian" (Sebastian Pölsterl)
- Fixed #552203, Typo: affect (Sebastian Pölsterl)

Translations:
- Updated ast: Gil Forcada, Astur
- Updated de: Christian Kirbach
- Updated ja: Takeshi AIHANA
- Updated uk: Maxim Dziumanenko