py-tox: updated to 3.5.2
v3.5.2:
Bugfixes
- session packages are now put inside a numbered directory (instead of prefix numbering it,
  because pip fails when wheels are not named according to PEP-491 , and prefix numbering messes with this)

Features
- level three verbosity (-vvv) show the packaging output


v3.5.1:
Bugfixes
- fix regression with 3.5.0: specifying --installpkg raises AttributeError: 'str' object has no attribute 'basename'


v3.5.0:
Bugfixes
- intermittent failures with --parallel--safe-build, instead of mangling with the file paths now uses a lock to make the package build operation thread safe and is now on by default (--parallel--safe-build is now deprecated)

Features
- Added temp_dir folder configuration (defaults to {toxworkdir}/.tmp) that contains tox
  temporary files. Package builds now create a hard link (if possible, otherwise copy - notably in
  case of Windows Python 2.7) to the built file, and feed that file downstream (e.g. for pip to
  install it). The hard link is removed at the end of the run (what it points though is kept
  inside distdir). This ensures that a tox session operates on the same package it built, even
  if a parallel tox run builds another version. Note distdir will contain only the last built
  package in such cases.