glib2 glib2-tools gdbus-codegen: updated to 2.84.2
Overview of changes in GLib 2.84.2, 2025-05-20

* Bugs fixed:
  - Backport “gclosure: fix ATOMIC_CHANGE_FIELD to read vint
    atomically” to glib-2-84
  - Backport “Windows: fix wrong typelib path” to glib-2-84
  - Backport "gstring: carefully handle gssize parameters"
  - Backport “Update macOS job for new CI runner” to glib-2-84
  - Backport “gdate: Call tzset before localtime_r” to glib-2-84
  - Backport -Wsign-conversion fixes for g_get_locale_variants() from
    to glib-2-84
  - Backport “glocalfile: Disable faccessat()-based query_exists on
    Android” to glib-2-84


Overview of changes in GLib 2.84.1, 2025-04-03

* Fix test failure when building against gobject-introspection ≥1.83.4

* Bugs fixed:
  - 2.84.0 build failure on Linux: ../gio/gnetworkmonitornetlink.c:47:10:
    fatal error: netlink/netlink_route.h: No such file or directory (Philip
    Withnall)
  - test failure with gobject-introspection 1.83.4: warning: element
    doc:format from state 3 is unknown, ignoring (Philip Withnall)
  - gio/trash does not handle special characters well
  - `g_cancellable_connect()` documentation incorrect (Marco Trevisan
    (Treviño))
  - g_cancellable_connect(): is it safe to unref cancellable from
    callback? (Marco Trevisan (Treviño))
  - Crash with some registry key values in GWin32AppInfo (Philip Withnall)
  - Memory sanitizer fixes
  - gobject: Be consistent in using atomic logic to handle the
    GParamSpecPool
  - gsettings: Port docs to gi-docgen format, add missing annotations and
    make various improvements
  - tests: Don't install runner scripts without installed_tests
  - Update French translation
  - Update Catalan translation
  - Update Turkish translation
  - Updated Danish translation
  - Update Persian translation
  - docs: Document GSignalFlags members added after 2.0
  - Update Indonesian translation
  - tests: Add a test for g_object_freeze_notify() being called too often
  - gfileinfo: Slightly expand docs for
    g_file_info_get_attribute_as_string()
  - gi: Dynamically set doc-format
  - tests: Various fixes to create temporary files in /tmp rather than the
    build directory
  - gdbusnameowning: Convert docs to gi-docgen linking syntax
  - giounix-private: Fix macro for checking for epoll_create1()
  - Fix LGPL in header
  - gutils: make documentation of g_set_prgname() clearer
  - docs: Add some detail
  - Update Romanian translation
  - gspawn-win32: Fix potential integer overflows in argv handling
  - gvarianttype: Improve docs on type validation

* Translation updates:
  - Catalan (Jordi Mas)
  - Danish (Ask Hjorth Larsen)
  - French (Vincent Chatelain)
  - Indonesian (Andika Triwidada)
  - Persian (Danial Behzadi)
  - Romanian (Antonio Marin)
  - Turkish (Sabri Ünal)


Overview of changes in GLib 2.84.0, 2025-03-06

* Bugs fixed:
  - Update Slovenian (sl) translation in glib
  - Update Korean translation
  - tests: Minor fixes to reference and stream-rw_all tests
  - gdebugcontrollerdbus: Fix a minor typo in a code example in the docs
  - Update Hungarian translation

* Translation updates:
  - Hungarian (Balázs Úr)
  - Korean (Changwoo Ryu)
  - Slovenian (Martin)