nghttp2[-tools]: updated to 1.70.0
1.70.0

Require C++23
Adopt Designated initializers part1
Adopt Designated initializers part2
Adopt Designated initializers part3
tests: Make const values static const
src: Rewrite util::split_str and its variants
src: Adopt std::string::resize_and_overwrite
src: Pass std::chrono::{time_point,duration} by value
Bump mruby to 4.0.0
src: Fix warning "space between quotes and suffix is deprecated in C++23"
lib, tests: Use C-style comment
src: Avoid std::chrono::high_resolution_clock
src: Add noexcept to user-defined literals
src: Replace std::optional with std::expected
src/util: Adopt std::expected for error handling
get_socket_error: Return errno of getsockopt if it fails
src: Use util::stream_error
src: Get rid of std::stringstream
src: Modernize Header and HeaderRef
src/http2: Adopt std::expected
src/tls: Adopt std::expected
nghttpx: Adopt std::expected for Connection read/write
Nghttpx dconn expected
Nghttpx downstream expected
Nghttpx http2session expected
Nghttpx upstream expected
Nghttpx clienthandler expected
Nghttpx httpdownstreamconnection expected
Nghttpx expected
Nghttpx http2upstream expected
Nghttpx http3upstream expected
Nghttpx mruby expected
Nghttpx quic expected
nghttpx: Adopt std::expected for QUICConnectionHandler
Nghttpx tls expected
nghttpx: Rewrite time_t_from_asn1_time with ASN1_TIME_diff for boringssl
Nghttpx livecheck expected
Nghttpx dns expected
Nghttpx memcached expected
Nghttpx misc expected
Nghttpx worker expected
Nghttpx connhandler expected
nghttpx: Pass WorkerEvent without explicit std::move
nghttpx: Adopt std::expected for worker_process_event_loop
nghttpx: Adopt std::expected for parse_config
Nghttpx config expected
Src fixup
nghttpx: Adopt std::expected for main routines
H2load expected
nghttp: Adopt std::expected
nghttpd: Adopt std::expected
HtmlParser: Adopt std::expected
src: Adopt size_t literal suffix
nghttp: put pseudo headers before normal headers
h2load: Replace std::cerr with std::print
h2load: Replace std::cout with std::print
nghttpx: Migrate to std::print
Nghttp print
Nghttpd print
src: Migrate std::cout to std::print
src: Simplify as_string_view usage
src: Migrate fprintf to C++ counterparts
src: Use std::println without argument to print just line separator
nghttpx: Create CID encryption ctx per worker
nghttpx: Use std::unique_ptr for quic_keying_materials_
Src optimize
src: Provide faster hash functions for OpenSSL forks
src: Adopt std::expected for http2::make_websocket_accept_token
src: NSDMI part1
src: Add noexcept to move ctor and assignment operator
build(deps): bump github.com/quic-go/quic-go from 0.59.0 to 0.59.1
build(deps): bump golang.org/x/net from 0.53.0 to 0.54.0
src: MSDMI part2
Avoid azure ubuntu mirror
src: MSDMI part3
src/allocator: Rewrite concat_string_ref with fold expression
src: Fix build failure on macos26
cmake: Remove CMAKE_CXX_STANDARD 23 that is not needed there
Fix base64 oob
Nghttpx upgrade
Make NGHTTP2_HTTP_FLAG_* macros and make them unsigned
Define flags as macros
Make NGHTTP2_EXTPRI_INC_MASK unsigned
src: Avoid zero-argument std::println
build(deps): bump golang.org/x/net from 0.54.0 to 0.55.0
GHA: Add Cygwin build
Fix docker build
lib: Rewrite integer decoder in http
Bump ngtcp2 and its dependencies
Avoid deprecated ngtcp2 and nghttp3 apis
net: Use macros for win32 hton*/ntoh* fallbacks
lib: Add nghttp2_downcase_byte
Rework HTTP header validation
Bump sfparse
helper: Initialize array with designated initializers
Reformat downcase table
http: Initialize array with designated initializers
Upper case hex integer literals in huffman data table
Upcase hex
Nghttpx h2 stream write timeout
bpf, examples, tests: Upper case hex integer literals
Reformat huffman data table
nghttpx: Provide frontend and backend stream timeouts
build(deps): bump github.com/quic-go/quic-go from 0.59.1 to 0.60.0
nghttpx: Reformat help message to make it editor friendly
nghttpx: Drop connection when frontend write rate is too low
build(deps): bump golang.org/x/net from 0.55.0 to 0.56.0
build(deps): bump actions/checkout from 6 to 7
Bump ngtcp2 and its dependencies
nghttpx: Drop h3 connection when frontend write rate is too low
build(deps): bump actions/cache from 5 to 6
Gcc 16
nghttpx: NGHTTP2_ERR_TEMPORAL_CALLBACK_FAILURE is not allowed in on_frame_recv_callback
nghttpx: Rename completeCb_ to complete_cb_
nghttpx: Remove unused unordered_set include
Require nghttp3 >= 1.17.0
Add the missing header value check for priority header field
build(deps): bump golang.org/x/net from 0.56.0 to 0.57.0
build(deps): bump actions/setup-go from 6 to 7
Count CONTINUATIONS per its frame header
build(deps): bump github.com/quic-go/quic-go from 0.60.0 to 0.61.0
Bump ngtcp2 and its dependencies
Bump neverbleed
Bump llhttp to v9.4.2
nghttpx: Reset quic upstream addr fd to the current path