(geography/R-sf) Fix Build on NetBSD/9.4, GCC_REQD+= 8
Following part can not be handled by gcc-7.5

/usr/include/g++/bits/unique_ptr.h:263:17:   required from 'std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = GDALRasterAttributeTable; _Dp = std::default_delete<GDALRasterAttributeTable>]'

/tmp/geography/R-sf/work/.buildlink/include/gdal_multidim.h:199:55:   required from here
/usr/include/g++/bits/unique_ptr.h:76:22: error: invalid application of 'sizeof' to incomplete type 'GDALRasterAttributeTable'
  static_assert(sizeof(_Tp)>0,