gam: update to 7.10.01
Changs since 7.05.08:

7.10.01

Added options ispublished [<Boolean>] and isacceptingresponses [<Boolean>] to gam <UserTypeEntity> create|update form.

7.10.00

Added commands to manage/display Chat Custom Emojis.

    See: https://github.com/GAM-team/GAM/wiki/Users-Chat#manage-chat-emojis
    See: https://github.com/GAM-team/GAM/wiki/Users-Chat#display-chat-emojis

Updated gam <UserItem> print|show chatspaces|chatmembers asadmin to display the spaces in ascending display name order.
7.09.07


Added webviewlink to <FileTreeFieldName> for use in gam <UserTypeEntity> print|show filetree.

7.09.06

Upddated gam print|show shareddrives, gam print|show shareddriveacls, gam print shareddriveorganizers to display the Shared Drives in ascending name order; the API returns them in an unidentifiable order.

7.09.05

Improved output of gam info|show chromeschemas [std] to more accurately display the schemas.

Fixed bugs in gam update chromepolicy that caused invalid error messaages.

7.09.04

Fixed bug in gam whatis <EmailItem> where the check for an invitable user always failed.

Fixed bug in gam print shareddriveorganizers where no organizers were displayed when domain in gam.cfg was blank.

Updated to Python 3.13.5

7.09.03

Updated gam <UserTypeEntity> create focustime|outofoffice ... timerange <Time> <Time> to check that the first <Time> is less than the second Time; previously the event was not created.

For new installs the enforce_expansive_access Boolean variable in gam.cfg now defaults to True. For existing installations, if enforce_expansive_access has not been added to gam.cfg, a default value of True will be used.

7.09.02

Added command gam info chromeschema std <SchemaName> to display a Chrome policy schema in the same format as Legacy GAM.

Improved output of gam show chromeschemas [std] and gam info chromeschema [std] to more accurately display the schemas.

7.09.01

Fixed bug in gam <UserTypeEntity> print diskusage where the ownedByMe column was blank for the top folder.

Fixed bug in gam update chromepolicy where the following error was generated when updating policies with simple numerical values.

ERROR: Missing argument: Expected <value>"

7.09.00

Removed the overly broad service account IAM and Access Management API scope https://www.googleapis.com/auth/cloud-platform from DWD. The gam <UserTypeEntity> check|Update serviceaccount commands issue an error message if this scope is enabled prompting you to update your service account authorization so that the scope can be removed.

GAM commands that need IAM access now use the more limited scope https://www.googleapis.com/auth/iam in a non-DWD manner.

Added enforce_expansive_access Boolean variable to gam.cfg that provides the default value for option enforceexpansiveaccess in all commands that delete or update drive file ACLs/permissions. It's default value is False.

gam <UserTypeEntity> delete permissions
gam <UserTypeEntity> delete drivefileacl
gam <UserTypeEntity> update drivefileacl
gam <UserTypeEntity> copy drivefile
gam <UserTypeEntity> move drivefile
gam <UserTypeEntity> transfer ownership
gam <UserTypeEntity> claim ownership
gam <UserTypeEntity> transfer drive

Fixed bug in gam print shareddriveorganizers that caused a trap when an organizer was a deleted user.

Updated to Python 3.13.4

7.08.02

Updated the defaults in gam print shareddriveorganizers to match the most common use case, not the script.

    domainlist - The workspace primary domain
    includetypes - user
    oneorganizer - True
    shownoorganizerdrives - True
    includefileorganizers - False

To select organizers from any domain, use: domainlist ""

These commands produce the same result.

gam redirect csv ./TeamDriveOrganizers.csv print shareddriveorganizers domainlist mydomain.com includetypes user oneorganizer shownoorganizerdrives
gam redirect csv ./TeamDriveOrganizers.csv print shareddriveorganizers

7.08.01

Added option shareddrives (<SharedDriveIDList>|(select <FileSelector>|<CSVFileSelector>)) to gam print shareddriveorganizers that displays organizers for a specific list of Shared Drive IDs.

See: https://github.com/GAM-team/GAM/wiki/Shared-Drives#display-shared-drive-organizers

7.08.00

Added the following command that can be used instead of the GetTeamDriveOrganizers.py script.

gam [] print shareddriveorganizers [todrive *] [adminaccessasadmin] [shareddriveadminquery|query ] [orgunit|org|ou ] [matchname ] [domainlist ] [includetypes ] [oneorganizer []] [shownorganizerdrives [false|true|only]] [includefileorganizers []] [delimiter ]

See: https://github.com/GAM-team/GAM/wiki/Shared-Drives#display-shared-drive-organizers

The command defaults match the script defaults:
* `domainlist` - All domains
* `includetypes` - user,group
* `oneorganizer` - False
* `shownoorganizerdrives` - True
* `includefileorganizers` - False

For example, to get a single user organizer from your domain for all Shared Drives including no organizer drives:

gam redirect csv ./TeamDriveOrganizers.csv print shareddriveorganizers domainlist mydomain.com includetypes user oneorganizer shownoorganizerdrives

7.07.17

Added option `oneuserperrow` to `gam print devices` to have each of a
device's users displayed on a separate row with all of the other device fields.

7.07.16

Added `chromeostype`, `diskspaceusage` and `faninfo` to `<CrOSFieldName>` for use in `gam info|print cros`.

Fixed bugs/cleaned output in  `gam info|print cros`.

7.07.15

Added option `shareddrivesoption included|included_if_account_is_not_a_member|not_included` to `gam create vaultexport`.

The previous option `includeshareddrives <Boolean>` is mapped as follows:
* `includeshareddrives false` - `shareddrivesoption included_if_account_is_not_a_member`
* `includeshareddrives true` - `shareddrivesoption included`

7.07.14

Update `gam setup chat` output to include the following that shows the actual Cloud Pub/Sub Topic Name.

You'll use projects//topics/no-topic in Connection settings Cloud Pub/Sub Topic Name

7.07.13

Added option `showitemcountonly` to `gam [<UserTypeEntity>] print|show shareddrives` that causes GAM to display the
number of Shared Drives on stdout; no CSV file is written.

7.07.12

Fixed bug in `gam print|show oushareddrives` that caused a trap.

Improved getting Shared Drive names from IDs when accessing Shared Drives in external workspaces.

7.07.11

Updated `gam calendars <CalendarEntity> update events` and `gam <UserTypeEntity> update events <UserCalendarEntity>`
to handle the following error:

ERROR: 400: badRequest - Bad Request

Updated `gam <UserTypeEntity> move drivefile` to handle the following error:

ERROR: 400: shareOutNotPermitted

7.07.10

Updated `gam calendars <CalendarEntity> update events` and `gam <UserTypeEntity> update events <UserCalendarEntity>`
to handle the following error:

ERROR: 400: eventTypeRestriction - Attendees cannot be added to 'fromGmail' event with this visibility setting.

7.07.09

Updated `gam calendars <CalendarEntity> update events` and `gam <UserTypeEntity> update events <UserCalendarEntity>`
to handle the following error:

gamlib.glgapi.serviceNotAvailable: Authentication backend unavailable.

7.07.08

Fixed bug in `gam <UserTypeEntity> print filelist ... countsonly` that issued an
incorrect warning message like the following when `redirect csv <FileName> multiprocess` was specified.

WARNING: csv_output_row_filter column "^name$" does not match any output columns

7.07.07

Fixed bug in `gam report <ActivityApplictionName> ... countsonly eventrowfilter` that issued an
incorrect warning message like the following when `redirect csv <FileName> multiprocess` was specified.

WARNING: csv_output_row_filter column "^doc_title$" does not match any output columns

7.07.06

Added option `eventrowfilter` to `gam calendars <CalendarEntity> print events ... countsonly`
and `gam <UserTypeEntity> print events <UserCalendarEntity> ... countsonly` that causes
GAM to apply `config csv_output_row_filter` to the event details rather than the event counts.
This will be useful when `<EventSelectProperty>` and `<EventMatchProperty>` do not have the
capabilty to select the events of interest; e.g., you want to filter based on the event `created` property.

Dropped the extraneous `id` column for `gam calendars <CalendarEntity> print events ... countsonly`
and `gam <UserTypeEntity> print events <UserCalendarEntity> ... countsonly`.

7.07.05

Updated `gam <UserTypeEntity> move drivefile` to recognize the API error: `ERROR: 400: shareOutWarning`.

7.07.04

Updated `gam create vaultexport ... rooms <ChatSpaceList>` to strip `spaces/` from the Chat Space IDs.

Updated `gam <UserTypeEntity> copy drivefile` to recognize the API error: `ERROR: 400: shareOutWarning`.

7.07.03

Updated `gam create vaultexport` to allow allow specifying a list of items in a search method
with `shareddrives|rooms|sitesurl select <FileSelector>|<CSVFileSelector>`.

7.07.02

Fixed bug in `redirect csv ... transpose` where a CSV file with multiple rows was not properly transposed.

7.07.01

Fixed bug in `gam print|show chromepolicies` that caused a trap. Made additional
updates to handle changes in the Chrome Policy API.

7.07.00

As of mid-October 2024, Google deprecated the API that retrieved the Global Address List.

The following commands have been eliminated.

gam info gal gam print gal gam show gal


These commands are a work-around for `gam print gal`.

gam config csv_output_row_filter "includeInGlobalAddressList:boolean:true" redirect csv ./UserGAL.csv print users fields name,gal gam config csv_output_row_filter "includeInGlobalAddressList:boolean:true" batch_size 25 redirect csv ./GroupGAL.csv print groups fields name,gal


7.06.14

Updated `create|update adminrole` to allow specifying a collection of privileges
with `privileges select <FileSelector>|<CSVFileSelector>` which makes copying roles much simpler.

Added option `role <RoleItem>` to `gam print|show adminroles` to allow display of information
for a specific role.

7.06.13

Updated `gam print group-members ... recursive` and `gam print cigroup-members ... recursive`
to expand groups representing chat spaces.

7.06.12

Deleted commands to display Analytic UA properties; the API has been deprecated.

gam print|show analyticuaproperties

7.06.11

Improved `gam checkconn`.

Updated `gam print group-members` and `gam print cigroup-members` to recognize members
that are groups representing chat spaces. For now, these groups are not expanded when
`recursive` is specified.

7.06.10

Added the following license SKU.

1010020034 - Google Workspace Frontline Plus

7.06.09

Added `gemini` and `geminiforworkspace` to `<ActivityApplicationName>` for use in
`gam report <ActivityApplicationName>`.

7.06.08

Fixed problem where Yubikeys caused a trap.

7.06.07

Updated private key rotation progress messages in `gam create|use|update project`
and `gam upload sakey`.

Updated `gam use project` to display the following error message when the specifed project
already has a service account.

Re-run the command specify a new service account name with: saname '

7.06.06

Native support for Windows 11 Arm-based devices.

Renamed some MacOS and Linux binary installer files to align on terminology. Everything is "arm64" now, no "aarch64".

7.06.05

Updated code in `gam delete|update chromepolicy` to handle the `policyTargetKey[additionalTargetKeys]`
field in a more general manner for future use.

7.06.04

Fixed bug in `gam report <ActivityApplictionName>` where a report with no activities
was not displaying any output.

7.06.03

Fixed bug in `gam <UserTypeEntity> print|show drivelastmodification` that caused a trap
when an empty drive was specified.

7.06.02

Updated `gam <UserTypeEntity> print|show filecounts ... showlastmodification` to include
file mimetype and path information for the last modified file.

Added simple commands to get information about the last modified file on a drive.
By default, a user's My Drive is processed; optionally, a Shared Drive can be processed.

gam print drivelastmodification [todrive ] [select ] [pathdelimiter ] (addcsvdata ) gam show drivelastmodification [select ] [pathdelimiter ]

7.06.01

Updated `gam <UserTypeEntity> create|update drivefileacl ... expiration <Time>`
to handle additional API errors.

Updated to Python 3.13.3.

7.06.00

Upgraded to OpenSSL 3.5.0.

Fixed bug in `gam print cigroups` where `createTime`, `updateTime` and `statusTime`
were not converted according to `gam.cfg timezone`.

7.05.22

Updated progress messages for  `gam <UserTypeEntity> print filelist|filecounts|filesharecounts|filetree select shareddriveid <SharedDriveID>`
to display the ID of the SharedDrive that is being accessed.

Getting all Drive Files/Folders for user@domain.com on Shared Drive ID: <SharedDriveID Got 33 Drive Files/Folders for user@domain.com on Shared Drive ID: ...

7.05.21

Fixed bug in `gam update chromepolicy` that generated an error like the following
when JSON data was read from a file.

ERROR: JSON: {'error': {'code': 400, 'message': 'Invalid enum value: {prefix}{value} for enum type: chrome.policy.api.v1.devicepolicy.AllowNewUsersEnum', 'status': 'INVALID_ARGUMENT'}}

Fixed bug in `gam create chromepolicyimage` that caused a trap.

7.05.20

Updated code to validate both `<RegularExpression>` and `<ReplacementString>`
in the following command line options; this will expose errors when the command
is being parsed rather than at run-time.

replaceregex replacedescription replacefilename

7.05.19

Added `replaceregex <RegularExpression> <ReplacementString> <Tag> <String>` to the following commands:

gam sendemail subject gam sendemail subject

The `<RegularExpression>` is used as a match pattern against `<String>` to produce `<ReplacementString>`.
Instances of `{Tag}` will be replaced by `<ReplacementString>` in the message subject and body.

Added `replaceregex <RegularExpression> <ReplacementString> <Tag> <UserReplacement>` to the following commands:

gam create user gam update user gam update users gam update users gam draft message gam import message gam insert messageo gam create sendas gam update sendas gam signature gam vacation subject

The `<RegularExpression>` is used as a match pattern against `<UserReplacement>` to produce `<ReplacementString>`.
Instances of `{Tag}` will be replaced by `<ReplacementString>` in the indicated items.

For example, when adding a phone number to a signature, an unformatted number can be formatted:

replaceregex "(\d{3})(\d{3})(\d{4})" "(\1) \2-\3" Phone "9876543210" replaces 9876543210 with (987) 654-3210

replaceregex "(+\d{2})(\d{3})(\d{3})(\d{3})" "\1 \2 \3 \4" Phone "+61987654321" replaces +61421221506 with +61 987 654 321

7.05.18

Updated `gam calendars <CalendarEntity> show events` and `gam <UserTypeEntity> show events`
to display the event description according to `show_convert_cr_nl` in `gam.cfg`;
previously, GAM assumed `show_convert_cr_nl = true`.

show_convert_cr_nl = false description: Line 1 Line 2 Line 3

show_convert_cr_nl = true description: Line 1\nLine 2\nLine 3\n

7.05.17

Updated commands that delete drive ACLs to handle the following error:

ERROR: 403: cannotDeletePermission - The authenticated user does not have the required access to delete the permission.

7.05.16

Added option `transpose [<Boolean>]` to `redirect csv` that causes
GAM to transpose CSV output rows and columns. This will most useful
when a `countsonly` option is used in a `print` or `report` command.

7.05.15

Updated `gam <UserTypeEntity> get drivefile` and `gam <UserTypeEntity> create drivefile`
to allow downloading and uploading of Google Apps Scripts.

$ gam user user1@domain.com get drivefile 1ZY-YkS3E0OKipALra_XzfIh9cvxoILSbb8TRdHBFCpyB_mXI_J8FmjHv format json User: user1@domain.com, Download 1 Drive File User: user1@domain.com, Drive File: Test Project, Downloaded to: /Users/gamteam/GamWork/Test Project.json, Type: Google Doc $ gam user user2@domain.com create drivefile localfile "Test Project.json" mimetype application/vnd.google-apps.script+json drivefilename "Test Project" User: user2@domain.com, Drive File: Test Project(1Ok_svw55VTreZ5CzcViJDLfEzVRi-Un8D9eG6I5pIeVyRl2YsmNiy3C_), Created with content from: Test Project.json

7.05.14

Added the following License SKU:

ProductId SKUId Display Name 101039 1010390002 Assured Controls Plus

7.05.13

Updated license product names to match Google.

7.05.12

Fixed bug in `gam update chromepolicy` where `appid` was misinterpreted for `chrome.devices.kiosk` policies
and an error was generated.

ERROR: Chrome Policy Schema: customers/C123abc456/policySchemas/, Does not exist

7.05.11

Added the following License SKUs:

ProductId SKUId Display Name Google-Apps 1010070001 Google Workspace for Education Fundamentals Google-Apps 1010070004 Google Workspace for Education Gmail Only 101034 1010340007 Google Workspace for Education Fundamentals - Archived User

7.05.10

Updated various chat space commands to handle the following error:

ERROR: 503: serviceNotAvailable - The service is currently unavailable

7.05.09

Fixed bug in `gam calendars <CalendarEntity> print events matchfield attendeesstatus required accepted resource_calendar@resource.calendar.google.com`
that caused a trap.