bugzilla: workaround build issue with Perl 5.30.
It doesn't like this one line of code. Unclear why. Fails with
an undefined reference to utf8::SWASHNEW.

But all it does is remove BiDi control characters, so we can remove it.

Bump PKGREVISION
PR pkg/54624