wireshark: updated to 4.6.3
4.6.3

Bug Fixes

The following vulnerabilities have been fixed:
wnpa-sec-2026-01 BLF file parser crash. Issue 20880.
wnpa-sec-2026-02 IEEE 802.11 dissector crash. Issue 20939.
wnpa-sec-2026-03 SOME/IP-SD dissector crash. Issue 20945.
wnpa-sec-2026-04 HTTP3 dissector infinite loop. Issue 20944.
The following bugs have been fixed:
Wireshark 4.6.0 build fails on Solaris: pcapio.c:441:21: error: request for member '_flag' in something not a structure or union. Issue 20773.
RTP Player streams cannot be stopped. Issue 20879.
Additional ABI/API compatibility fixes. Issue 20881.
Missing data in pinfo→cinfo in HomePlug message CM_ATTEN_CHAR.IND. Issue 20893.
maxmind_db: crash when switching from a profile where it’s disabled to one where it’s enabled. Issue 20903.
Compilation warning or error if CFLAGS defines _FORTIFY_SOURCE to other than 3 without first undefining it. Issue 20904.
IEEE 802.11: Incorrect parsing of QoS and Mesh Control Field when the frame body contains an A-MSDU. Issue 20905.
OSS-Fuzz 473164101: Heap-buffer-overflow in dissect_idn_laser_data. Issue 20936.
Bug in decoding 5G NAS message - Extended CAG information list IE. Issue 20946.