(math/xyconvert) +USE_LANGUAGES+= c++
The problem was:

~/usr/include/g++/bits/c++0x_warning.h:32:2: error: #error
This file requires compiler and library support for the ISO C++ 2011 standard.
This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
  ^~~~~