Update to 6.0.43
Changelog:
# Tomcat 6.0.43 (markt)
## Catalina
* fix	Assert that mapping result object is empty before performing mapping work in Mapper. (kkolinko)

## Coyote
* fix	53952: Add support for TLSv1.1 and TLSv1.2 for APR connector. Based upon a patch by Marcel Šebek. (schultz/jfclere)
* fix	56780: Enable Tomcat to start when using SSL with an IBM JRE in strict SP800-131a mode. (markt/kkolinko)
* fix	57102: Fix bug that meant sslEnabledProtocols setting was not recognised for the HTTPS NIO connector. (markt)
* add	Disable SSLv3 by default for the APR/native HTTPS connector. (markt/schultz)
* fix	Do not increase remaining counter at end of stream in IdentityInputFilter. (kkolinko)
* fix	Disable SSLv3 by default (along with SSLv2 which was already disabled by default) in light of the recently announced POODLE vulnerability (CVE-2014-3566). (markt)
* fix	57116: Do not fallback to default protocol list for HTTPS BIO connector if sslEnabledProtocols has no matches. (markt)
* update	Align calculation of default ciphers and default protocols for JSSE HTTPS connectors with Tomcat 7 which allows for per connector defaults based on the choice of sslProtocol. (markt/kkolinko)

## Web applications
* fix	Configure the Javadoc tool to read sources as ISO-8859-1, suppress timestamp comments and enable charset header. (kkolinko)
* fix	Correct typos in configuration samples on SSL Configuration page of Tomcat documentation. (kkolinko)

## Other
* update	56079: The Apache Tomcat Windows service and the Apache Tomcat Windows service monitor application are now digitally signed. (markt/kkolinko)
* update	56988: Allow to use relative path in base.path setting when building Tomcat. (kkolinko)
fix	Update documentation: the minimum version of Apache Ant required to build Tomcat is 1.8.0. (kkolinko)
* update	56596: Update to Tomcat Native Library version 1.1.32 to pick up the Windows binaries that are based on OpenSSL 1.0.1j and APR 1.5.1. (markt)
* fix	Fix timestamps in Tomcat build to use 24-hour instead of 12-hour format and use UTC timezone. (kkolinko)

# Tomcat 6.0.42 (jfclere)	not released
## Catalina
* fix	56600: In WebdavServlet: Do not waste time generating response for broken PROPFIND request. (kkolinko)
* fix	56648: Reduce scope of synchronization when adding children to a container (e.g. adding a Context to a Host) to prevent blocking requests to other children while the new child starts. (markt)
* fix	56684: Ensure that Tomcat does not shut down if the socket waiting for the shutdown command experiences a SocketTimeoutException. (markt)

## Coyote
fix	Various improvements to ChunkedInputFilter including clean-up, i18n for error messages and adding an error flag to allow subsequent attempts at reading after an error to fail fast. (markt)
fix	56661: Support using AJP request attribute AJP_LOCAL_ADDR to fix getLocalAddr(). (rjung)

## Jasper
* fix	43001: Enable the JspC Ant task to set the JspC option mappedFile. (kkolinko)
* fix	56334: Fix a regression in EL parsing when quoted string follows a whitespace. (markt)
* fix	56560: Fix NoClassDefFoundError when using Jasper Ant task defined by catalina-tasks.xml file. Patch provided by M Gemmell. (kkolinko)
* fix	56561: Avoid NoSuchElementException while handling attributes with empty string value. (violetagg)
* fix	56612: Correctly parse consecutive escaped single quotes when used in an EL expression. (markt)
* code	Use if { ... } else if { ... } rather than multiple if { ... } for alternative branches in the JSP parser. (kkolinko)
* fix	Fix a potential resource leak in JDTCompiler when checking wether a resource is a package. Reported by Coverity Scan. (fschumacher)

## Other
* fix	56606: When creating tomcat-users.xml in the Windows Installer, use the new attribute name for the name of the user. (markt)
* add	56829: Add the ability for users to define their own values for _RUNJAVA and _RUNJDB environment variables. Be more strict with executable filename on Windows (s/java/java.exe/). Based on a patch by Neeme Praks. (markt/kkolinko)