Put back MAKE_JOBS_SAFE=no, despite building fine at various MAKE_JOBS levels I've since observed a couple of failures in bulk builds at MAKE_JOBS=2.  The usual failure mode is
  MCS     [net_4_0] mono-api-info.exe
  error CS0006: Metadata file `../../class/lib/net_2_0/Mono.Cecil.dll' could not be found

or similar (net_4_0 components depending upon unbuilt net_2_0 dependencies).