py-Pillow: update to 4.3.0
4.3.0:
- Fix warning on pointer cast in isblock
- Doc: Added macOS High Sierra tested Pillow version
- Use correct Windows handle type on 64 bit in imagingcms
- 64 Bit Windows fix for block storage
- Fix "expression result unused" warning
- Add 16bit Read/Write and RLE read support to SgiImageFile
- Block & array hybrid storage
- Common seek frame position check
- Doc: Add note about aspect ratio to Image thumbnail script
- Fix ValueError: invalid version number '1.0.0rc1' in scipy release candidate
- Unfreeze requirements.txt
- Test: ResourceWarning tests
- Use n_frames to determine is_animated if possible
- Doc: Corrected parameters in documentation
- Avoid unnecessary Image operations
- Added register_extensions method
- Fix TIFF support for I;16S, I;16BS, and I;32BS rawmodes
- Fixed doc syntax in ImageDraw
- Fixed support for building on Windows/msys2. Added Appveyor CI coverage for python3 on msys2
- Fix ValueError in Exif/Tiff IFD
- Use pathlib2 for Path objects on Python < 3.4
- Export only required properties in unsafe_ptrs
- Alpha composite fixes
- Faster Transpose operations, added 'Transverse' option
- Deprecate ImageOps undocumented functions gaussian_blur, gblur, unsharp_mask, usm and box_blur in favor of ImageFilter implementations
- Dependencies: Updated freetype to 2.8.1
- Bug: Player skipped first image
- Faster filter operations for Kernel, Gaussian, and Unsharp Mask filters
- EPS: Add showpage to force rendering of some EPS images
- DOC: Fix type of palette parameter in Image.quantize.
- DOC: Fix Ico docs to match code
- Added file pointer save to SpiderImagePlugin
- Add targa version 2 footer
- Removed redundant lines
- Travis CI: Use default pypy/pypy3
- Fix for SystemError when rendering an empty string, added in 4.2.0
- Fix for memory leaks in font handling added in 4.2.0
- Tests:  cleanup, more tests. Fixed WMF save handler
- Removed debugging interface for Image.core.grabclipboard
- Doc syntax fix
- Faster packing and unpacking for RGB, LA, and related storage modes
- Use RGBX rawmode for RGB JPEG images where possible
- Remove palettes from non-palette modes in _new
- Delete transparency info when convert'ing RGB/L to RGBA
- Code tweaks to ease type annotations
- Fixed incorrect use of 's#' to byteslike object
- Fix JPEG subsampling labels for subsampling=2
- Region of interest (box) for resampling
- Basic support for Termux (android) in setup.py
- Bug: Fix Image.fromarray for numpy.bool type.
- CI: Add Fedora 24 and 26 to Docker tests
- JPEG: Fix ZeroDivisionError when EXIF contains invalid DPI (0/0).
- Depends: Updated openjpeg to 2.2.0
- Depends: Updated Tk Tcl to 8.6.7
- Depends: Updated libimagequant to 2.10.2
- Test: Added test for ImImagePlugin tell()
- Test: Additional tests for SGIImagePlugin
- New Image.getchannel method
- Remove unused im.copy2 and core.copy methods
- Fast Image.merge()
- Fast Image.split()
- Fast image allocation
- Storage cleanup
- FLI: Use frame count from FLI header
- Test: Test animated FLI file
- Bug: Fixed uninitialized memory in bc5 decoding
- Moved SgiImagePlugin save error to before the start of write operations
- Move createfontdatachunk.py so isn't installed globally
- Bug: Fix unexpected keyword argument 'align'
- Add newlines to error message for clarity
- Docs: Updated redirected URL
- Bug: Fix JPEG DPI when EXIF is invalid
- Bug: Fix for font getsize on empty string
- Docs: Improved ImageDraw documentation
- Docs: Corrected alpha_composite args documentation
- Docs: added the description of the filename attribute to images.rst
- Dependencies: Updated libimagequant to 2.10.1
- PDF: Renamed parameter to not shadow built-in dict