textproc/p5-Encode-Detect: fix 'array subscript has type char' errors
In file included from src/JpCntx.cpp:39:0:
src/JpCntx.h: In member function 'void JapaneseContextAnalysis::HandleOneChar(const char*, PRUint32)':
src/JpCntx.h:72:55: error: array subscript has type 'char' [-Werror=char-subscripts]
       mRelSample[jp2CharContext[mLastCharOrder][order]]++;
                                                       ^
src/JpCntx.cpp: In member function 'void JapaneseContextAnalysis::HandleData(const char*, PRUint32)':
src/JpCntx.cpp:164:57: error: array subscript has type 'char' [-Werror=char-subscripts]
         mRelSample[jp2CharContext[mLastCharOrder][order]]++;
                                                         ^

The mentioned char arrays only contain small nonnegative numbers,
therefore their exact data type doesn't matter. It is now unsigned char.