www/rails70: update to 7.0.7
Rails 7.0.7 (20223-08-10)

Active Support

* Fix Cache::NullStore with local caching for repeated reads.  (fatkodima)

* Fix to_s with no arguments not respecting custom :default formats
  (Hartley McGuire)

* Fix ActiveSupport::Inflector.humanize(nil) raising NoMethodError:
  undefined method `end_with?' for nil:NilClass.  (James Robinson)

* Fix Enumerable#sum for Enumerator#lazy.  (fatkodima, Matthew Draper,
  Jonathan Hefner)

* Improve error message when EventedFileUpdateChecker is used without a
  compatible version of the Listen gem.  (Hartley McGuire)

Active Model

* Error.full_message now strips ":base" from the message.  (zzak)

* Add a load hook for ActiveModel::Model (named active_model) to match the
  load hook for ActiveRecord::Base and allow for overriding aspects of the
  ActiveModel::Model class.

Active Record

* Restores functionality to the missing method when using enums and fixes.
  (paulreece)

* Fix StatementCache::Substitute with serialized type.  (ywenc)

* Fix :db_runtime on notification payload when application have multiple
  databases.  (Eileen M. Uchitelle)

* Correctly dump check constraints for MySQL 8.0.16+.  (Steve Hill)

* Fix ActiveRecord::QueryMethods#in_order_of to include nils, to match the
  behavior of Enumerable#in_order_of.

  For example, Post.in_order_of(:title, [nil, "foo"]) will now include posts
  with nil titles, the same as Post.all.to_a.in_order_of(:title, [nil,
  "foo"]).  (fatkodima)

* Revert "Fix autosave associations with validations added on :base of the
  associated objects."

  This change intended to remove the :base attribute from the message, but
  broke many assumptions which key these errors were stored.  (zzak)

* Fix #previously_new_record? to return true for destroyed records.

  Before, if a record was created and then destroyed,
  #previously_new_record? would return true.
  Now, any UPDATE or DELETE to a record is considered a change, and will
  result in #previously_new_record? returning false.  (Adrianna Chang)

* Revert breaking changes to has_one relationship deleting the old record
  before the new one is validated.  (zzak)

* Fix support for Active Record instances being uses in queries.

  As of 7.0.5, query arguments were deep duped to avoid mutations impacting
  the query cache, but this had the adverse effect to clearing the primary
  key when the query argument contained an ActiveRecord::Base instance.

  This broke the noticed gem.  (Jean Boussier)

Action View

* Fix render collection: @records, cache: true to cache fragments as bare
  strings.
  Previously it would incorrectly cache them as Action View buffers.  (Jean
  Boussier)

* Don't double-encode nested field_id and field_name index values.
  Pass index: @options as a default keyword argument to field_id and
  field_name view helper methods.  (Sean Doyle)

Railties

* Update default scaffold templates to set 303 (See Other) as status code on
  redirect for the update action for XHR requests other than GET or POST to
  avoid issues (e.g browsers trying to follow the redirect using the
  original request method resulting in double PATCH/PUT).  (Guillermo Iguaran)