Update to HPLIP 3.15.6 (from 3.14.6)
Note: python3 support (listed below) has not been tested.


HPLIP 3.15.6 - This release has the following changes:
Added Support for the Following New Printers:

- HP DeskJet 2130 All-in-One Printer series
- HP DeskJet 2132 All-in-One Printer
- HP Deskjet 2546B All-in-One Printer
- HP Deskjet 2546P All-in-One Printer
- HP Deskjet 2546R All-in-One Printer
- HP DeskJet 3630 All-in-One Printer series
- HP DeskJet 3632 All-in-One
- HP Officejet 5744 e-All-in-One

Added support for the following new Distro's:

- Fedora 22

Issues fixed:

- Unable to capture 'error_log' while running 'hp-logcapture' on
  Fedora21.
- Error message is displayed while running 'hp-diagnose_queues' in
  terminal

Launchpad fixes:

1433557 - udev rules wrongly match on monitor hub, wrong invocation of
	  systemd unit, changes config files in udev rules
1438456 - hp-setup creates spurious cupsd process

HPLIP 3.15.4 - This release has the following changes:
Significant Changes:

- HPLIP Plugin support for ARMv6,ARMv7 and aarch64 architectures

Added Support for the Following New Printers:

-HP Color LaserJet Pro M252dw
-HP Color LaserJet Pro M252n
-HP Color LaserJet Pro MFP M277n
-HP Color LaserJet Pro MFP M277dw
-HP Color LaserJet Enterprise M553n
-HP Color LaserJet Enterprise M553dn
-HP Color LaserJet Enterprise M553x
-HP Color LaserJet Enterprise M553dh
-HP Color LaserJet Enterprise M552dn
-HP LaserJet Enterprise M604n
-HP LaserJet Enterprise M604dn
-HP LaserJet Enterprise M605dn
-HP LaserJet Enterprise M605n
-HP LaserJet Enterprise M605x
-HP LaserJet Enterprise M606x
-HP LaserJet Enterprise M606dn

Added support for the following new Distro's:

- Debian 8.0 (RC)
- LinuxMint 17.1
- Ubuntu 15.04 (Beta)

Issues fixed:

- "Auto agree with license" option is set by default while resolving the
  dependencies with auto installation of HPLIP

Launchpad fixes:

1328074 - Installation fails when Downloads directory does not exist
1424539 - Updated driver plugin information in website
1152219 - hplip driver plugin support for ARM architecture
1328601 - FC20 latest version of HPLIP the "ready light" keeps flashing
	  after print job is done
1388180 - hp-sendfax complains about Pre-2.0 version of Reportlab
1422004 - pkservice.py crashed with AttributeError in __init__():
          'module' object has no attribute 'MainLoop'

HPLIP 3.15.2 - This release has the following changes:
Significant Changes:

- Python3 support for HPLIP

Added support for the following new Distro's:

- Debian 7.7, 7.8
- OpenSuse 13.2
- Fedora 21

Launchpad fixes:

1388126 - Doesn't build against libjpeg-turbo 1.3.90
1395676 - hpcups crashes if DEVICE_URI not set in environment
1388007 - Incorrect call to hpmudext.device_open
1187055 - plugin download fails if python links to python3
802999  - Incorrect IEEE 1284 Device IDs for many models

HPLIP 3.14.10 - This release has the following changes:

Added Support for the Following New Printers:

- HP Deskjet 2541 All-in-One Printer
- HP Envy 4501 e-All-in-One
- HP Envy 4503 e-All-in-One
- HP Envy 4505 e-All-in-One
- HP Envy 4507 e-All-in-One
- HP Envy 4508 e-All-in-One
- HP ENVY 5534 e-All-in-One Printer
- HP Envy 5640 e-All-in-One
- HP Envy 5642 e-All-in-One
- HP Envy 5643 e-All-in-One
- HP Envy 5644 e-All-in-One
- HP Envy 5660 e-All-in-One
- HP Envy 5665 e-All-in-One
- HP Envy 7640 e-All-in-One
- HP Envy 7645 e-All-in-One
- HP LaserJet Pro MFP M125r
- HP LaserJet Pro MFP M125ra
- HP LaserJet Pro M201n Printer
- HP LaserJet Pro M201dw Printer
- HP LaserJet Pro M202n Printer
- HP LaserJet Pro M202dw Printer
- HP LaserJet Pro MFP M225rdn
- HP LaserJet Pro MFP M225dw
- HP LaserJet Pro MFP M225dn
- HP LaserJet Pro MFP M226dw
- HP LaserJet Pro MFP M226dn
- HP LaserJet Enterprise MFP M630dn
- HP LaserJet Enterprise MFP M630f
- HP LaserJet Enterprise MFP M630h
- HP LaserJet Enterprise Flow MFP M630z
- HP Officejet 5740 e-All-in-One
- HP Officejet 5742 e-All-in-One
- HP Officejet 5745 e-All-in-One
- HP OfficeJet 8040 e-All-in-One
- HP OfficeJet 6810 e-All-in-One  Printer Series
- HP OfficeJet 6812 e-All-in-One  Printer
- HP OfficeJet 6815 e-All-in-One  Printer
- HP Officejet 7612 Wide Format e-All-in-One Printer
- HP OfficeJet Pro 6230 ePrinter
- HP OfficeJet Pro 6830 e-All-in-one
- HP OfficeJet Pro 6835 e-All-in-one
- HP OfficeJet Pro 8616 e-All-in-One Printer


Added support for the following new Distro's:

- Debian 6.0.10
- Debian 7.6
- Ubuntu 14.10 Beta
- RHEL 7.0

Issues fixed:

- Traceback error occurs while configuring the device using
  'hp-setup <wrong input>'.
- Traceback error occurs while sending fax when SELinux is enabled.

Launchpad fixes:

250073  - Installation of 3.14.6 complains about failed install of
	  non-existing package cupsys-bsd on Debian 7.
1255033 - Updated comment in 56-hpmud.rules file