Remove slash from end of DEPENDS.
This caused my bulk build to fail (before building) when it was
building list of dependencies, because multimedia/mmg/Makefile
included ../../multimedia/mkvtoolnix/Makefile.dist and also
depended on ../../multimedia/mkvtoolnix/. And multimedia/mkvtoolnix/Makefile
also included ../../multimedia/mkvtoolnix/Makefile.dist.

The bulk build error was like:

---->  Depending in /home/jreed/pkgsrc/multimedia/mmg (pass #1)
---->  Depending in ../../multimedia/mkvtoolnix/ (pass #2)
...
---->  Depending in ../../multimedia/mkvtoolnix/ (pass #24)
ERROR:  You have reached 25 times through the dependency tree
        and _still_ not finished.  This is probably due to a broken
        set of dependencies.  You may wish to examine the partial
        database left in /home/jreed/pkgsrc/.bulk_db.foo

Removing the trailing slash from the DEPENDS fixed this problem for me.