Pullup ticket 874 - requested by Takahiro Kambe portability fix for squid
Revisions pulled up:
- pkgsrc/www/squid/Makefile		1.164
- pkgsrc/www/squid/distinfo		1.108
- pkgsrc/www/squid/patches/patch-bd	removed

   Module Name:		pkgsrc
   Committed By:	taca
   Date:		Mon Oct 31 09:53:41 UTC 2005

   Modified Files:
   	pkgsrc/www/squid: Makefile distinfo
   Removed Files:
   	pkgsrc/www/squid/patches: patch-bd

   Log Message:
   Use official patch instead of temporary one.

   2005-10-26 20:31 (Minor) fails to compile with undefined reference to setenv

   Bump PKGREVISION.