py-urwid: updated to 2.1.0
Urwid 2.1.0
* Add support for Python 3.7 and 3.8, drop support for Python 3.3
* Add 24-bit (true color) support.
* Add TrioEventLoop
* Add support for input encoding in Terminal widget
* Add ability to specify LineBox title attribute
* Add custom checkbox symbol
* Add installation instruction to README
* Remove PollingListWalker class
* Change SelectableIcon default cursor_position to 0.
* Extended numerical editing: integers and floats
* Re-raise coroutine exceptions in AsyncioEventLoop properly
* Fixed locale issue
* Gate SIGWINCH behind GLib 2.54+
* Remove method Text._calc_line_translation()
* Fix colon in HalfBlock5x4Font
* Don't use deprecated inspect.getargspec() with python3
* Fix issue "Non-integer division in bargraph when using set_bar_width(1)"
* Fix misleading indentation in Screen._stop()
* Fix crash on click-Esc & Esc-click
* Use 'TimerHandle.cancelled()' if available
* Break rather than raising exception on shard calculation bug.
* Increase _idle_emulation_delay.
* Fix EOF detection for the Terminal widget on Python 3
* Fix the asyncio example, and make the raw Screen work without real files
* Unbreak python ./examples/treesample HOME END keys.
* Urwid.util: Fix bug in rle_append_beginning_modify
* Fix AttributeError on mouse click
* Fix ProgressBar smoothing on Python 3.x
* Fix asyncio event loop test on py3.4
* Handle case where MainLoop._topmost_widget does not implement mouse_event
* Implement `ellipsis` wrapping mode for StandardTextLayout
* Fix .pack call in Columns.column_widths
* Use ._selectable member for Edit widget
* Fix use of ignore_focus, for widgets inheriting from Text
* Remove some special handling for TreeListBox
* Make Columns and Pile selectable when any child widget is
* Implement get_cursor_coords for Frame widget
* Fix Frame mouse_event when footer is trimmed
* Fix Python 3.8 SyntaxWarning: 'str' object is not callable
* README: Use SVG build status badge