Update to 2.16.2037.102
Changelog:
r510 2015-01-25 2.16.2037.102 - r494 2015-01-24 2.16.2021.102
Summary of changes between 2.16.2021.102 (r494) and 2.16.2037.102 (r510).

    DEPS changes:
        none
    Build related changes:
        libc++ is used by default to build Android target binaries.
        Clang 3.5 is now required to build Mozc for Android, NaCl, and Linux. See  Issue 276  for the motivation behind this change.
        Visual C++ 2013 is required to build Mozc for Windows.
    Major changes:
        Mozc for Windows now requires Windows Vista SP2 and later. Mozc 2.16.2034.102 (r507) is the last version that can run on Windows XP and Windows 2003 Server. See  Issue 277 .
    Known issues:
        Voiced sound marks on the key pad is not placed at correct position in Android (Issue 263)
        Compilation errors in Android arm64 and mips64 build (Issue 273)
    Fixed issues:
        FIX: Inconsistency between suggestion candidates and conversion candidates ( Issue 274 )
        FIX: Learning algorithm is sometimes too aggressive when punctuation is committed ( Issue 275 )
        FIX: Require Clang to build Linux host binaries ( Issue 276 )
        FIX: Discontinue the support of Windows XP / 2003 Server ( Issue 277 )
    Commit summary:
        r510: Remove a workaround code for Visual C++ 2010 (KB813540)
        r509: Require Visual C++ 2013 to build Mozc for Windows
        r508: Require Windows Vista SP2 or later
        r507: Remove build_tools command from build_mozc.py
        r506: Require Clang to build Linux host binaries
        r505: Switch from stlport to libcxx in Android build
        r504: Remove mozc::DetachedThread as it is no longer used
        r503: Fix build failur of unit tests when libcxx is used on Android
        r502: Fix test failure in release build with Visual C++ 2013
        r501: Make the conditions to learn candidates with a punctuation mark more strict
        r500: Apply the same hack as conversion to prediction for transition cost from history node
        r499: Remove an unused member field
        r498: As-is import of NaCl Mozc for Chromium OS
        r497: Remove platform-dependent mozc::Encryptor part 3
        r496: Fix style violations in header include guards part 4
        r495: Remove unused variables
        r494: Fix a typo in reading strings of Unicode Emoji data

r486 2015-01-18 2.16.2020.102 - r474 2015-01-01 2.16.2008.102
Summary of changes between 2.16.2008.102 (r474) and 2.16.2020.102 (r486).

    DEPS changes:
        protobuf: bba83652e1be610bdb7ee1566ad18346d98b843c -> 172019c40bf548908ab09bfd276074c929d48415 (downgrading)
    Build related changes:
        Ubuntu 14.04 is used as the reference build/test environment for Android, NaCl, and Linux. Hereafter we will not make sure that Mozc can be built on Ubuntu 12.04.
    Known issues:
        Voiced sound marks on the key pad is not placed at correct position in Android (Issue 263)
        Compilation errors in Android arm64 and mips64 build (Issue 273)
    Fixed issues:
        FIX: All resources are not released in Service.onDestory ( Issue 265 )
        FIX: Many emojis are suggested from space ( Issue 266 )
        FIX: Noisy candidate "itsumo" due to language aware conversion ( Issue 267 )
        FIX: BuildInDocker fails when building for Android ( Issue 269 )
        FIX: Runtime CHECK failure on Windows: protobuf/src/google/protobuf/descriptor.cc:1018 ( Issue 271 )
        FIX: AssertionError in gen_zip_code_seed.py ( Issue 272 )
    Commit summary:
        r486: Unsupport Ubuntu 12.04 as a build environment
        r485: Update copyright year in source header comments
        r484: Update copyright year in the about dialog to 2015
        r483: Update special rules for KEN_ALL.CSV
        r482: Revert r438 "Update Protocol Buffers to 2.6.1" and r444 "Suppress compiler warnings for Protocol Buffers 2.6.1"
        r481: Revert r477 "Revert r247 "Explicity invoke bash for make-standalone-toolchain.sh""
        r480: Call CalculatorInterface::CalculateString even for x86 Android testing
        r479: Suppress LangAwareRewriter to suggest the raw text if the query is in the dictionary as a key
        r478: Handle emojis that have multiple readings correctly
        r477: Revert r247 "Explicity invoke bash for make-standalone-toolchain.sh"
        r476: Several coding style fixes
        r475: Improve classic skins for Android
        r474: Fix resource leak on onDestroy