gam: update to 7.19.02
Changes since 7.10.07:

7.19.02

Update gam info user <UserItem> to eliminate 5 second delay when getting license info.

7.19.01

Updated gam <UserTypeEntity> print|show signature to handle the following error that occurs when an alias is specified:
ERROR: 404: notFound - Requested entity was not found.

7.19.00

Eliminated drive_v3_beta and meet_v2_beta from gam.cfg as the API betas are no longer used.

Updated Meet API scopes so that GAM can read metadata about additional Meet spaces.

[*] 34)  Meet API - Manage/Display Meeting Spaces
[*] 35)  Meet API - Read Meeting Spaces metadata

7.18.07

Updated gam <UserTypeEntity> print drivelastmodification to put addcsvdata columns after User,id,name rather than after the last column.

7.18.06

Updated gam <UserTypeEntity> delete|modify messages to improve the handling of the following error:
quotaExceeded - User-rate limit exceeded

7.18.05

Added support for Inbound SSO OIDC profiles.

Currently, if you enter gam select <SectionName> and nothing else on the command line, GAM performs no action. Now, it will be treated as if you entered: gam select <SectionName> save

Updated to Python 3.13.7.

7.18.04

Added commands to display/manage Alert Center Pub/Sub notifications.

    See: https://github.com/GAM-team/GAM/wiki/Alert-Center#configuring-settings

7.18.03

Updated gam oauth create to give a warning if the number of selected scopes will probably cause Google to generate a "Something went wrong" error.

7.18.02

Upgraded to OpenSSL 3.5.2.

7.18.01

Added option nosystemroles to gam print|show adminroles that causes GAM to only display non-system roles.

Added option formatjson to gam info|print|show adminroles; this will be most useful when the privileges option is used.

Updated gam create|update adminrole to allow specification of privileges with JSON data: privileges <JSONData>. These two updates make it easier to copy admin roles.

Updated gam create|update adminrole to allow output of the created/updated role data in CSV format; by default, GAM displays <RoleName>(<RoleID>) created|updated.

csv [todrive <ToDriveAttribute>*] [formatjson [quotechar <Character>]] (addcsvdata <FieldName> <String>)*

7.18.00

Added commands to display Business Profile Accounts. These are special purpose commands and will not generally be used.

gam show businessprofileaccounts
gam print businessprofileaccounts [todrive <ToDriveAttribute>*]

7.17.03

Fixed bug in gam <UserItem> print|show chatspaces asadmin fields <ChatSpaceFieldNameList> that caused a trap when displayname was not in <ChatSpaceFieldNameList>.

7.17.02

Updated gam <UserTypeEntity> print|show webmastersites to handle the following error that occurs if you haven't updated your project to include the Google Search Console API:
ERROR: 403: permissionDenied - Google Search Console API has not been used in project 111055363999 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/searchconsole.googleapis.com/overview?project=111055363999 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

7.17.01

Fixed bug in gam <UserTypeEntity> show webmastersites that caused a trap.

7.17.00

Added commands to discover Sites and WebResources that managed users (previously unmanaged) may have access to for better governance and visibility. These are special purpose commands and will not generally be used.

gam <UserTypeEntity> show webresources
gam <UserTypeEntity> print webresources [todrive <ToDriveAttribute>*]
gam <UserTypeEntity> show webmastersites
gam <UserTypeEntity> print webmastersites [todrive <ToDriveAttribute>*]

7.16.01

The Drive API now supports setting download restrictions on individual files.

Added downloadrestictions and <DriveDownloadRestrictionsSubfieldName> to <DriveFieldName>.

<DriveDownloadRestrictionsSubfieldName> ::=
  downloadrestrictions.itemdownloadrestriction|
  downloadrestrictions.effectivedownloadrestrictionwithcontext

Added itemdownloadrestriction (restrictedforreaders [<Boolean>]) (restrictedforwriters [<Boolean>]) to <DriveFileAttribute>.

From the Drive API documentation:

itemDownloadRestriction - The download restriction of the file applied directly by the owner or organizer. This does not take into account shared drive settings or DLP rules.
effectiveDownloadRestrictionWithContext - Output only. The effective download restriction applied to this file. This considers all restriction settings and DLP rules.
restrictedForReaders - Whether download and copy is restricted for readers.
restrictedForWriters - Whether download and copy is restricted for writers. If true, download is also restricted for readers.

7.16.00

Removed drive_v3_native_names from gam.cfg; GAM now only uses Drive API v3 fields names on output. If you had drive_v3_native_names = False in gam.cfg or are updating from Legacy GAM:

    See: https://github.com/GAM-team/GAM/wiki/Drive-REST-API-v3

7.15.01

Added downloadrestrictions.restrictedforreaders and downloadrestrictions.restrictedforwriters to <SharedDriveRestrictionsSubfieldName>; previously, only the abbreviations downloadrestrictedforreaders and downloadrestrictedforwriters were supported (they are still supported).

Updated gam <UserTypeEntity> copy drivefile to handle unexpected data returned by Google that caused a trap.

7.15.00

Updated gam print shareddriveorganizers to make shownoorganizerdrives default to True as documented; it was defaulting to False.

Cleaned up code for processing Python dictionary structures; this should have no noticable effect.

7.14.04

Fixed bug in gam print|show cigroups cimember <UserItem> that generated the following error:
ERROR: Cloud Identity Group: groups/-, Print Failed: Error(4013): Insufficient permissions to retrieve memberships.

Updated gam <UserTypeEntity> update user suspended off and gam <UserTypeEntity> unsuspend users to handle the following error that occurs when trying to unsuspend a user that has been suspended for abuse:
ERROR: 412: adminCannotUnsuspend - Cannot restore a user suspended for abuse.

    See: https://support.google.com/a/answer/1110339

7.14.03

Fixed bug in gam print cigroup-members includederivedmembership that caused a trap.

7.14.02

Fixed bug in gam print|show cigroups|cigroups-members cimember <UserItem> that generated the following error:

Cloud Identity Group Print Failed: Request contains an invalid argument.

7.14.01

Don't install yubikey library via pip by default. To install with yubikey support use pip install gam7[yubikey]

7.14.00

Added commands to display Google Tag Manager accounts, containers, workspaces, tags and user permissions.

    See: https://github.com/GAM-team/GAM/wiki/Users-Tag-Manager

7.13.03

Added option csv [todrive <ToDriveAttribute>*] [formatjson [quotechar <Character>]]] to gam create chromeprofilecommand so that command details are displayed in CSV format.

Added option commands <ChromeProfileCommandNameList>|<FileSelector>|<CSVFileSelector> to <ChromeProfileNameEntity> so that gam print|show chromeprofilecommands can directly display the commands generated by gam create chromeprofilecommand with the csv option.

7.13.02

Fixed bug in gam create chromeprofilecommand where select|filter were not recognized.

Updated gam create datatransfer <OldOwnerID> datastudio <NewOwnerID> that generated the following error due to an unhandled API change:
ERROR: Invalid choice (google data studio): Expected <calendar|looker studio|drive and docs>

7.13.01

Enhanced gam create|print|show chromeprofilecommand to allow specification of multiple Chrome browser profiles rather than just one.

<ChromeProfilePermanentID> ::= <String>
<ChromeProfileName> ::= customers/<CustomerID>/profiles/<ChromeProfilePermanentID> | <ChromeProfilePermanentID>
<ChromeProfileNameList> ::= "<ChromeProfileName>(,<ChromeProfileName>)*"
<ChromeProfileNameEntity> ::=
<ChromeProfileNameEntity> ::=
        <ChromeProfileNameList> |
        (select <FileSelector>|<CSVFileSelector>) |
        (filter <String> (filtertime<String> <Time>)* [orderby <ChromeProfileOrderByFieldName> [ascending|descending]])

gam create|print_show chromeprofilecommand <ChromeProfileNameEntity>

7.13.00

Added commands that send remote commands to Chrome browser profiles and display the results; at the moment, these commands can clear the browser cache and cookies.

    See: https://github.com/GAM-team/GAM/wiki/Chrome-Profile-Management#create-a-chrome-profile-command

7.12.02

Updated gam print users to handle the following error:
ERROR: 503: serviceNotAvailable - The service is currently unavailable

7.12.01

Added support for plan free in gam create resoldsubscription.

    The free plan is exclusive to the Cloud Identity SKU and does not incur any billing.

7.12.00

Started updated handling of missing scopes messages in client access commands; this is a work in progress.

Updated gam info|show shareddrive to handle changes in the Drive API that caused traps.

Added downloadrestrictedforreaders and downloadrestrictedforwriters to <SharedDriveRestrictionsSubfieldName> to support new Shared Drive restrictions.

Updated gam course <CourseID> create|update announcement to accept input from a literal string, a file or a Google Doc.

<CourseAnnouncementContent> ::=
        ((text <String>)|
         (textfile <FileName> [charset <Charset>])|
         (gdoc <UserGoogleDoc>)|
         (gcsdoc <StorageBucketObjectName>))

Added command gam check suspended <UserItem> that checks the suspension status of a user and sets the return code to 0 if the user is not suspended or 26 if it is.

$ gam check suspended testok@domain.com
User: testok@domain.com, Account Suspended: False
$ echo $?
0

$ gam check suspended testsusp@domain.com
User: testsusp@domain.com, Account Suspended: True, Suspension Reason: ADMIN
$ echo $?
26

Updated gam <UserTypeEntity> sendemail to verify that one of recipient|to|from immediately follows sendemail.

7.11.00

Added commands to manage classroom/course announcements.

    See: https://github.com/GAM-team/GAM/wiki/Classroom-Courses#manage-course-announcements

Upgraded to OpenSSL 3.5.1.

7.10.10

Added choices text and hyperlink to option showwebviewlink in gam [<UserTypeEntity>] print|show shareddrives.

    showwebviewlink text - Displays https://drive.google.com/drive/folders/<SharedDriveID>
    showwebviewlink hyperlink - Displays =HYPERLINK("https://drive.google.com/drive/folders/<SharedDriveID>", "<SharedDriveName>")

7.10.09

Added option showwebviewlink to gam [<UserTypeEntity>] print|show shareddrives that displays the web view link for the Shared Drive: https://drive.google.com/drive/folders/<SharedDriveID>.

7.10.08
Fixed bug in commands that modify messages where the labelids <LabelIdList> option could not be used unless one of these options was also specified: query, matchlabel, ids; it can be now be used by itself.