Updated p5-Params-Validate to 0.72.
changes since 0.59:

0.72 Dec 3, 2003

- If a normalize_keys callback returns the same normalized key for two
different inputs, Params::Validate will die.

- The pure Perl implementation had a bug where if the same hash
reference was used for the spec in multiple calls to validate(), then
any call made after a parameter failed a validation check could
exhibit strange behaviors (like parameters passing that shouldn't,
etc.).  This was due to the fact that the Perl implementation uses
each() internally, and was leaving the hash's iterator partially
iterated.  Reported via an apparent problem with DateTime.pm by Jost
Krieger.


0.71 Dec 2, 2003

- Suppressed some annoying "subroutine redefined" warnings if the pure
Perl version ended up being loaded after attempting to load the XS
version.


0.70 Nov 23, 2003

- Any validation call that used a callback leaked memory when using
the XS version.  This was introduced in 0.67, when callbacks started
receiving a reference to the parameters as a second argument.
Reported by Eugene van der Pijll.


0.69 Nov 3, 2003

- The key normalization feature introduced in 0.66 leaked one SV*
every time a parameter _hash_ was run through the XS version of
validate() or validate_with().  This happened if one of
normalize_keys, allow_extra, or ignore_case was set, or if
validate_with() was used.  Upgrading is strongly recommended!
Reported by Ruslan.


0.68 Oct 21, 2003

- Added spiffy new parameter dependency feature.  Implemented by
Daisuke Maki.


0.67 Oct 10, 2003

- The test count for 06-option.t was off.  Reported by Christian
Schaffner.

- Validation callbacks now receive a reference to the (normalized)
parameter hash/array as their second argument.

- Shut up an "unitialized value in subroutine entry" warning caused by
calling validate_pos() with an undef value in the parameter array.
This was introduced in 0.66.


0.66 Oct 08, 2003

- Skip a few more tests under Perl 5.6.0.  Patch from Christian
Schaffner.

- Error messages now include the stringified value of the variable
that was invalid.  Implemented by Daisuke Maki.

- Added a new parameter normalization callback feature, the
"normalize_keys" option.  Implemented by Daisuke Maki.

** The "strip_leading" and "ignore_case" options are now deprecated.
Use the new "normalize" feature instead.


0.65 Aug 07, 2003

- It is now possible to turn validation on and off at runtime.  To
make this easier, it can be set via the PERL_NO_VALIDATION environment
variable, or the $Params::Validate::NO_VALIDATION global variable.  Go
ahead, shoot yourself in the foot with it!


0.64 Jul 14, 2003

- Fix an XS compilation error under 5.6.1:

 Validate.xs: In function `validate_isa':
 Validate.xs:381: `perl_on_error' undeclared (first use in this function)


0.63 Jul 14, 2003

- The XS version of validate_with failed if the params key contained
an array reference containing a single hash reference.  Since this
works with the pure Perl version, it should work with the XS version.
Reported by Diab Jerius.  Bug #2791 on rt.cpan.org.


0.62 Jun 25, 2003

- Remove a warn() statement left in from debugging.  Reported by Shane
McCarron.


0.61 Jun 23, 2003

- The last release had some debugging code left in which tried to load
Devel::StackTrace.  Reported by Iain Truskett.


0.60 Jun 21, 2003

- Fixed a weird segfault that could occur with Perl 5.6.1 when a
user-defined on_fail callback died with an object as its argument.
This only happened with the XS version of the code.  Reported by Ken
Williams.

The end result is that the version of the XS code that is used with
Perl 5.6.0 and 5.6.1 is slightly slower than that used with 5.00503 or
5.8.0, as it requires an additional Perl-level wrapper.

- Use XSLoader in preference to Dynaloader with Perl 5.6.0+.