gcc15: needs C++14
otherwise you'll get:

../../gcc-15.1.0/gcc/gimple.cc:78:1: error: body of 'constexpr'
function 'constexpr size_t get_tail_padding_adjustment() [with G =
gimple; size_t = long unsigned int]' not a return-statement

Let's see if we need to force c++14