Update sun-j*14 to Sun JDK/JRE version 1.4.2_07.
Bugs fixed according to http://java.sun.com/j2se/1.4.2/ReleaseNotes.html:
1.4.2_04 Server JVM crashes on Linux
ClassLoaders do not get released by GC, causing OutOfMemory in Perm Space
PE with no stack Trace: Enable -XX:-OmitStackTraceInFastThrow for 1.4.2
1.4.2 fastdebug assert on linkResolver.cpp, 49
Unexpected Full GC occurs at 54% of old generation capacity
CMS: precleaning causes crash if perm gen collection enabled
SIGSEGV in ContiguousSpace::prepare_for_compaction(CompactPoint*)
async exception can be delivered on entry from native to vm
indirecting typecodes is wrong
(cs) Charset.isSupported is slow when invoked for different charsets
java.lang.IllegalStateException: recursive invocation using LANG=hu_HU.ISO8859-2
NPE @ sun.awt.font.AdvanceCache.get(AdvanceCache.java:135)
Exponential performance regression in AWT components (multiple monitors)
J2SE 142_06: Regression in java.beans.Introspector (property re-ordering)
Error msg on exception is not displayed correctly in Japanese on XP
ServerSocket(Proxy) and Socket(Proxy) do not work with sun one proxy server
InetAddress.getAllByName does not obey setting of java.net.preferIPv6Addresses
(fs) MappedByteBuffer.force() throws IOException / ENOSPC
(se) select not immune to EINTR (linux)
Need JKS KeyStore with case sensitive alias names
Accelerator keys don't work when JPopupMenu is outside its parent
1.4.2 REGRESSION: JComboBox has problem in JTable in Windows L&F
JFileChooser in Motif L&F does not comply with Section 508
JDI can't connect to the app server a second time
Vmark hang after 66 hours with 1.5.0-beta-b19 C2 on itanium2 with RH AS
stack size assertion failure in hotspot\src\os\win32\vm\os_win32.cpp:2410
NullPointerException when trying to pass byte[] between JVM and ActiveX
JVM Leaks large amount of memory when running applets
Java Plug-In no longer supports 'javascript:' URLs after MS Hotfix 867801
LiveConnect method eval() runs in incorrect context when using frames (IE only)
Occasional ConcurrentModificationException during applet download
Javascript in Applet hangs Netscape Browser
Kerberos library should only select keys of types that it supports
Problem with Kerberos Obfuscated classes