libxkbfile: update to 1.1.3.
This release adds support for building with meson as well as autoconf.
Please test building with meson and report any issues you hit to our
gitlab issue tracker at:
https://gitlab.freedesktop.org/xorg/lib/libxkbfile/-/issues
as we plan on removing the autoconf build support in a future release.

Alan Coopersmith (13):
      configure: Use LT_INIT from libtool 2 instead of deprecated AC_PROG_LIBTOOL
      Set close-on-exec when opening files
      _XkbMakeAtom: remove check for impossible case
      _XkbInitAtoms: check for malloc() failure
      XkbChangeAtomDisplay: stop leaking atom name
      XkbCFReportError: avoid -Wformat-nonliteral warning
      XkbWriteCFile: stop leaking header file ifdef name
      DefaultParser: avoid -Wimplicit-fallthrough warnings
      xkbtext.c: Add tbGetBufferString helper function
      XkbIndentText: Fix -Wsign-compare warning
      Fix -Wsign-compare warnings in xkbtext.c & xkmread.c
      Add a meson build system
      libxkbfile 1.1.3