py-websocket-client: updated to 0.53.0
0.53.0:
- on_open() missing 1 required positional argument: 'ws'

0.52.0:
- fixed callback argument in _app.py
- Fixing none compare bug in run_forever
- Fix NoneType bug introduced by 386 fix

0.51.0:
- revert "WebSocketApp class to make it inheritable" because of breaking the compatibily

0.50.0:
- fixed pong before ping
- pass proper arguments to method callbacks

0.49.0:
- WebSocketApp class to make it inheritable
- Add option to disable sending the Origin header
- Websocket.close() meaning of "close status: XXXXX"
- Enable multithreading protection with ping_interval
- reset WebsocketApp.sock
- websocket.enableTrace not working
- AttributeError: 'module' object has no attribute 'NullHandler'
- WebSocketBadStatusException "not enough arguments for format string"
- handshake should deal with None in headers