(pkgsrc)   - Add two patches, to avoid    error: incompatible types when assigning to type '__off_t' from type 'fpos_t'    fp_->_offset = u.f;   - Remove one patch patch-af, which had a comment, not necessary for now     " also look in *.mk files as makefiles.  bump pkg revision." (upstream)   - Update 4.2 to 4.6     ---------------------- * Noteworthy changes in release 4.6 (2012-02-03) [stable]
** Bug fixes
  - lid -L no longer mishandles open-ended ranges like "..2" and "2.."
  - lid's -d, -o and -x options now work properly

* Noteworthy changes in release 4.5 (2010-06-17) [stable]
* Noteworthy changes in release 4.4 (2009-10-30) [beta]
                        ------------
** New features
  mkid and xtokid accept a new option --files0-from=FILE, to make them
  process only the files named in FILE.  FILE must contain a list of
  NUL-terminated file names.

** Bug fixes
  mkid and xtokid now accept language specific options via the command line.

* Noteworthy changes in release 4.3.92 (2008-10-18) [beta]
                        --------------
** Bug fixes

  fid: avoid a buffer overrun
  handle failed allocation, e.g., by strdup
  avoid potential realloc overflow
  mkid: avoid an infloop on some .el files
  all programs: detect write error on stdout

** Miscellaneous improvements

  revamp code and infrastructure, bringing it closer to coreutils' standards
  add automatically-generated man pages
  mkid recognize more suffixes: .ac, .mk, .bz2, .lzma.
  idutils is now licensed under the General Public License version 3
    or later (GPLv3+).