The distribution patch under work/nbitools-R6.3/config/md.patch breaks with GNU patch, hurting !NetBSD pkgsrc platforms. Replace the patch with patch-a{m,n,o}, and remove the pre-patch target.
The pkglint
ERROR: Makefile:24: Invalid tool syntax: "${IMAKE_TOOLS:Nimake}".
appears to be bogus, given an identical expression is used in
<mk/tools/imake.mk>.