Update MesaLib to 11.2.0.
Mesa 11.2.0 is a new development release. People who are concerned with
stability and reliability should stick with a previous release or wait for Mesa
11.2.1.

Mesa 11.2.0 implements the OpenGL 4.1 API, but the version reported by
glGetString(GL_VERSION) or glGetIntegerv(GL_MAJOR_VERSION) / glGetIntegerv
(GL_MINOR_VERSION) depends on the particular driver being used. Some drivers
don't support all the features required in OpenGL 4.1. OpenGL 4.1 is only
available if requested at context creation because compatibility contexts are
not supported.

New features

Note: some of the new features are only available with certain drivers.

  • GL_ARB_arrays_of_arrays on all gallium drivers that provide GLSL 1.30
  • GL_ARB_base_instance on freedreno/a4xx
  • GL_ARB_compute_shader on i965
  • GL_ARB_copy_image on r600
  • GL_ARB_indirect_parameters on nvc0
  • GL_ARB_query_buffer_object on nvc0
  • GL_ARB_shader_atomic_counters on nvc0
  • GL_ARB_shader_draw_parameters on i965, nvc0
  • GL_ARB_shader_storage_buffer_object on nvc0
  • GL_ARB_tessellation_shader on i965 and r600 (evergreen/cayman only)
  • GL_ARB_texture_buffer_object_rgb32 on freedreno/a4xx
  • GL_ARB_texture_buffer_range on freedreno/a4xx
  • GL_ARB_texture_query_lod on freedreno/a4xx
  • GL_ARB_texture_rgb10_a2ui on freedreno/a4xx
  • GL_ARB_texture_view on freedreno/a4xx
  • GL_ARB_vertex_type_10f_11f_11f_rev on freedreno/a4xx
  • GL_KHR_texture_compression_astc_ldr on freedreno/a4xx
  • GL_AMD_performance_monitor on radeonsi (CIK+ only)
  • GL_ATI_meminfo on r600, radeonsi
  • GL_NVX_gpu_memory_info on r600, radeonsi
  • New OSMesaCreateContextAttribs() function (for creating core profile
    contexts)

Bug fixes

  • Bug 27512 - Illegal instruction _mesa_x86_64_transform_points4_general
  • Bug 75165 - compute.c:464:49: error: function definition is not allowed
    here
  • Bug 79783 - Distorted output in obs-studio where other vendors "work"
  • Bug 89330 - piglit glsl-1.50 invariant-qualifier-in-out-block-01 regression
  • Bug 89969 - nouveau: add support for chunk decoding in order to support
    vaapi (st/va)
  • Bug 90348 - Spilling failure of b96 merged value
  • Bug 91526 - World of Warcraft (on Wine) has UI corruption with nouveau
  • Bug 91596 - EGL_KHR_gl_colorspace (v2) causes problem with Android-x86 GUI
  • Bug 91806 - configure does not test whether assembler supports sse4.1
  • Bug 91927 - [SKL] [regression] piglit compressed textures tests fail with
    kernel upgrade
  • Bug 92193 - [SKL]
    ES2-CTS.gtf.GL2ExtensionTests.compressed_astc_texture.compressed_astc_texture
    fails
  • Bug 92229 - [APITRACE] SOMA have serious graphical errors
  • Bug 92233 - Unigine Heaven 4.0 silhuette run
  • Bug 92363 - [BSW/BDW] ogles1conform Gets test fails
  • Bug 92438 - Segfault in pushbuf_kref when running the android emulator
    (qemu) on nv50
  • Bug 92589 - [BDW BSW SKL CTS] ES31-CTS.texture_gather.* GPU_HANG
  • Bug 92595 - [HSW,BDW,SKL][GLES 3.1 CTS] Big difference in the results for
    the ES31-CTS.shader_bitfield_operation.* tests
  • Bug 92609 - [BDW, BSW] piglit sampling-2d-array-as-2d-layer fails
  • Bug 92687 - Add support for ARB_internalformat_query2
  • Bug 92706 - glBlitFramebuffer refuses to blit RGBA to RGB with MSAA
  • Bug 92709 - "LLVM triggered Diagnostic Handler: unsupported call to
    function ldexpf in main" when starting race in stuntrally
  • Bug 92743 - Centroid shouldn't have to match between the FS and the VS
  • Bug 92759 - [Regression, bisected] Visuals without alpha bits are not
    sRGB-capable
  • Bug 92849 - [IVB HSW BDW] piglit image load/store
    load-from-cleared-image.shader_test fails
  • Bug 92909 - Offset/alignment issue with layout std140 and vec3
  • Bug 93004 - Guild Wars 2 crash on nouveau DX11 cards
  • Bug 93048 - [CTS regression] mesa af2723 breaks GL Conformance for debug
    extension
  • Bug 93063 - drm_helper.h:227:1: error: static declaration of
    ‘pipe_virgl_create_screen’ follows non-static declaration
  • Bug 93091 - [opencl] segfault when running any opencl programs (like
    clinfo)
  • Bug 93092 - lp_test_format regression
  • Bug 93126 - wrongly claim supporting GL_EXT_texture_rg
  • Bug 93180 - [regression] arb_separate_shader_objects.active sampler
    conflict fails
  • Bug 93189 - "./util/u_inlines.h", line 83: operands have incompatible
    types: void ":" int
  • Bug 93215 - [Regression bisected] Ogles1conform Automatic mipmap generation
    test is fail
  • Bug 93235 - [regression] dispatch sanity broken by GetPointerv
  • Bug 93257 - [SKL, bisected] ASTC dEQP tests segfault
  • Bug 93264 - Tonga VM Faults since llvm ScheduleDAGInstrs: Rework schedule
    graph builder.
  • Bug 93266 - gl_arb_shading_language_420pack does not allow binding of image
    variables
  • Bug 93300 - Two Worlds 2 renders water incorrectly
  • Bug 93312 - [SKL][GLES 3.1 CTS] ES31-CTS.layout_binding* GPU_HANG
  • Bug 93320 - [HSW,BDW,SKL][GLES 3.1 CTS]
    ES31-CTS.vertex_attrib_binding.advanced-bindingUpdate fail
  • Bug 93322 - [HSW,BDW,SKL][GLES 3.1 CTS]
    ES31-CTS.compute_shader.resource-ubo fail
  • Bug 93323 - [HSW,BDW,SKL][GLES 3.1 CTS]
    ES31-CTS.shader_image_load_store.basic-allTargets-store-fs fail
  • Bug 93325 - [HSW,BDW,SKL]ES31-CTS.explicit_uniform_location.uniform-loc-* 2
    tests fail
  • Bug 93339 - glLinkProgram() should fail when a varying is never written to
    in a previous stage
  • Bug 93348 - [HSW,BDW,SKL][GLES 3.1 CTS] ES31-CTS.compute_shader.* segfault
  • Bug 93358 - [HSW] Unreal Elemental demo - assertion error in
    copy_image_with_blitter
  • Bug 93387 - inverse() shouldn’t be exposed in GLSL 1.20 and 1.30
  • Bug 93388 - [i965, regression, bisection] MESA_FORMAT_B8G8R8X8_SRGB changes
    break kwin
  • Bug 93407 - [SKL][GLES 3.1 CTS]ES31-CTS.compute_shader.resources-texture
    fail
  • Bug 93410 - [BDW,SKL][GLES 3.1 CTS]
    ES31-CTS.shader_image_load_store.negative-linkErrors fail
  • Bug 93418 - Geometry Shaders output wrong vertices on Sandy Bridge
  • Bug 93426 - [SKL,BDW,BSW,BXT] CTS regression:
    es2-cts.gtf.gl2fixedtests.buffer_objects.buffer_object,s
  • Bug 93524 - Clover doesn't build
  • Bug 93526 - GfxBench 4 tessellation demos misrender
  • Bug 93532 - [HSW,BDW,SKL][GLES 3.1 CTS] ES31-CTS.compute_shader.*.
    Regression, bisected.
  • Bug 93540 - [BISECTED, HSW] Rendering issue in Heaven (and other
    benchmarks)
  • Bug 93560 - opt_combine_constants failing fabsf(reg->f) == table.imm[i].val
    assertion
  • Bug 93599 - Strange green flashes with "Metro: Last Light Redux" + "Metro
    2033 Redux" with Intel Mesa driver
  • Bug 93648 - Random lines being rendered when playing Dolphin (geometry
    shaders related, w/ apitrace)
  • Bug 93650 - GL_ARB_separate_shader_objects is buggy (PCSX2)
  • Bug 93667 - Crash in eglCreateImageKHR with huge texture size
  • Bug 93696 - [HSW,BDW;SKL][GLES 3.1 CTS]
    ES31-CTS.explicit_uniform_location.uniform-loc-mix-with-implicit-max-* fail
  • Bug 93700 - [SKL, regression] deqp-gles2.functional.texture.completeness
  • Bug 93717 - Meta mipmap generation can corrupt texture state
  • Bug 93722 - Segfault when compiling shader with a subroutine that takes a
    parameter
  • Bug 93725 - [HSW, regression, bisected] ES31-CTS.texture_gather.*depth*
  • Bug 93731 - glUniformSubroutinesuiv segfaults when subroutine uniform is
    bound to a specific location
  • Bug 93761 - A conditional discard in a fragment shader causes no depth
    writing at all
  • Bug 93790 - [HSW] Use after free with compute programs
  • Bug 93792 - [HSW] intel_mipmap_tree.c:1325: intel_miptree_copy_slice:
    Assertion `src_mt->format == dst_mt->format
  • Bug 93813 - Incorrect viewport range when GL_CLIP_ORIGIN is GL_UPPER_LEFT
  • Bug 93840 - [i965] Alien: Isolation fails with GL_ARB_compute_shader
    enabled
  • Bug 93862 - [Bisected] "drm/amdgpu: fix amdgpu_bo_pin_restricted VRAM
    placing v2" is bad
  • Bug 93878 - [llvmpipe][softpipe] piglit
    arb_gpu_shader_fp64-double-gettransformfeedbackvarying regression
  • Bug 93957 - [HSW] Mishandling of sample count when using an attachment-less
    framebuffer (assertion error)
  • Bug 93961 - virgl build failure after 2016-02-01 changes - no previous
    prototype for 'virgl_drm_winsys_create'
  • Bug 93962 - [HSW, regression, bisected, CTS]
    ES2-CTS.gtf.GL2FixedTests.scissor.scissor - segfault/asserts
  • Bug 93989 - build: flex-2.5.39 seems to be failing for glsl_lexer.ll
  • Bug 94016 - make check MesaExtensionsTest.AlphabeticallySorted regression
  • Bug 94019 - [bisected] 3D acceleration broken with gallium/radeon: just get
    num_tile_pipes from the winsys
  • Bug 94050 - test_vec4_register_coalesce regression
  • Bug 94073 - Miscompilation of abs_vec3_vert_xvary_ref.vert in WebGL
    conformance
  • Bug 94081 - [HSW] compute shader shared var + atomic op = fail
  • Bug 94088 - [llvmpipe] SIGFPE pthread_barrier_destroy.c:40
  • Bug 94091 - Tonga unreal elemental segfault since radeonsi: put image,
    fmask, and sampler descriptors into one array
  • Bug 94100 - [HSW] compute indirect dispatch with 0 work groups causes gpu
    hang
  • Bug 94134 - [regression]
    piglit.spec.arb_texture_view.sampling-2d-array-as-2d-layer assertion
  • Bug 94139 - [regression, HSW, IVB] piglit.spec.arb_compute_shader.minmax
  • Bug 94150 - UE4 Suntemple rendering errors
  • Bug 94186 - Crash when launching glxinfo and World of Warcraft with RV790
  • Bug 94188 - define (or undef) defined behaves stupidly
  • Bug 94193 - [llvmpipe] Line antialiasing looks different when
    GL_LINE_STIPPLE is enabled with pattern 0xffff
  • Bug 94199 - Shader abort/crash
  • Bug 94253 - [llvmpipe] piglit gl-1.0-swapbuffers-behavior regression
  • Bug 94254 - [llvmpipe] [softpipe] piglit read-front regression
  • Bug 94257 - [softpipe] piglit glx-copy-sub-buffer regression
  • Bug 94274 - [swrast] piglit arb_occlusion_query2-render regression
  • Bug 94284 - [radeonsi] outlast segfault on start
  • Bug 94388 - r600_blit.c:281: r600_decompress_depth_textures: Assertion
    `tex->is_depth && !tex->is_flushing_texture' failed.
  • Bug 94412 - Trine 3 misrender
  • Bug 94481 - softpipe - access violation in img_filter_2d_nearest
  • Bug 94524 - Wrong gl_TessLevelOuter interpretation for isolines
  • Bug 94595 - [Mesa AMD&swrast] Texture views attached as framebuffers return
    their viewed tecture's color encoding and render incorrectly