alsa-lib: update to 1.2.15.1.
1.12.5.1

alsa-lib
Core

    Release v1.2.15.1
    ucm: use closefrom instead of close_range

Use Case Manager API

    ucm: exec - fix maxfd used warning
    ucm: use closefrom instead of close_range

Configuration

    conf: cards: unify whitespace - use tabs and remove trailing spaces
    conf: pistachio-card: define pcm configuration block only one time
    conf: YMF744: define pcm configuration block only one time
    conf: VX222,VXPocket: define pcm configuration block only one time
    conf: VIA686A,VIA82xx: define pcm configuration block only one time
    conf: TRID4DWAVENX: define pcm configuration block only one time
    conf: SI7018: define pcm configuration block only one time
    conf: SB-XFi: define pcm configuration block only one time
    conf: RME96[35][26]: define pcm configuration block only one time
    conf: PS3: define pcm configuration block only one time
    conf: PMac,PMacToonie: define pcm configuration block only one time
    conf: PC-Speaker: define pcm configuration block only one time
    conf: NFORCE: define pcm configuration block only one time
    conf: Maestro3: define pcm configuration block only one time
    conf: Loopback: define pcm configuration block only one time
    conf: ICH,ICH4,ICH-MODEM: define pcm configuration block only one time
    conf: ICE17[12][24]: define pcm configuration block only one time
    conf: HdmiLpeAudio: define pcm configuration block only one time
    conf: GUS: define pcm configuration block only one time
    conf: FWSpeakers: define pcm configuration block only one time
    conf: FM801: define pcm configuration block only one time
    conf: FireWave: define pcm configuration block only one time
    conf: ES1968: define pcm configuration block only one time
    conf: ENS137[01]: define pcm configuration block only one time
    conf: EMU10K1X: define pcm configuration block only one time
    conf: EMU10K1: define pcm configuration block only one time
    conf: Aureon51: define pcm configuration block only one time
    conf: Echo3G: define pcm configuration block only one time
    conf: CS46xx: define pcm configuration block only one time
    conf: CMI8xxx: define pcm configuration block only one time
    conf: CA0106: define pcm configuration block only one time
    conf: AU88[123]0: define pcm configuration block only one time
    conf: Aureon: define pcm configuration block only one time
    conf: Audigy: define pcm configuration block only one time
    conf: AACI,ATIIXP: define pcm configuration block only one time
    conf: vc4-hdmi: define pcm configuration block only one time
    conf: HDA-Intel: define pcm configuration block only one time
    conf: USB-Audio: define pcm configuration block only one time
    Revert "conf: fix load_for_all_cards() - do not merge the card specific contents"
    conf: fix possible memory leak in config_file_open() - error path
    conf: merge card specific contents per file (whole) after parsing

1.12.5

alsa-lib
Core

    Release v1.2.15
    include: fix typo in error.h to avoid compile error when gcc <= 2.95
    include: list.h - add list_splice() and list_splice_init() functions
    github: add coverity.yml
    doxygen: fix warnings and add missing ALSA_LIBRARY_BUILD define
    error: add missing log_priority/interface functions to header file
    configure: bumb version to 1.2.13pre1 (for alsa-utils)
    include: remove local SNDMSG/SYSMSG defines (no longer used)
    huge correction of tabulators and whitespaces
    log: implement filter based on string configuration (env LIBASOUND_DEBUG).
    error: add priority and interface strings to the log messages
    redesign the message log functions
    error: do not export internal snd_err_msg variable
    github: fix Fedora workflow (awk package dependency)

Config API

    doxygen: fix warnings and add missing ALSA_LIBRARY_BUILD define
    huge correction of tabulators and whitespaces

Control API

    coverity.com fixes - initial round
    snd_tlv_convert_to_dB: Fix mute handling for MINMAX_MUTE type
    doxygen: fix warnings and add missing ALSA_LIBRARY_BUILD define
    huge correction of tabulators and whitespaces
    redesign the message log functions

HWDEP API

    doxygen: fix warnings and add missing ALSA_LIBRARY_BUILD define

Mixer API

    mixer: abst - reshuffle snd_mixer_simple_basic_register code to be more logical
    doxygen: fix warnings and add missing ALSA_LIBRARY_BUILD define
    huge correction of tabulators and whitespaces
    mixer: bag - fix bag_del_all implementation (missing free)

Mixer Abstraction API

    huge correction of tabulators and whitespaces

PCM API

    pcm: plugin - avoid 32-bit to 64-bit return value conversions
    add missing return value changes for snd_config_get_string() calls
    add missing return value changes for snd_config_get_id() calls
    doxygen: fix warnings and add missing ALSA_LIBRARY_BUILD define
    pcm route: suppress false positive warning for gcc 8+
    pcm: add a loop to snd_pcm_avail_delay() to avoid bogus delay values

Rawmidi API

    rawmidi: Fix SNDRV_RAWMIDI_INFO_STREAM_INACTIVE duplicate definition
    rawmidi: Fix the prefix of the inactive stream flag

Sequencer API

    seq: fix snd_seq_drain_output return value for partial drain
    seq: hw - notify if running mode / pversion ioctl fails

Topology API

    add missing return value changes for snd_config_get_id() calls
    topology: fix nibble warning in tplg_save_quoted()

Use Case Manager API

    ucm: add ValueGlobals section to the top configuration file
    ucm: fix the DefineRegex issue where multiple variables were set to empty string
    ucm: Include directive - add optional behaviour
    ucm: complete dependency graphs for conflicting/supported device lists
    ucm: implement DeviceVariant configuration extension
    ucm: implement ValueDefaults.BootCardGroup and define use
    ucm: keep original device name for logs
    ucm: sort devices by priority
    ucm: doc - add examples for device name with descriptors (colon)
    ucm: be more restrictive for device name with descriptor
    ucm: strip device index when the device type is present only one time
    ucm: add support for device names with colon (':')
    ucm: normalize device names
    ucm: add possibility to inline Verb configurations to the main configuration file
    ucm: add Prepend and Append block handling for If conditions (syntax 8+)
    add missing return value changes for snd_config_get_string() calls
    ucm: add missing stdbool.h include to ucm_local.h
    ucm: fix variant issue where variables or macros are overwritten
    ucm: remove 'error: ' prefix from error messages (duplication)
    ucm: remove uc_dbg macro and callers
    ucm: replace uc_error with snd_error calls
    ucm: add a basic set of trace/debug log calls
    ucm: use close_range on _GNU_SOURCE
    Force to use alphasort64() sorting function for Harmony OS
    ucm: regex: fix the error message (missing argument)
    Revert "ucm: do not bump syntax version to 8"

ALSA Server

    coverity.com fixes - initial round
    huge correction of tabulators and whitespaces
    replace SNDMSG,SYSMSG,SNDERR,SYSERR with new log macros

Async helpers

    coverity.com fixes - initial round
    replace SNDMSG,SYSMSG,SNDERR,SYSERR with new log macros

Configuration

    coverity.com fixes - initial round
    add missing return value changes for snd_config_get_string() calls
    add missing return value changes for snd_config_get_id() calls
    conf/pistachio: fix syntax
    config: do not print errno in snd_config_check_hop()
    redesign the message log functions
    conf: fix load_for_all_cards() - do not merge the card specific contents
    conf: fix parse_array_def - merge arrays
    conf: Revert "conf: fix load_for_all_cards()"
    conf: fix parse_array_def override code path
    Force to use alphasort64() sorting function for Harmony OS
    conf: aliases: add hda-acpi -> HDA-Intel alias

Documentation

    doc: add missing include pcm_plugin.h to source files
    doxygen: fix warnings and add missing ALSA_LIBRARY_BUILD define

Error handler

    coverity.com fixes - initial round
    error: make prio/interface output a bit shorter in default log handler
    log: implement filter based on string configuration (env LIBASOUND_DEBUG).
    error: add priority and interface strings to the log messages
    redesign the message log functions
    error: do not export internal snd_err_msg variable

Simple Abstraction Mixer Modules

    replace SNDMSG,SYSMSG,SNDERR,SYSERR with new log macros

Test/Example code

    test: ucm - remove old syntax configuration files (incomplete anyway)
    test: update midifile library to ANSI C