py-sphinx: updated to 1.8.1
Release 1.8.1:

Incompatible changes
LaTeX \pagestyle commands have been moved to the LaTeX template. No changes in PDF, except possibly if \sphinxtableofcontents, which contained them, had been customized in conf.py.

Bugs fixed
* Incorrect default path for sphinx-build -d/doctrees files
* autodoc emits deprecation warning for autodoc_default_flags
* lambda object causes PicklingError on storing environment
* Sphinx fails to build with syntax error in Python 2.7.5
* add latexpdf to make.bat for non make-mode
* Autodoc does not work with enum subclasses with properties/methods
* autodoc: crashed on modules importing eggs
* latex: ImportError: cannot import name ‘DEFAULT_SETTINGS’
* autodoc: autofunction emits a warning for callable objects
* Fix TypeError in error message when override is prohibited
* PDF builds of ‘howto’ documents have no page numbers
* mathbase: math_role and MathDirective was disappeared in 1.8.0
* latex: Index has disappeared from PDF for Japanese documents
* py domain: :type: field can’t process :term: references
* py domain: TypeError has been raised for class attribute