py-filelock: update to 3.15.4.
3.15.4

Pass file_lock as positional argument by @kwist-sgr in #347

3.15.3

Add test for virtualenv stability by @gaborbernat in #344
Fix TypeError: _CountedFileLock.__init__() got an unexpected keyword argument 'timeout' by @kwist-sgr in #345

3.15.2

Use a metaclass to implement the singleton pattern by @kwist-sgr in #340