Update to 0.4.6. Bump depends in bl3 file because of shlib major bump.
* Version 0.4.6 (released 2004-05-24)

** The header file idn-free.h is actually installed by 'make install'.

** API and ABI is backwards compatible with the previous version.

* Version 0.4.5 (released 2004-05-21)

** In IDNA ToUnicode, a `free' on a stale pointer fixed by Ulrich Drepper.

** Several memory leaks fixed by Ulrich Drepper.

** Added more SASLPrep and NFKC test vectors.

** Automake 1.8.4 is used.

** API and ABI is backwards compatible with the previous version.
idn_free: ADD.  Wrapper around system `free'.
idn-free.h: ADD.  Prototype for `idn_free'.
                See idn-free.h for discussion.  The interface is
                currently not documented.  Comments and feedback is
                appreciated.

* Version 0.4.4 (released 2004-04-29)

** Fixed two bugs in iSCSI definition, syncing with newly published RFC 3722.
The first bug was an omission of prohibiting the characters in C.1.1,
C.1.2 and C.7 (space characters and characters that are inappropriate
for canonical representation).  The second was a bug in the definition
of the table, causing the entire table to be skipped, of the special
prohibited output character table defined in RFC 3722 (see section 6,
the characters in the table are various ASCII characters and U+3002).

** A few test vectors for iSCSI were added.

** The self tests are linked with libtool -no-install to avoid wrapper script.

** Separated self test utilities into a separate library, shared by all tests.

** More translations.
Added Romanian (by Laurentiu Buzdugan).

** API and ABI is backwards compatible with the previous version.

* Version 0.4.3 (released 2004-04-22)

** Fixed a bug in table processing code to prohibit control characters.
The problem was that the code used a code point of 0 to indicate end
of table, but if (as for table C.2.1) a range starts with 0, this
logic would fail.  The end-of-table test is now that both the start
and end code points of the range is 0.  Table C.2.1 is responsible for
prohibiting non-ASCII control characters, i.e. ASCII 0-31 and 127.
Before, libidn silently accepted such strings without complaining.

** A few test vectors for SASLprep were added.

** The pkg-config script no longer include a -R parameter.

** More translations.
Added Dutch (by Elros Cyriatan), and German (by Roland Illig).

** API and ABI is backwards compatible with the previous version.

* Version 0.4.2 (released 2004-03-20)

** A Punycode implementation in Java was added, by Oliver Hitz.
Eventually hopefully a StringPrep, Nameprep and IDNA implementation
will be added as well.  Currently you need to specify --enable-java to
enable the Java interface.  The Java sources (below java/) are
compiled into byte-code (not native code) into a JAR library.

** More translations.
Added Danish (by Morten Bo Johansen), French (by Michel Robitaille),
Polish (by Jakub Bogusz), and Serbian (by Aleksandar Jelenak).

** Norwegian TLD table added, by Thomas Jacob.

** API and ABI is backwards compatible with the previous version.

* Version 0.4.1 (released 2004-03-08)

** The user messages from the command line utility are now translated.
Currently English and Swedish is supported.

** Logic of stringprep_locale_charset modified.
Future versions will use, in order, $CHARSET iff defined, nl_langinfo
(CODESET) iff working, or fall back to returning "ASCII".  Earlier it
attempted to guess the system locale, in contrast with the current
application's locale, via some setlocale save/set/reset magic.  This
change may require you to invoke setlocale() in your application,
which is (should be) required for non-ASCII to work anyway.  Based on
discussion with Ulrich Drepper.

** The command-line utility now invoke setlocale (LC_ALL, "") at startup.

** Fixed SASLprep tables to prohibit non-ASCII space in output.
Non-ASCII space has always been mapped to ASCII space, so it is not
clear this really have any effect, but the specification require it.

** Building Libidn as part of GLIBC has been updated.
Refer to libc/README for more information.  Incidentally, GLIBC in CVS
now include a copy of Libidn.

** API and ABI is backwards compatible with the previous version.
IDNA_DLOPEN_ERROR: ADD.  Only used internally by Libidn in libc.

* Version 0.4.0 (released 2004-02-28)

** Support for TLD restrictions on IDN strings, contributed by Thomas Jacob.
Many TLDs restrict the set of characters that can be used, from the
full Unicode 3.2 range that is normally available.  This contribution
make it possible for you to test strings for TLD conformance locally.
The code can be disabled by --disable-tld.  If enabled (the default),
the new API "tld.h" is installed which can be used to check a string
for conformance to TLD specific rules.  This add a new self test, and
a new chapter in the manual.  People responsible for maintaining TLD
tables are hereby encouraged to contribute them (under reasonable
licensing terms) for inclusion in future versions of Libidn.  Be
warned that the API for TLD checking may change throughout the 0.4.x
series as we get feedback on it.

** Kerberos 5 stringprep profile macro is no longer documented.
The macro itself will probably be removed in the future, if the
specification is dropped from the Kerberos WG agenda.

** API and ABI is backwards compatible with the previous version.
stringprep_kerberos5: DEPRECATED.
Tld_table_element:
Tld_table:
Tld_rc: ADD.  New data types.
tld_get_4:
tld_get_4z:
tld_get_z: ADD.  New functions to extract TLD from string.
tld_get_table:
tld_default_table: ADD.  New functions to get TLD table from TLD name.
tld_check_4t:
tld_check_4tz: ADD.  New function to provide core TLD operations.
tld_check_4:
tld_check_4z:
tld_check_8z:
tld_check_lz: ADD.  New functions that combine all TLD operations in one call.

* Version 0.3.7 (released 2004-01-22)

** The command line parameter '--' idiom is documented.

** The iSCSI stringprep profile now recognized as "iSCSI".
The earlier name "ISCSIprep" is still recognized, for backwards
compatibility.

** DocBook manuals no longer included (the tools are too unstable).

** API and ABI is backwards compatible with the previous version.

* Version 0.3.6 (released 2004-01-06)

** The manual now contain a troubleshooting section for the command line tool.

** The PHP interface pass the string directly on the command line.

** The macro that create 'idn-int.h' has been updated to latest version.

** API and ABI is backwards compatible with the previous version.

* Version 0.3.5 (released 2003-12-15)

** The program 'idn' accepts input strings directly on the command line.

** The program 'idn' defaults to --idna-to-ascii if no parameter is given.

** The program 'idn' now print user instructions before waiting for input.

** DocBook HTML output not included any longer.
The reason is that the filenames generated by docbook2html appear to
be rather random, so it is difficult to maintain the Makefile.am rules
for them.

** Autoconf 2.59, automake 1.8 and libtool from CVS is used.

** API and ABI is backwards compatible with the previous version.
IDNA_CONTAINS_NON_LDH: ADD.  Same integer value as IDNA_CONTAINS_LDH.
IDNA_CONTAINS_LDH: DEPRECATED.  LDH (letter-digits-hyphens) characters
   		are not an error, but non-LDH characters are, when
   		IDNA_USE_STD3_ASCII_RULES is used.  The logic of the
   		mnemonic name of this error constant was reversed.

* Version 0.3.4 (released 2003-11-09)

** DocBook manuals in XML, PDF, PostScript, ASCII and HTML formats included.