py-test-asyncio: updated to 1.2.0
1.2.0

Added

--asyncio-debug CLI option and asyncio_debug configuration option to enable asyncio debug mode for the default event loop.
A pytest.UsageError for invalid configuration values of asyncio_default_fixture_loop_scope and asyncio_default_test_loop_scope.
Compatibility with the Pyright type checker

Fixed

RuntimeError: There is no current event loop in thread 'MainThread' when any test unsets the event loop (such as when using asyncio.run and asyncio.Runner).
Deprecation warning when decorating an asynchronous fixture with @pytest.fixture in [strict]{.title-ref} mode. The warning message now refers to the correct package.

Notes for Downstream Packagers

Bump the minimum required version of tox to v4.28. This change is only relevant if you use the tox.ini file provided by pytest-asyncio to run tests.
Extend dependency on typing-extensions>=4.12 from Python<3.10 to Python<3.13.