grip: update to 4.0.1
pkgsrc changes:
---------------
  * remove outdated patches

upstream changes:
-----------------
v4.0.1 2019-12-02  Johnny A. Solbu <johnny@solbu.net>

	* Patch from Dan Fandrich:
	  Stop copying overlapping strings on multi-artist CDs
	* Add korean translation from TP
	* nl.po, zh_CN.po: Update translations from TP

v4.0.0 2019-10-05  Johnny A. Solbu <johnny@solbu.net>

	* Patches from Adrian Reber:
	  - Remove vte dependency
	     grip uses vte for its status window. The version of vte grip relies on
	     is not maintained upstream for a long time. This commit removes the
	     complete status window functionality from grip. Messages previously sent
	     to the status window are now sent to the console.
	  - Switch to non-deprecated g_string functions
	  - Ignore deprecation errors

v3.10.2 2019-08-17  Johnny A. Solbu <johnny@solbu.net>

	* Sync updated french translation from Translation Project

v3.10.1 2019-02-24  Johnny A. Solbu <johnny@solbu.net>

	* Patch from Lutz Mändle: Calculates the correct space needed for
	  drawing the labels in the edit box
	* Patch from Adrian Reber: Fix errors with gcc9 and terminate strings correctly

v3.10.0 2019-01-07  Johnny A. Solbu <johnny@solbu.net>

	* Patch from Frédéric Fauberteau: undefined reference to `WIFEXITED'
	  (patch issue #162)
	* Translation updates: New danish translation
	* Remove freedb.musicbrainz.org as secondary default cd database:
	  https://blog.metabrainz.org/2018/09/18/freedb-gateway-end-of-life-notice-march-18-2019/
	* automake: Replace INCLUDES with AM_CPPFLAGS
	* Rename configure.in > configure.ac