py-proto-plus: update to 1.24.0.
1.24.0 (2024-06-11)

Features

    Add always_print_fields_with_no_presence fields to to_json and to_dict (0f89372)

Bug Fixes

    Add compatibility with protobuf==5.x (0f89372)
    AttributeError module 'google._upb._message' has no attribute 'MessageMapContainer' (0f89372)
    deps: Allow protobuf 5.x (#457) (62d74e3)
    Drop python 3.6 (#456) (5a7666c)

Documentation

    Deprecate field including_default_value_fields in to_json and to_dict (0f89372)