Remove tcp_wrappers option to fix exim build
Exim has removed support for tcpwrappers, and the remaining -lwrap
in the linking flags causes the build to fail on NetBSD with:

/usr/lib/libwrap.so: undefined reference to `allow_severity'
/usr/lib/libwrap.so: undefined reference to `deny_severity'

Bump PKGREVISION