Update sun-jdk15 and sun-jre15 to 1.5.0_01 (which in pkgsrc is represented by version 5.0.1).
List of bugs fixed in this release:

5087041 - hotspot - compiler1 - Tiger b62 vm crashes in client compiler
5026838 - hotspot - compiler2 - 1.4.2_04 Server JVM crashes on Linux
5033614 - hotspot - compiler2 - ClassLoaders do not get released by GC,
          causing OutOfMemory in Perm Space
5071820 - hotspot - compiler2 - server VM crashes with -Xcomp in 1.4.2_05
5090967 - hotspot - garbage_collector - SIGSEGV in
          ContiguousSpace::prepare_for_compaction(CompactPoint*)
5096167 - hotspot - jvmti - null class name crashes VM if ClassFileLoadHook
          is enabled
6195632 - hotspot - other - jhelper must be recompiled with the beta version
          of dtrace
5095421 - hotspot - runtime_system - amd64 vm should not crash on em64t
5101288 - hotspot - runtime_system - async exception can be delivered on entry
          from native to vm
4993280 - java - apt - apt should favor source files over class files for
          type information
4996963 - java - apt - apt could accept class files and java files on the
          command line
5095716 - java - apt - RoundState.finalRound computed improperly
5096931 - java - apt - TypeDeclaration.getMethods needs to screen out static
          initializers
5096932 - java - apt - Bad comparator in SourceOrderDeclScanner
6174696 - java - apt - apt getTypeDeclaration(Strings) cannot find classes
          that are not already loaded
5079070 - java - build - metadata incorrect for 1.5.0_01
5099622 - java - build - Don't use javah_g in j2se build
5106516 - java - build - Please define JDK update version in makefile
5108366 - java - build - invalid characters in English LICENSE file in tiger
          b64 solaris/linux bundles
6174598 - java - build - Need to backout fix for 5106516
6201982 - java - build - Solaris 8 Build patch requirement change, need
          109147-32/109148-32 (ld/dtrace issue)
4806753 - java - char_encodings - Using alternating charsets with
          String(byte[]) and String.getBytes is very slow
5002890 - java - char_encodings - (cs) Charset.isSupported is slow when
          invoked for different charsets
5066464 - java - classes_2d - JDK 1.5 fontconfig.properties should not include
          abolute path to physical font
6173770 - java - classes_2d - JCK-5.0 test
          api/java_awt/Graphics/index.html#CopyArea[Graphics0018_14] fails
          intermittently
4972534 - java - classes_awt - [Tiger]Can't input anything into textfields on
          solaris10 by JRE1.5-B32
5076963 - java - classes_awt - JNI bugs in sun.awt.windows.WToolkit.eventLoop()
5085626 - java - classes_awt - Exponential performance regression in AWT
          components (multiple monitors)
5088782 - java - classes_awt - AWT application does not load : throws NPE
5093198 - java - classes_awt - XAWT: Java crashes on window
          dispose/getLocationOnScreen
6178323 - java - classes_awt - REGRRESSION: sun.awt.windows.WComponentPeer
          throws exception "couldn't create component peer"
5097856 - java - classes_lang - (reflect) hashCode of TypeVariable causes
          StackOverflowError
5101311 - java - classes_lang - NullPointerException thrown when environment
          contains strings without `='
5101626 - java - classes_lang - Unexpected NPE from toLowerCase
5082105 - java - classes_net - InetAddress.isReachable() leaves open handles
          after execution
5086348 - java - classes_net - URL.openConnection(Proxy.NO_PROXY) throws
          NULLPointerException
5087907 - java - classes_net - InetAddress.getAllByName does not obey setting
          of java.net.preferIPv6Addresses
6197569 - java - classes_net - VM crash if java application tries to use
          system proxy (Solaris10 build 71 CDE only)
5100121 - java - classes_nio - (se) select not immune to EINTR (linux)
5072953 - java - classes_security - AuthorityInfoAccess certificate extension
          is being ignored.
5100603 - java - classes_security - Need JKS KeyStore with case sensitive
          alias names
4890345 - java - classes_swing - 1.4.2 REGRESSION: JComboBox has problem in
          JTable in Windows L&F
4959489 - java - classes_swing - NPE in
          javax.swing.text.html.ParagraphView.paint()
5036904 - java - classes_swing - JFileChooser in Motif L&F does not comply
          with Section 508
5059744 - java - classes_swing - [App]Press Ctl+Space, there is exception
          thrown in jgraphpad
5061077 - java - classes_swing - Exception with JFileChooser in GTK LNF
5073869 - java - classes_swing - Synth does not resolve styles with name and
          region matches correctly
5077647 - java - classes_swing - Under GTK L&F JFileChooser does not have
          drag support at all.
5080144 - java - classes_swing - REGRESSION: XP L&F: JTextField.setEditable()
          does not change background color
5082298 - java - classes_swing - REGRESSION:
          com/sun/java/swing/plaf/gtk/5048769/bug5048769.sh fails
5084107 - java - classes_swing - Regression: JTextPane doesn't wrap with RTL
          ComponentOrientation
5087905 - java - classes_swing - REGRESSION: CSS cause NPE for unknown colours
5088268 - java - classes_swing - REGRESSION: Suns Default CSS has bad styles
          for lists
5089077 - java - classes_swing - Regression: NPE when relative font sizes used
          in html
5092815 - java - classes_swing - REGRESSION: Simplified chinese file name not
          displayed correctly in JFileChooser
5094122 - java - classes_swing - Applets fail w/ GTK L&F due to security
          manager.
5096948 - java - classes_swing - 1.5.0 Regression: NPE when switching from
          Metal L&F with JComboBox
5097973 - java - classes_swing - REGRESSION: table border nonumerical width
          is broken
6175284 - java - classes_swing - REGRESSION:
          javax/swing/JScrollPane/5096948/bug5096948.java fails to compile
5101540 - java - classes_util_i18n - New Turkish currency
4856983 - java - compiler - (crash) mutually f-bounded type vars with multiple
          bounds may crash javac
5081785 - java - compiler - (enum) Empty enum declartion allowed in non-static
          context
5090006 - java - compiler - javac fails with assertion error
5090126 - java - compiler - Clean up com.sun.tools.javac.Main specification
          to reflect CCC 5087488
5092545 - java - compiler - Assertion failed in javac (ClassWriter.java:513)
5094318 - java - compiler - REGRESSION: Array cloning is not backwards
          compatible
5097548 - java - compiler - (crash) Stack overflow in capture conversion
5105890 - java - compiler - (codegen) constant folding broken for conditional
          operator
4853713 - java - doc - Dummy bug report
5092670 - java - doc - tiger supported platforms - discrepancy between internal
          and external matrix
5100416 - java - doc - JDK5.0 README.html references deprecated JVMPI/JVMDI,
          should reference JVM TI
5104731 - java - doc - README files need info about CA certificates
5082481 - java - drag&drop - normal DnD program causes "FATAL ERROR in native
          method"
5057832 - java - install - update releases need to be resolved for namechange
5066525 - java - install - Java Control Panel desktop file needs to be fixed
          (for Cinnabar)
5083395 - java - install - SUNWj5cfg missing class action script for "e" type
          files
5084556 - java - install - Regression: Java icon isn't updated to 1.5.0_01
          on Win98 only
6173968 - java - install - ALT_JRE_CAB_URL default does not need a -jre or -jdk
6175102 - java - install - xpi installer is broken as a result of 5.0 jinstall
          arg changes
6175981 - java - install - Uninstallation through Add/Remove
          Programs/Change/Remove fails and throws a fatal error on AMD
6177485 - java - install - jre1.5.0.10 found in Fearure Descripion of the
          JDK1.5.0_01 b03 Install Wizard
6196130 - java - install - Java default selection not robust on Micro release
6176978 - java - javadoctool - current Javadoc's invocation and extension
          (Doclet) mechanisms are problematic
5109805 - java - localization - l10n for 4996963: apt resource has 6 new
          properties
6174188 - java - localization - l10n for 5081785 & 5097250: compiler resource
          has 2 new properties
5054778 - java - qa_web_eng - problems in http://java.sun.com/
6208691 - java - qa_web_eng - 5.0u1 releasenotes has "SDK"
5093343 - java - runtime - Verifier allows hidden field initialization before
          super() call
5078608 - java_deployment - compression - Digital signatures are invalid after
          unpacking
5062648 - java_deployment - configuration - Wrong initialization order in
          Config.initialize()
6182774 - java_deployment - update - Java Update on XP causing increase in
          java.sun.com traffic
5077565 - java_plugin - iexplorer - Java Script event handlers issue.
5081700 - java_plugin - iexplorer - Java Plug-In no longer supports
          'javascript:' URLs after MS Hotfix 867801
5050796 - java_plugin - misc - REGRESSION: Graybox is not resizable for
          relative dimension applet
5094966 - java_plugin - misc - Mimetypes 1.5.0_01 not recognized on Mozilla
          browser for Solaris and Linux
5100835 - java_plugin - misc - mime type should be updated automatically for
          java update
5076437 - java_plugin - solaris - [cinnabar14] mozilla crashes when opening a
          java applet - intermittent
5047548 - javawebstart - download_engine - Lazy downloading of parts with
          packages is broken
5109575 - javawebstart - download_engine - Authenticating Proxy causes
          NoSuchMethodError when using pre-1.4 jre's
5074087 - javawebstart - general - if title is not specified for
          related-content, app cannot start on windows
5086391 - javawebstart - other - please refert back to 1.4.2 behaviour of
          checking changed jar files...
5093922 - jmx - classes - NotificationBroadcasterSupport should not use
          synchronized(this)
4425728 - jsse - examples - rmi server closes the connection early
5091352 - jsse - runtime - Allow null localKeyID attribute in pkcs12 with
          one private key