cups-filters: Update print/cups-filters to 1.20.3
pkgsrc changes:
 - Fix an error pointed out by gcc-6.4.0 via
   patches/patch-filter_pdftoopvp_OPVPOutputDev.cxx:

    filter/pdftoopvp/OPVPOutputDev.cxx: In member function 'void OPVPOutputDev::doUpdateFont(GfxState*)':
    filter/pdftoopvp/OPVPOutputDev.cxx:532:46: error: invalid conversion from 'const Ref*' to 'Ref*' [-fpermissive]
       id = new SplashOutFontFileID(gfxFont->getID());
                                    ~~~~~~~~~~~~~~^~
    filter/pdftoopvp/OPVPOutputDev.cxx:69:3: note:   initializing argument 1 of 'SplashOutFontFileID::SplashOutFontFileID(Ref*)'
       SplashOutFontFileID(Ref *rA) { r = *rA; substIdx = -1; }
       ^~~~~~~~~~~~~~~~~~~

Changes:
1.20.3
------
 - braille: Do not remove read permission on cups-brf. Thanks
   to Samuel Thibault for this patch (Pull request #32).
 - braille: Get braille table descriptions from liblouis
   metadata. Thanks to Samuel Thibault for this patch (Pull
   request #31).
 - braille: Select liblouis tables based on metadata before
   using file names. Thanks to Samuel Thibault for this patch
   (Pull request #30).
 - cups-browsed: The new method of identifying remote CUPS
   queues via the "printer-type" TXT record field does not work
   for printers discovered by legacy CUPS broadcast (CUPS 1.5.x
   or older). Now consider also printers without TXT record
   (not discovered via DNS-SD) as remote CUPS queues (Issue
   #34).
 - gstoraster: Improved detection whether input is PostScript
   or PDF by skipping over possible headers. Thanks to Rod
   Schmidt (schmidtrod at q dot com) for the patch.

1.20.2
------
 - cups-browsed: If the user modifies/overwrites a print queue
   created by cups-browsed, it will now automatically released
   from the control of cups-browsed, so the modified queue does
   not get removed by cups-browsed on shutdown.  (Ubuntu bug
   #1731417).
 - cups-browsed: The configuration setting
   "CreateIPPPrinterQueues LocalOnly" suppressed also the
   automatic generation of local queues for remote CUPS
   printers whereas this option is only intended for physical
   IPP printers.
 - cups-browsed: Identify remote CUPS queues by the
   "printer-type" TXT record entry and not by the
   "ipp(s)://<host>/printers/<name>" URIs, there are also IPP
   network printers with such URIs (HP LaserJet Professional
   M1212nf MFP in Ubuntu bug #1731417).
 - .gitignore: Added filter/braille/filters/brftopagedbrf
 - cups-browsed, foomatic-rip: Fixed several typos. Thanks to
   Didier Raboud for the patches.