gam: update to 7.40.00 and take maintainership
Take maintainership.

Changes since 7.38.00:

7.40.00

Updated gam print|show businessprofileaccounts (client access) to gam <UserTypeEntity> print|show businessprofileaccounts (service account access). You'll need to run gam user user@domain.com update serviceaccount and select 2)  Business Account Management API.

7.39.08

Fixed bug in gam oauth create that caused a trap when 0)  Business Account Management API was selected.

Upgraded to Python 3.14.4 on macOS and Windows; Linux is still 3.14.3.

7.39.07

Upgraded to OpenSSL 3.6.2.

7.39.06

Fixed bug in gam version checkrc.

7.39.05

Added optional argument preview to updateprimaryemail <RegularExpression> <EmailReplacement> [preview] for the following commands that causes GAM to preview, but not perform, primary email address changes. This allows verification of the primary email address changes before commiting the changes.

gam update group <GroupEntity>
gam update cigroup <GroupEntity>
gam <UserTypeEntity> update user

7.39.04

Added updateprimaryemail <RegularExpression> <EmailReplacement> option to gam update group <GroupEntity> and gam update cigroup <GroupEntity> to allow modifying the group's current primary email address. For example, to change the domain of a set of groups from the current domain.com to newdomain.com:

gam update group csvfile Groups.csv:email updateprimaryemail "^(.+)@domain.com$" "\1@newdomain.com"

7.39.03

Added the following options to gam <UserTypeEntity> create chatspace that can be used to capture space details when creating chat spaces in bulk.

csv [todrive <ToDriveAttribute>*] [formatjson [quotechar <Character>]] (addcsvdata <FieldName> <String>)*

See: https://github.com/GAM-team/GAM/wiki/Users-Chat#bulk-build-chat-spaces

7.39.02

Fixed progress messages for gam <UserTypeEntity> print filelist when permissions were being displayed/matched for Shared Drives.

7.39.01

Updated gam <UserTypeEntity> transfer drive <UserItem> to handle the following error:

ERROR: 403: cannotDeletePermission - The authenticated user cannot delete the permission.

7.39.00

Deleted variable enforce_expansive_access from gam.cfg and removed option enforceexpansiveaccess from the following commands as expansive access is now always enforced by Google on My Drives.

gam <UserTypeEntity> delete permissions
gam <UserTypeEntity> delete drivefileacl
gam <UserTypeEntity> update drivefileacl
gam <UserTypeEntity> copy drivefile
gam <UserTypeEntity> move drivefile
gam <UserTypeEntity> transfer ownership
gam <UserTypeEntity> claim ownership

7.38.02

Added license SKU 1010470009 for AI Expanded Access; abbreviation aiexpandedaccess.

Renamed license SKU 1010470001 from Gemini Enterprise to Gemini Enterprise - Legacy.

7.38.01

Added root as a synonym for '/' in command line arguments that specify an OU. This is to avoid issues where a stand-alone / on the command line may be mis-interpreted by the command line interpreter as a reference to the file system root.