I had libsoup24-2.26.3 installed which was good enough, but I didn't have any gnome-keyring so I get this error:
===> Creating toolchain wrappers for gst-plugins0.10-soup-0.10.18
ERROR: gnome-keyring>=0.4.0 is not installed; can't buildlink files.
*** Error code 1

My workaround is to abuse the BUILDLINK_API_DEPENDS to:
BUILDLINK_API_DEPENDS.libsoup24+=       libsoup24>=2.28.0
(where that version is when the include of gnome-keyring was added)