xlsfonts: update to 1.0.9.
Alan Coopersmith (9):
      Simplify qsort() comparision function to just call strcmp()
      Add --help and --version options
      Improve man page formatting
      man page: fix warnings from `mandoc -T lint` and `groff -rCHECKSTYLE=10`
      Strip trailing whitespace from source files
      IgnoreError: tell the compiler the arguments are intentionally unused
      gitlab CI: drop the ci-fairy check-mr job
      meson: Add option to build with meson
      xlsfonts 1.0.9