mozc: update to 2.20.2673.102.
pkgsrc changes:
- switch to using qt5 (to follow upstream)
- handle ${PREFIX} in more places
- fix package COMMENT (remove "for IBus")
- GCC_REQD 4.7 for c++11
- add patch comments

See PR pkg/52689 for more details.

Upstream changes:
(from https://github.com/google/mozc/blob/master/docs/release_history.md)

Summary of changes between 2.19.2644.102 and 2.20.2673.102 as follows.

    Third party libraries:
        None.
    Build related changes:
        --qtver GYP build option was removed (280e38f).
        Mozc for macOS now uses macOS 10.11 SDK by default (b2a74bb).
    Major changes:
        src/data/installer/credits_ja.html was removed (2ec6c8f).
        Mozc for macOS now generates 64-bit executables. 32-bit machine is no longer supported on macOS.
        Mozc for Android now has more translations (d914458).
    Fixed issues:
        #187: build_mozc.py always generates 32 bit binaries on 64 bit OSX
        #327: Switch to Qt5 from Qt4
        #348: DirectWrite may fail to render text in certain enviromnents
        #391: ImportError: gen_zip_code_seed.py
        #399: OK/Cancel buttons on Mozc key binding editor dialog cannot be clicked on Windows
        #400: Close icon on GUI dialogs do not work on Windows
    Total commits:
        30 commits.

Summary of changes between 2.18.2613.102 and 2.19.2643.102 as follows.

    Third party libraries:
        protobuf: e8ae137 -> c44ca26
        Dropped dependency on fonttools
    Build related changes:
        --qtver=5 GYP build option is implicitly assumed on macOS and Linux builds (f76c304). On Windows, --qtver=4 is still the default.
    Major changes:
        Mozc for macOS now supports 10.12 as a runtime environment.
        Mozc for Android now uses on-device font to render keytop icons (f5dcad).
    Fixed issues:
        #263: Incorrect position in voiced sound marks on the key pad in Android
        #384: HUAWEI P9 lite does not show MozcView.
        #388: Having multiple abbreviation user dictionary entries with the same reading should be supported
        #389: Emoticon user dictionary entry should not be treated a content word
    Total commits:
        39 commits.

Summary of changes between 2.17.2532.102 and 2.18.2612.102 as follows.

    Third party libraries:
        protobuf: d5fb408 -> e8ae137
        GYP: e2e928b -> 4ec6c4e
        breakpad: d2904bb -> 85b27e4
        Dropped dependency on zlib
    Build related changes:
        Renamed src/mozc_version_template.txt to src/data/version/mozc_version_template.bzl
        Reference build environment now uses Ubuntu 14.04.5 (a7cbf72)
        Reference build environment now uses Ninja 1.7.1 (d2bc62b)
        Removed --android_compiler GYP option (5ce7fa6)
        Android build requires Android NDK r12b (5ce7fa6)
    Major changes:
        Improved Store Apps compatibility on Windows (0488082)
    Fixed issues:
        NPE in UserDictionaryToolActivity.onPostResume on Android (09b47c3)
        #273: Compilation errors in Android arm64 and mips64 build
        #373: Unexpected size bloat of the APK
        #374: Duplicate candidates after Undo
        #375: 90- is suggested from 090-
        #376: Suggestion-only user dictionary entry may not work
        #377: Abbreviation user dictionary entry may not work
        #378: Suppression word may not work
        #379: Single character noun user dictionary entry may not work
        #380: Dependency on dictionary/pos_matcher.h from session/session_server.cc is missing in GYP rules
        #382: Fix typo
    Total commits:
        84 commits.

Summary of changes between 2.17.2405.102 and 2.17.2531.102 as follows.

    Third party libraries:
        protobuf: 1a59a71 -> d5fb408
    Build related changes:
        Building Mozc for Windows requires Visual Studio 2015 update 3.
        --qtdir option is no longer supported in Linux desktop build (d003076).
    Major changes:
        Updated system dictionary.
        Removed several Shift-JIS-based normalizations on Windows (26241b0).
        Mozc for Windows requires SSE2 even on 32-bit environment.
        Mozc for Windows supports Windows 7 SP1 and later only.
        Mozc for macOS supports macOS 10.9 and later only.
        Mozc for desktop platforms (Windows, macOS, desktop Linux) supports Qt5 behind --qtver=5 GYP option.
    Fixed issues:
        Fix OOM when importing too large dictionary file on Android (5c859ae)
        #298: Fix NPE on Samsung devices on showing toast
        #315: Switch to Visual C++ 2015
        #372: Discontinue the support of Windows Vista
    Total commits:
        128 commits.

Summary of changes between 2.17.2355.102 and 2.17.2404.102 as follows.

    Third party libraries:
        protobuf: 172019c -> 1a59a71
    Build related changes:
        Building Mozc requires protobuf 3.0 or later.
        --android_stl GYP option is removed in Android build. You cannot use GNU STL to build Mozc for Android anymore.
    Major changes:
        None.
    Fixed issues:
        #369: Unexpected software keyboard layout can be chosen
        #370: Mozc keeps crashing on Android N Developer Preview 5
        #371: Shortcut word in personal dictionary should not be used for multi segment conversion
    Total commits:
        50 commits.

Summary of changes between 2.17.2323.102 and 2.17.2354.102 as follows.

    Third party libraries:
        None.
    Build related changes:
        None.
    Major changes:
        2.17.2323.102 and later commits in OSS repository preserve the original CL commit date in Google internal repository.
            Consider to specify --topo-order option to git log to see commits in the actual commit order.
        Multiple performance improvements in Android.
    Fixed issues:
        None.
    Total commits:
        32 commits.

Summary of changes between 2.17.2314.102 and 2.17.2322.102 as follows.

    Third party libraries:
        googletest: 1d53731 -> 82b11b8
        WTL: 9.0.4140 -> 9.1.5321
    Build related changes:
        Building macOS binaries now requires Ninja instead of xcodebuild.
    Major changes:
        None.
    Fixed issues:
        #247: Use ninja to build Mac binaries
        #355: Native resource leak due to the missing pthread_detach call in mozc::Thread::Detach
        #361: ImmSetCandidateWindow() with CFS_EXCLUDE isn't supported on Win Vista and Win7
    Total commits:
        15 commits.