Update to Asterisk 13.10.0:  this is mainly a bug fix release.
The Asterisk Development Team has announced the release of Asterisk 13.10.0.

The release of Asterisk 13.10.0 resolves several issues reported by the
community and would have not been possible without your participation.
Thank you!

The following are the issues resolved in this release:

Improvements made in this release:
-----------------------------------
 * ASTERISK-26088 - Investigate heavy memory utilization by
      res_pjsip_pubsub (Reported by Richard Mudgett)
 * ASTERISK-26011 - [patch]PJSIP: add "via_addr", "via_port",
      "call_id" to contacts (Reported by Alexei Gradinari)
 * ASTERISK-25994 - [patch]res_pjsip: module load priority
      (Reported by Alexei Gradinari)
 * ASTERISK-25931 - PJSIP: add "reg_server" to contacts. (Reported
      by Alexei Gradinari)
 * ASTERISK-25835 - Authentication using 'Username' field from
      Digest (Reported by Ross Beer)
 * ASTERISK-25930 - PJSIP: disable multi domain to improve realtime
      performace (Reported by Alexei Gradinari)

Bugs fixed in this release:
-----------------------------------
 * ASTERISK-26160 - pjsip: Updated->Reachable during qualify
      (Reported by Matt Jordan)
 * ASTERISK-26177 - func_odbc: Database handle is kept when it
      should be released (Reported by Leandro Dardini)
 * ASTERISK-26099 - res_pjsip_pubsub: Crash when sending request
      due to server timeout (Reported by Ross Beer)
 * ASTERISK-26141 - res_fax: fax_v21_session_new leaks reference to
      v21_details (Reported by Corey Farrell)
 * ASTERISK-26140 - res_rtp_asterisk: gcc 6 caught a
      self-comparison (Reported by George Joseph)
 * ASTERISK-26138 - chan_unistim:  Under FreeBSD, chan_unistim
      generates a compile error (Reported by George Joseph)
 * ASTERISK-26128 - Alembic scripts are failing (Reported by Mark
      Michelson)
 * ASTERISK-26139 - test_res_pjsip_scheduler:  Compile failure if
      pjproject isn't installed in a system location (Reported by
      George Joseph)
 * ASTERISK-26130 - [patch] WebRTC: Should use latest DTLS version.
      (Reported by Alexander Traud)
 * ASTERISK-26127 - res_pjsip_session: Crash due to race condition
      between res_pjsip_session unload and timer (Reported by Joshua
      Colp)
 * ASTERISK-26083 - ARI: Announcer channels staying around after
      playback to a bridge is finished (Reported by Per Jensen)
 * ASTERISK-26126 - [patch] leverage 'bindaddr' for TLS in
      http.conf (Reported by Alexander Traud)
 * ASTERISK-26069 - Asterisk truncates To: header, dropping the
      closing '>' (Reported by Vasil Kolev)
 * ASTERISK-26097 - [patch] CLI: show maximum file descriptors
      (Reported by Alexander Traud)
 * ASTERISK-25262 - Memory leak when a caller channel does multiple
      dials and CEL is enabled (Reported by Etienne Lessard)
 * ASTERISK-26092 - [Segfault] in res_rtp_asterisk.c:4268 after
      Remotely bridged channels (Reported by Niklas Larsson)
 * ASTERISK-26096 - res_hep: Crash when configuration file is
      missing (Reported by Niklas Larsson)
 * ASTERISK-26089 - Invalid security events during boot using PJSIP
      Realtime (Reported by Scott Griepentrog)
 * ASTERISK-26074 - res_odbc: Deadlock within UnixODBC (Reported by
      Ross Beer)
 * ASTERISK-26054 - Asterisk crashes (core dump) (Reported by B.
      Davis)
 * ASTERISK-24436 - Missing header in res/res_srtp.c when compiling
      against libsrtp-1.5.0 (Reported by Patrick Laimbock)
 * ASTERISK-26091 - [patch] ar cru creates warning, instead use ar
      cr (Reported by Alexander Traud)
 * ASTERISK-26070 - ari/channels:  Creating a local channel without
      an originator adds all audio formats to it's capabilities
      (Reported by George Joseph)
 * ASTERISK-26078 - core: Memory leak in logging (Reported by
      Etienne Lessard)
 * ASTERISK-26065 - chan_pjsip: MWI NOTIFY contents not ordered
      properly (Reported by Ross Beer)
 * ASTERISK-26063 - ${PJSIP_HEADER(read,Call-ID)} does not work -
      documentation needs clarification for when read/write is
      possible (Reported by Private Name)
 * ASTERISK-25777 - data race in threadpool (Reported by Badalian
      Vyacheslav)
 * ASTERISK-26038 - 'make install' doesn't seem to install OS/X
      init files (Reported by Tzafrir Cohen)
 * ASTERISK-26029 - parking: ast_parking_park_call should return
      parking_space instead of parking_exten (Reported by Diederik de
      Groot)
 * ASTERISK-25938 - res_odbc: MySQL/MariaDB statement
      LAST_INSERT_ID() always returns zero. (Reported by Edwin
      Vandamme)
 * ASTERISK-25941 - chan_pjsip: Crash on an immediate SIP final
      response (Reported by Javier Riveros )
 * ASTERISK-26014 - res_sorcery_astdb: Make tolerant of unknown
      fields (Reported by Joshua Colp)
 * ASTERISK-24986 - keepalive INFO packages ignored by asterisk
      (Reported by Ilya Trikoz)
 * ASTERISK-26034 - T.38 passthrough problem behind firewall due to
      early nosignal packet (Reported by George Joseph)
 * ASTERISK-26030 - call cut because of double Session-Expires
      header in re-invite after proxy authentication is required
      (Reported by George Joseph)
 * ASTERISK-25964 - Outbound registrations created via ARI/push
      configuration do not clean up outbound registrations currently
      in flight (Reported by Matt Jordan)
 * ASTERISK-26005 - res_pjsip: Multiple SIP messages are combined
      into 1 TCP packet (Reported by Ross Beer)
 * ASTERISK-25352 - res_hep_rtcp correlation_id is different then
      res_hep (Reported by Kevin Scott Adams)
 * ASTERISK-26008 - app_followme does not delete recorded name
      prompt (Reported by Tzafrir Cohen)
 * ASTERISK-26007 - res_pjsip: Endpoints deleting early after
      upgrade from 13.8.2 to 13.9 (Reported by Greg Siemon)
 * ASTERISK-25990 - PJSIP TLS registration should respect
      client_uri scheme when generating Contact URI (Reported by
      Sebastian Damm)
 * ASTERISK-25978 - res_pjsip_authenticator_digest: Should not use
      source port in nonce verification (Reported by Mark Michelson)
 * ASTERISK-25993 - pjproject: Allow bundling to not require
      everything it does (Reported by Joshua Colp)
 * ASTERISK-25956 - Compilation error in conditionally compiled
      code in config_options.c (Reported by Chris Trobridge)
 * ASTERISK-25998 - file: Crash when using nativeformats (Reported
      by Joshua Colp)
 * ASTERISK-25826 - PJSIP / Sorcery slow load from realtime
      (Reported by Ross Beer)
 * ASTERISK-25968 - pjproject_bundled:  Configure and make need to
      be re-tested (Reported by George Joseph)
 * ASTERISK-24463 - Voicemail email address corrupt or not sent
      when message is in the process of being recorded during reload
      (Reported by John Campbell)
 * ASTERISK-25970 - Segfault in pjsip_url_compare (Reported by
      Dmitriy Serov)
 * ASTERISK-25963 - func_odbc requires reconnect checks for stale
      connections (Reported by Ross Beer)
 * ASTERISK-25961 - tests/channels/SIP/sip_tls_call: Sporadic crash
      when running test (Reported by Joshua Colp)
 * ASTERISK-16115 - [patch] problem with ringinuse=no, queue
      members receive sometimes two calls (Reported by nik600)
 * ASTERISK-25917 - [patch]app_voicemail: passwordlocation=spooldir
      only works if you manually add secret.conf yourself (Reported by
      Jonathan R. Rose)
 * ASTERISK-25950 - [patch]SIP channel does not send PeerStatus
      events for autocreated peers (Reported by Kirill Katsnelson)
 * ASTERISK-25954 - Manager QueueSummary and QueueStatus Actions
      are case sensitive to QueueName (Reported by Javier Acosta)

New Features made in this release:
-----------------------------------
 * ASTERISK-25904 - PJSIP: add contact.updated event (Reported by
      Alexei Gradinari)

For a full list of changes in this release, please see the ChangeLog:

http://downloads.asterisk.org/pub/telephony/asterisk/ChangeLog-13.10.0

Thank you for your continued support of Asterisk!