py-test-cov: updated to 2.7.1
2.7.1:
* Fixed source distribution manifest so that garbage ain't included in the tarball.

2.7.0:
* Fixed AttributeError: 'NoneType' object has no attribute 'configure_node' error when --no-cov is used.
* Various testing and CI improvements.
* Improved documentation regarding subprocess and multiprocessing.
* Improved pytest_cov.embed.cleanup_on_sigterm to be reentrant (signal deliveries while signal handling is
  running won't break stuff).
* Added pytest_cov.embed.cleanup_on_signal for customized cleanup.
* Improved cleanup code and fixed various issues with leftover data files.
* Improved examples. Now there are two examples for the common project layouts, complete with working coverage
  configuration. The examples have CI testing.
* Improved help text for CLI options.