www/ruby-rails70: update to 7.0.8
pkgsrc change: fix dependency of ruby-activestorage70

Active Support

* Fix TimeWithZone still using deprecated #to_s when ENV or config to
  disable it are set.  (Hartley McGuire)

* Fix CacheStore#write_multi when using a distributed Redis cache with a
  connection pool.  Fixes #48938.  (Jonathan del Strother)

Active Record

* Fix change_column not setting precision: 6 on datetime columns when using
  7.0+ Migrations and SQLite.  (Hartley McGuire)

* Fix unscope is not working in specific case

    Before:

    Post.where(id: 1...3).unscope(where: :id).to_sql # "SELECT `posts`.* FROM `posts` WHERE `posts`.`id` >= 1 AND `posts`.`id` < 3"

    After:

    Post.where(id: 1...3).unscope(where: :id).to_sql # "SELECT `posts`.* FROM `posts`"

 Fixes #48094.  (Kazuya Hatanaka)

* Fix associations to a STI model including a class_name parameter

    class Product < ApplicationRecord
      has_many :requests, as: :requestable, class_name: "ProductRequest", dependent: :destroy
    end

    # STI tables
    class Request < ApplicationRecord
      belongs_to :requestable, polymorphic: true

      validate :request_type, presence: true
    end

    class ProductRequest < Request
      belongs_to :user
    end

Accessing such association would lead to:

    table_metadata.rb:22:in `has_column?': undefined method `key?' for nil:NilClass (NoMethodError)

  (Romain Filinto)

* Fix change_table setting datetime precision for 6.1 Migrations
  (Hartley McGuire)

* Fix change_column setting datetime precision for 6.1 Migrations
  (Hartley McGuire)

Action View

* Fix form_for missing the hidden _method input for models with a namespaced
  route.  (Hartley McGuire)

* Fix render collection: @records, cache: true inside jbuilder templates

  The previous fix that shipped in 7.0.7 assumed template fragments are
  always strings, this isn't true with jbuilder.  (Jean Boussier)


Action Pack

* Fix HostAuthorization potentially displaying the value of the
  X_FORWARDED_HOST header when the HTTP_HOST header is being blocked.
  (Hartley McGuire, Daniel Schlosser)

Active Job

* Fix Active Job log message to correctly report a job failed to enqueue
  when the adapter raises an ActiveJob::EnqueueError.  (Ben Sheldon)

Railties

* Omit webdrivers gem dependency from Gemfile template (Sean Doyle)