anope: Build fix: Don't check for presence of epoll header on SunOS
In file included from /home/pbulk/build/chat/anope/work/anope-2.0.7-source/src/socketengines/socketengine_epoll.cpp:18:0:
/usr/include/sys/epoll.h:1:2: error: #error "This header has been disabled to stop its functionality from being used."
 #error "This header has been disabled to stop its functionality from being used."
  ^~~~~
/home/pbulk/build/chat/anope/work/anope-2.0.7-source/src/socketengines/socketengine_epoll.cpp:23:20: error: 'epoll_event' was not declared in this scope