py-google-auth: update to 2.19.1.
Bug Fixes

    Check id token error response (#1315) (2a71f7b)
    Fix "AttributeError: 'str' object has no attribute 'get'" (dac7cc3)

Documentation

    Replacing abc.com with example.com (dac7cc3)