py-zeroconf: updated to 0.28.5
0.28.5
Enabled ignoring duplicated messages which decreases CPU usage, thanks to J. Nick Koston.
Fixed spurious AttributeError: module 'unittest' has no attribute 'mock' in tests.