monit: Update to 5.35.2
Changes:
Version 5.35.2
Fixed: Monit may skip the sleep altogether and perform checks in a
tight loop when many "check program" tests are used in conjunction with
the short poll cycle.

Version 5.35.1
Fixed: Issue #1127: Monit may crash when "check program" is used.

Version 5.35.0
Fixed: Monit may hang on exit, if a program executed by "check program"
was pending while monit tried to quit (regression from Monit 5.34.1).
Fixed: Issue #484: The pidfile based process check may not work
properly on platforms that assign PID to threads (LWPs), such as Linux.
When the process with the given PID stopped, but the same PID was assigned to
the LWP, Monit reported the process as running (which is wrong) and
logged the following error:
 "failed to get service data" The service status displayed
the process as OK but showed no process statictics.
Fixed: When the pidfile was updated (e.g. process restarted), Monit was
still monitoring the previous PID. If the PID was reassigned to
different process or thread (LWP),
Monit wasn't able to detect that the process is not running.
Fixed: Issue #1115: Service checks may sporadicaly hang if the PID is
recycled by the system quickly, e.g. due to PID randomization
(regression from Monit 5.34.1).
Fixed: Issue #1121: The "set mailserver" timeout option allowed to only
increase the network timeout. Values lower then 30 seconds were
ignored.
Fixed: Issue #1122: Monit hangs with high CPU usage if the
"set daemon <seconds>" is set to >= 2148 seconds.
Fixed: Issue #1126: Monit with LibreSSL: The secure connection shutdown
may hog the CPU for up to connection timeout (5s by default).
Fixed: Monit HTTP interface didn't parse the password file (regression
from monit 5.34.4). Thanks to Francisco Javier Felix Belmonte.
Fixed: MacOS: When "check network" is used, but no network interfaces
are found, monit terminates with "AssertException: nbytes > 0  raised
in Mem_calloc"
Fixed: The loadavg test in the process check context didn't work. Error
like this was logged by monit each time the test was executed:
'myservice' error -- unknown resource ID: [5]
Fixed: MacOS + DragonflyBSD + FreeBSD + NetBSD + OpenBSD: If there are
no mounted filesystems and a "check filesystem" is used, monit would
terminate with
"AssertException: count > 0 raised in Mem_calloc"
Fixed: FreeBSD + OpenBSD + NetBSD: Detect presence of backtrace()
function during compilation (used in monit -vv mode to print backtrace)
Fixed: MacOS: Monit may stop handling signals (SIGCHLD for children,
SIGTERM to exit, SIGHUP for reload, SIGUSR1 for wakeup)
Fixed: If Monit detects syntax errors in the configuration file, log an
error message prior to exiting the program.
Fixed: Allow to stop Monit if it is in the middle of secure connection
with read/write retries.
New: Add the following headers to email alerts, to prevent
out-of-office autoresponders in Exchange, Outlook, Office365, Gmail:
 "X-Auto-Response-Suppress: All"
 "Precedence: Bulk"
New: When monit aborts (e.g. due to assert), print a backtrace.

Version 5.34.4
Fixed: If the Monit configuration file contains a string with
unbalanced escape sequences, Monit may crash upon startup.
Fixed: If the password in the "set mmonit" URL contains only binary
characters, syntax check passed (-t), but Monit aborts after start and
reports following error:
 AssertException: n >= 0
  raised in Str_ndup at src/util/Str.c:315
 Aborted
Fixed: If the "every <cron>" statement contained a syntax error, syntax
check passed (-t), but Monit aborts after start and reports following
error:
 AssertException: n < 5 && n >= 0
  raised in Time_incron at src/system/Time.c:1566
 Aborted
Fixed: If the timeout option value was set to 0, the syntax check was
successful (-t), but Monit aborts after starting and reports the
following error:
 AssertException: timeout > 0
  raised in Socket_create at src/net/socket.c:319
 Aborted
Fixed: The "set syslog" statement's "facility" option did not permit
the specification of the "log_user". Thanks to Lutz Mader for report.
Fixed: Double interpretation of format strings during RETHROW

Version 5.34.3
Fixed: If the ping statement did not explicitly specify an outgoing
address but a previous ping statement did, the same address was shared
by both statements.
Fixed: Monit may crash upon stopping if the ping statement is used in
conjunction with the address option.
Fixed: If a directory is set in the 'allow' option of the 'set httpd'
statement, instead of file or string, Monit hangs on start.

Version 5.34.2
Fixed: Network protocol test may sporadically fail with "Poll failed:
Interrupted system call" error.

Version 5.34.1
Fixed: The "check program" no longer keeps the zombie process between
cycles.

Version 5.34.0

New: Added the "timeout" option to the exec action. It can be set
either globally (in the "set limit" statement using the "execTimeout"
option) or locally (using the "timeout <number> seconds" in the exec
action). The default timeout is 0 (no limit), to keep the original
behaviour. Thanks to Lutz Mader.
New: Issue #1074: Added a hardlink test to file, directory and fifo
checks. Thanks to Lutz Mader. Example:
 check directory upload with path /data/upload
  if hardlink > 32000 then alert
New: Issue #1070: Added the system boot time and uptime to the XML
interface. Thanks to Lutz Mader.
New: Added support to add Monit to M/Monit hostgroup. Example:
 set mmonit
     https://monit:mypassword@mmonit.foo.bar:8443/collector
     with hostgroups [ Oslo, "Mail servers" ]
New: Add support for checking the output of a program for changes. This can be used to alert on changes of system
properties, e.g. 'ip route' or 'udisksctl status'. Thanks to Christian Goettsche. Example:
    check program myscript with path /usr/local/bin/myscript.sh
        if content changed then alert
        if content not changed then alert else ignore
New: Implemented 'ignore' functionality within the test success action, enabling the suppression of alerts when the
     check returns to a successful state. Thanks to Christian Goettsche.
New: Set the header X-Content-Type-Options to prevent MIME type
sniffing. Thanks to Christian Goettsche.
New: Added support for debugging TLS/SSL connections with Wireshark. It
is now possible to set the SSLKEYLOGFILE=<path> environment variable
when starting Monit, to log the master secret to a file, which can be
used by Wireshark in "Settings -> Protocols -> TLS ->
(Pre)-Master-Secret log filename".  Note: The SSLKEYLOGFILE
functionality is enabled only in the monit debug mode (when monit was
started with the -v option).
Fixed: Issue #1082: Wrong error message for the uptime test. Thanks to Lutz Mader.
Fixed: Disable SSL session renegotiation in the Monit HTTP interface (CVE-2011-1473).
Fixed: Monit reported wrong number of CPUs in the VMWare virtual host in Debian 12.x
Fixed: Issue #1086: The HTTP protocol test may return false error
"HTTP error: invalid chunk size" if the HTTP response contained header with
more then 511 bytes. We have increased the limit to 8192 bytes per
header and will report "response header exceeded maximum size" error if
the HTTP response contains longer header.
Fixed: When the monit ID is generated in first start and the system is
shut down before the file was stored to the filesystem, an empty
monitid file may be created. Thanks to Alexander Dahl for fix.
Fixed: The SSL connection can be sporadically interrupted.
Fixed: Issue #1101: Updated configuration examples for PAM in the Monit
manual. Thanks to Lutz Mader.
Fixed: The network test was failing on WSL (Windows subsystem for Linux).
Fixed: Make network interface speed statistics optional (monit used to
report link failure when statistics were not available) and do not
report/check if statistics are not available.