Fix install directory issue PR pkg/54183, thanks wiz@ and leot@ for review
	Install destination inconsistency if PKG_REVISION is set.
	The part of error message looks as:

	ERROR: The following files are in the PLIST but not in /W/devel/rubymine-bin/work/.destdir/usr/pkg:
	ERROR:         /W/devel/rubymine-bin/work/.destdir/usr/pkg/${PKGNAME_NOREV}/Install-Linux-tar.txt
	       .....
	       ....
	ERROR: ************************************************************
	ERROR: The following files are in /W/devel/rubymine-bin/work/.destdir/usr/pkg but not in the PLIST:
	ERROR:         /W/devel/rubymine-bin/work/.destdir/usr/pkg/rubymine-bin-2018.3.5nb1/Install-Linux-tar.txt