cbindgen: downgrade to 0.29.2
0.29.4 breaks firefox build:
build/dist/include/mozilla/webrender/webrender_ffi_generated.h:6705: error: 'COUNT' was not declared in this scope