Update py-gevent to 1.0.2:
Tests don't run through because of

===> Testing for py27-gevent-1.0.2
Traceback (most recent call last):
  File "testrunner.py", line 2, in <module>
    import six
  File "/scratch/net/py-gevent/work/gevent-1.0.2/greentest/six.py", line 2, in <module>
    from gevent.hub import PY3
ImportError: No module named gevent.hub
*** Error code 1


Release 1.0.2
-------------

- Fix LifoQueue.peek() to return correct element. PR #456. Patch by Christine Spang.
- Upgrade to libev 4.19
- Remove SSL3 entirely as default TLS protocol
- Import socket on Windows (closes #459)
- Fix C90 syntax error (PR #449)
- Add compatibility with Python 2.7.9's SSL changes. Issue #477.