sysutils/py-Glances: Update to 4.1.2
Changes since 4.1.1:

===============
Version 4.1.2
===============

Bug corrected:

*  AttributeError: 'CpuPercent' object has no attribute 'cpu_percent' #2859