gexiv2: lower C++ standard from C++17 to C++11
gexiv2 requests C++17 by default in it's meson.build, but it depends on
graphics/exiv2 whose public headers are not C++17 compliant since they make
use of std::auto_ptr:

graphics/gexiv2/work/.buildlink/include/exiv2/tags.hpp:143:17: error: no template named 'auto_ptr' in namespace 'std'; did you mean simply 'auto_ptr'?