tex-babel-greek: update to 1.15
Improve the handling of font encodings with 8-bit TeX:

Switch to the previous \encodingdefault (not \cf at encoding) when
exiting Greek text parts.
Exception: use \latinencoding if the initial \encodingdefault
is LGR and “greek” is the main document language.

Fix standard accent macros with pre-2022 \MakeUppercase.
Rename modifier "local-MakeUppercase-fixes" to
"no-MakeUppercase-fixes".