graphics/vv: Turn off -march=native that is enabled by default
-march=native is bad for binary packages. Also it causes a build failure on
NetBSD/aarch64, perhaps because /proc/cpuinfo isn't 100% compatible with
that of Linux?

> /usr/pkgsrc/graphics/vv/work/vv-84747114964a84aa7b9f1495cfc580b98817fac2/src/uti
> l/TonemapperAgx.cpp: In function 'float ToneMap::AgxCurve(float)':
> /usr/pkgsrc/graphics/vv/work/vv-84747114964a84aa7b9f1495cfc580b98817fac2/src/uti
> l/TonemapperAgx.cpp:12:7: error: '+nofp' feature modifier is incompatible with t
> he use of floating-point types
>    12 | float AgxCurve( float x )
>       |       ^~~~~~~~