Upgrade mailman to 2.1.8rc1, fix a cross-site scripting issue.
pkgsrc changes:
- install the admin/www/mailman-*.{pdf,ps,txt} documentation file, and
  change MESSAGES to point to mailman-install.txt
changes between 2.1.7 and 2.1.8rc1:
- A cross-site scripting hole in the private archive script of 2.1.7
  has been closed.  Thanks to Moritz Naumann for its discovery.
- Bouncers support added: 'unknown user', Microsoft SMTPSVC, Prodigy.net
  and several others.
- Updated email library to 2.5.7 which will encode payload into qp/base64
  upon setting.  This enabled backing out the scrubber related patches
  including 'X-Mailman-Scrubbed' header in 2.1.7.
- Fix SpamDetect.py potential hold/reject loop problem.
- A warning message from email package to the stderr can cause error
  in Logging because stderr may be detached from the process during
  the qrunner run.  We chose not to output errors to stderr but to
  the logs/error if the process is running under mailmanctl subprocess.
- DKIM header cleansing was separated from Cleanse.py and added to
  -owner messages too.
- Fixes: Lose Topics when go directly to topics URL (1194419).
  UnicodeError running bin/arch (1395683).  edithtml.py missing import
  (1400128).  Bad escape in cleanarch.  Wrong timezone in list archive
  index pages (1433673).  bin/arch fails with TypeError (1430236).
  Subscription fails with some Language combinations (1435722).
  Postfix delayed notification not recognized (863989).  2.1.7 (VERP)
  mistakes delay notice for bounce (1421285).  show_qfiles: 'str'
  object has no attribute 'as_string' (1444447).  Utils.get_domain()
  wrong if VIRTUAL_HOST_OVERVIEW off (1275856).