doxygen: updated to 1.9.5
Release 1.9.5

Bug fixes

issue 3165: EXPAND_ONLY_PREDEF neglected within function macro expansions (Origin: bugzilla 559489)
Macros listed with EXPAND_AS_DEFINED were not recursively expanded
issue 8215: missing lang attribute and meta description for SEO
issue 9016: Support collapsible sections in markdown
issue 9047: Support @param-taint in PHP (permit dashes in command aliases?)
issue 9096: Call Graph corrupt and/or incomplete (2)
issue 9236: doxygen x_noenv should always diff system-dependent settings
issue 9309: Colon on a line by itself
issue 9312: Build: cache.h:53:14: error: 'exchange' is not a member of 'std'
issue 9317: File-scoped Namespaces in C
issue 9319: Doc build fails with cairo 1.17.6
issue 9344: Long bibliography entry looks bad
issue 9352: Qt Q_GADGET macro is not supported
issue 9362: Doxyfile environment/quote mishandling in list values
issue 9367: Current git master does not honor PROJECT_NUMBER in LaTeX
issue 9378: Dollar Sign Escape Sequence Ignored in Markdown Backtick Syntax (Inline Code)
issue 9394: Request: Show C++ default member values when INLINE_SIMPLE_STRUCTS=YES
issue 9399: XML / perlmod fortran output, the type of a parameter of a function is set to the name of the parameter
issue 9409: Error-message and Line-Number is NOT related to document
issue 9417: Java: Issue with static initializer if no space after static
issue 9427: Enhance documentation for filter commands
issue 9430: HTML layout: a full sidebar overlaps with breadcrumbs
issue 9440: Fix search label regression
issue 9476: fatal: Cannot open 'doxygen/graph_legend.dox': No such file or directory
issue 9500: No output when run doxygen in high level directory
issue 9515: Function return value problem
issue 9520: Rest of file silently ignored after a certain string literal [PHP]
issue 9386: Problems with the directory dependency graph
bug 531817 Python: Backslash prevent showing the proper preview
bug 539818 C Preprocessor enum printing trick not handled properly by Doxygen
bug 642168 C "here-docs" not correctly parsed
bug 786576 regression with ALIASES or image latex interpretation
bug_572042 ingroup does not allow multiple groupnames
bug_751023 Predefined macros are handled incorrectly in source browser
Fixed javascript issue in menu.js causing invalid XHTML output
Fixed parsing issues with the XHTML output due to the use of &nbsp;
FileInfo::isSymLink() did not work correctly
Files Quick Link results in a non existing page
Added guard to prevent stack overflow in hasNonReferenceSuperClass()
Give markdown verbatim and fenced code blocks their own command.
No click possible on chapters in doxygen's CHM documentation

Features

Add support for Dark theme (set via HTML_COLORSTYLE with setting DARK, LIGHT, AUTO_DARK, AUTO_LIGHT and TOGGLE).
Original issue 8404: Dark theme
New options DOt_COMMON_ATTR, DOT_EDGE_ATTR, and DOT_NODE_ATTR to configure dot graph, nodes and arrows attributes
New option INPUT_FILE_ENCODING to specify input encoding based on a file pattern
New option FORTRAN_COMMENT_AFTER to configure the fixed format comment start position (default 72).
Added new commands \fileinfo and \lineinfo to show the current file and line.
See issue 7046: Add filename and line number support to tags, ala __FILE__ and __LINE__ macros
Add support for \showdate command
Allow empty HTML <div/> and <span/> tags
Handling of `@...@` setting with `doxygen -x_noenv`
Recognizing and name of implicit Fortran [programs
Support HTML stylesheets on the Internet
Issue 9415: fixed format source with wide lines
End of "here document" can be indented
Portuguese and Czech translators updated to 1.9.4.
issue 9444: Upgrade jQuery UI to latest 1.13 release to get rid of security issues

Improved user feedback

Commented function list marcro gives warning
Correction of line counting
Documenting parameter of function without parameters
Warning about non closed (nested) comment
Friendly message on incorrect input
Make directory traversal more robust for errors (e.g. broken symlinks)

Deprecated functionality

With the new dark mode color style the FORMULA_TRANSPARENT and DOT_TRANSPARENT have become obsolete. Pictures always have a transparent background now.
The specific options DOT_FONTNAME and DOT_FONTSIZE have been replaced be more generic options DOT_COMMON_ATTR, DOT_EDGE_ATTR, and DOT_NODE_ATTR that can be used to customize the way dot images are rendered. When upgrading the Doxyfile (using doxygen -u) the existing values of DOT_FONTNAME and DOT_FONTSIZE will be migrated.

Refactoring and cleanup

Dependency between examples.
Enabling include files for lex files
Enabling dependencies for include files in lex files
Fix handling of PUBLIC/PRIVATE for procedures in Fortran
Fix regressions introduced by changing the way references are resolved
Fixes: also allow ; and space as attribute separator
Implementation of lineBreak and nonBreakingSpace in docbook
Improve test for fortran public/private handling
Improvement of HTML documentation section
Incorrect determination of sub-sections for index.
Incorrect name lex state name used
Making example configurations consistent
Missing possibility for Element 'compounddef', attribute 'language'
More translation tweaks
Performance tweaks to speed up processing
Prohibit in-place doxygen builds
Refactoring and fixes
Refactoring: Automatically replace incorrect formula.repository
Refactoring: optimize FileDef::isDocumentationFile() method
Refactoring: optimize guessSection routine
Refactoring: reimplement getDefs using symbol resolver
Refactoring: replace left(n)/right(n) by startsWith/endsWith
Refactoring: use std::variant for Indices
Refactoring: use std::variant to switch between search indices
Remember position of collapse/expand across pages
Remove dead-code statement as found by coverity
Remove unused Validate debug option
Replacing the list of HTML / XML commands by tables
Restructure build rule to improve readability and remove duplication
Small spelling correction in doxygen usage
Test Fortran inheritance over modules
Use lower().str() to map Fortran identifier
Workaround for DEPFILE
Workaround for XHTML not supporting <picture>
fix shabang
python: do not use tabs for indentation
unset executable flag