rust: work around panic when building as non-root
During the bootstrap it seems to copy everything under $PREFIX/lib to a
staging area for some reason. This is not ideal because it may lead to
circumvention buildlink3's intents. But more urgent is that it breaks
non-root builds if there are unreadable files (e.g. setuid binaries)
installed by other packages. Skip such files.

Thread 'main' panicked at src/bootstrap/src/lib.rs:1816:17:
failed to copy `/usr/pkg/lib/polkit-1/polkit-agent-helper-1` to `/tmp/pkgsrc-obj/lang/rust/work/rustc-1.90.0-src/build/aarch64-unknown-netbsd/stage0-sysroot/lib/polkit-1/polkit-agent-helper-1`: Permission denied (os error 13)