boost: updated to 1.68.0
1.68.0:
New Libraries
YAP:
An expression template library for C++14 and later, from Zach Laine.

Updated Libraries
Beast:
This version fixes a missing executor work guard in all composed operations used in the implementation. Users who are experiencing crashes related to asynchronous completion handlers are encouraged to upgrade.
For a complete list of changes, please view the official Release Notes.
Context:
78: Linker error with context-impl=ucontext: multiple definition of boost::context::detail::current_rec
Coroutine2:
14: crash while stack unwinding
18: some guidance on why to use coroutine2
20: failes to compile test in due to the error C2039
22: undefined behaviour documentation
Fiber:
170: buffered_channel::try_push has incorrect documentation
172: WIN64: 'invalid conversion from 'HANDLE' to 'std::thread::native_handle_type' errors for builds using mingw-w64
175: throw exception "Operation not permitted"
NUMA support moved to extra library (fiber-numa); enabled via property numa (numa=on)
Fusion:
Added a workaround for ambiguous call of fusion::deque constructor on GCC 4.4/c++0x
Fixed a bug with C-style array
Fixed a fusion::for_each signature to take functor by value
This may break existing code with non-copyable (non-movable) functor, but the implementation wasn't correct for a long time; the documantation was correct from the first. So, please make sure your usage.
Fixed unintentional MPL placeholder substituion bug on fusion::transform.
Moved description, how to conform Fusion sequence as MPL sequence, to mpl section.
Added notes regarding IO facility for adapted type.
Geometry:
Improvements
469 Horizontal grid shift (nadgrids) in SRS transformations (undocumented for now due to potential interface changes).
478 Box-Segment distance for spherical and geographic coordinate systems.
487 Missing combinations of geometries in distance for spherical and geographic cs
489 Additional direct geodesic problem formulas for internal use
Solved issues
470 Assertion failure with short spherical and geographic segments.
471 Invalid envelope of spherical polygon
498 Unexpected results with expand() and make_inverse() for spherical and geographic CS
Bugfixes
488 Handle non-true-references in closing_iterator and ever_circling_range_iterator
495 VxWorks 7 cross-compilation issue.
GIL:
The I/O extensions have been entirely rewritten.
The library now requires a C++11-compliant compiler.
Documentation has been reformatted and updated.
Graph:
Conditionally replace deprecated/removed C++98 std::bind1st by std::bind, std::auto_ptr by std::unique_ptr, and std::random_shuffle by std::shuffle.
Fix compiler error with release builds on VS2015
Fix the Stanford GraphBase examples
Fix friend declarations for iterator_core_access
Add missing <boost/iterator.hpp> include
Avoid an unused variable warning
Fix some typos in documentation
Fix some issues in tests and examples
Lexical Cast:
Fixes for clang-tidy warnings 12092
Log:
Improved support for VxWorks.
Save and restore ebx register on x86 PIE targets in the dump stream manipulator implementation.
Math:
Support for arbitrary precision complex valued quadrature and hence contour integration
Improve performance of polynomial addition
Math:
Continue to improve numerical integration routines, and in particular add support for contour integrals.
Improve accuracy of erfc function's rational approximations.
Multi-index Containers:
Containers of moveable but non-copyable elements can now be serialized (ticket 13478). Thanks to Sébastien Paris for the report.
multi_index_container's default constructor is no longer explicit (ticket 13518).
Multiprecision:
Support for multiprecision complex numbers
Multiprecision:
Support added for complex multiprecision numbers.
Changed conversion to unsigned integer types to be truncating to match standard defined behaviour.
Correct bug in MPFR string formatting.
Fix undefined behaviour in cpp_dec_float conversion from long long.
Add support for Eigen interoperability.
float128.hpp: Fix Intel on Windows build.
Fix type used in temporaries when expanding expression templates containing mixed expressions.
Fix infinite loop in gmp_float to fixed-point string conversion.
Update the expression templates to issue static_asserts with better error messages when you try and do something unsupported.
Fix bug in cpp_int where incrementing to zero doesn't set the sign correctly.
Remove erroneous use of std::move, and rely on NVRO instead.
Fix up support for changes to MPIR-3.0.
Fix various conversion errors in cpp_bin_float when the exponent type is a long long, or else we're converting to an integer that is wider than we are.
Fix compatibility issue with GCC-8 caused by the introduction of std::byte.
Optional:
Added member function has_value() for compatibility with std::optional (issue 52).
Added member function map() for transforming optional<T> into optional<U> using a function of type T -> U.
Added member function flat_map() for transforming optional<T> into optional<U> using a function of type T -> optonal<U>.
Predef:
Add support for __ARM_ARCH macro.
Add detection for PTX architecture.
Add nvcc compiler detection.
Add support for detecting CUDA.
Remove reference to obsolete BOOST_ARCH_AMD64.
Program Options:
Support for multiple long names for an option, thanks to Eyal Rozenberg
Python:
Bug fixes to correct autolink support (Windows)
Rational:
Fixed undefined behavior in normalize()
System:
Add constexpr to error_code and error_condition members under C++14 and above
Signals:
Removal Notice: Boost.Signals will be removed in the next release. Boost.Signals was deprecated in version 1.54.0. Transition to Boost.Signals2 now to avoid disruption.
Stacktrace:
Fixed compilation on Solaris and other platforms that do qualify address as const in dladdr function (github 54).
Dropped dependency on Boost.LexicalCast.
Test:
Boost.test v3.8 see the Changes log for more details.
Breaking changes
The master_test_suite_t object is no more copyable
New feature:
Dataset test case can now use command line parameters
TypeIndex:
Dropped dependency on Boost.MPL.
Uuid:
Breaking change: sha1 detail namespace header redirection for backwards compatibility was removed
Added support for std::hash
Added support for move semantics on random generators
Properly handle EINTR when acquiring entropy
Use getrandom(2) instead of getentropy(3) on linux