Update libssh2 to 1.7.0.
 Changes:

    libssh2_session_set_last_error: Add function
    mac: Add support for HMAC-SHA-256 and HMAC-SHA-512
    WinCNG: support for SHA256/512 HMAC
    kex: Added diffie-hellman-group-exchange-sha256 support
    OS/400 crypto library QC3 support

Bug fixes:

    diffie_hellman_sha256: convert bytes to bits CVE-2016-0787
    SFTP: Increase speed and datasize in SFTP read
    openssl: make libssh2_sha1 return error code
    openssl: fix memleak in _libssh2_dsa_sha1_verify()
    cmake: include CMake files in the release tarballs
    Fix builds with Visual Studio 2015
    hostkey.c: Fix compiling error when OPENSSL_NO_MD5 is defined
    GNUmakefile: add support for LIBSSH2_LDFLAG_EXTRAS
    GNUmakefile: add -m64 CFLAGS when targeting mingw64
    kex: free server host key before allocating it (again)
    SCP: add libssh2_scp_recv2 to support large (> 2GB) files on windows
    channel: Detect bad usage of libssh2_channel_process_startup
    userauth: Fix off by one error when reading public key file
    kex: removed dupe entry from libssh2_kex_methods
    _libssh2_error: Support allocating the error message
    hostkey: fix invalid memory access if libssh2_dsa_new fails
    hostkey: align code path of ssh_rsa_init to ssh_dss_init
    libssh2.pc.in: fix the output of pkg-config --libs
    wincng: fixed possible memory leak in _libssh2_wincng_hash
    wincng: fixed _libssh2_wincng_hash_final return value
    add OpenSSL 1.1.0-pre2 compatibility
    agent_disconnect_unix: unset the agent fd after closing it
    sftp: stop reading when buffer is full
    sftp: Send at least one read request before reading
    sftp: Don't return EAGAIN if data was written to buffer
    sftp: Check read packet file offset
    configure: build "silent" if possible
    openssl: add OpenSSL 1.1.0-pre3-dev compatibility
    GNUmakefile: list system libs after user libs