Update to 6.0.1.1
* Fix build with GCC 6.4 (PostgreSQL part)

Changelog:
Bugs fixed compared to 6.0.0 RC3:
    deb#887593 add #include <abstractions/X> to oosplash apparmor profile [Vincas Dargis, Rene Engelhard]
    ofz#4728 bad-cast [Caolán McNamara]
    ofz#4753 bad-cast [Caolán McNamara]
    ofz#4767 bad-cast [Caolán McNamara]
    ofz#4817 bad-cast [Caolán McNamara]
    ofz#4848 bad-cast [Caolán McNamara]
    ofz#4872 bad-cast [Caolán McNamara]
    ofz#4971 bad-cast [Caolán McNamara]
    ofz#5007 bad-cast [Caolán McNamara]
    ofz#5235 bad-cast [Caolán McNamara]
    ofz#5254 bad-cast [Caolán McNamara]
    ofz#5435 sw: fix SwCache::Insert() stale pointers [Michael Stahl]
    ofz#5447 on plcf save force current Fkp to stick in cache [Caolán McNamara]
    ofz#5477 if the para is already oversize, nums would go negative [Caolán McNamara]
    ofz#5535 max decimal places for rtl_math_round is 20 [Caolán McNamara]
    ofz#5747 short->sal_Int32 like in StgDataStrm [Caolán McNamara]
    ofz#5909 bad-cast [Caolán McNamara]
    ofz#6064 bad-cast [Caolán McNamara]
    rhbz#1367846 Scrolling is way too fast in writer [Caolán McNamara]
    rhbz#1535541 mimetypes are .macroEnabled not .macroenabled [Caolán McNamara]
    rhbz#1541486 Base table creation dialog window title is shown in different languages [Stephan Bergmann]
    tdf#32935 CSV import dialog doesn't get focus if libreoffice is already running [Mike Kaganski]
    tdf#38915 Multiple soffice.bin soffice.exe [Mike Kaganski]
    tdf#49134 On opening a password-protected file, the LibreOffice dialog is not raised/given focus [Mike Kaganski]
    tdf#70425 EDITING: Embedded Firebird - Copying integer values from Calc to Base impossible [Tamas Bunth]
    tdf#75256 (Icon-Theme-Sifr) [META] Incomplete Sifr icon theme [Matthias Freund]
    tdf#88004 mimetypes are .macroEnabled not .macroenabled [Caolán McNamara]
    tdf#94225 Writer crashes on undo times N (steps in Comment 11 or Comment 38) [Fyodor Yemelyanenko]
    tdf#95024 Support for new Hungarian orthography [László Németh]
    tdf#103174 Very laggy scrolling with trackpad on hidpi screens [Caolán McNamara]
    tdf#103550 JIS function [Winfried Donkers]
    tdf#104016 FILEOPEN: RTF incorrect bullets indentation and spacing [Miklos Vajna]
    tdf#105226 AM/PM locale for it_IT incorrect [Winfried Donkers]
    tdf#106780 FILESAVE, ODF: attribute text:style-name is invalid in table:table-template [Abhishek Shrivastava]
    tdf#108473 Inserting into a Form Table Control Date/Time (Time) field gets stuck [Julien Nabet]
    tdf#109062 Scrolling with touchpad or scrollwheel is not working on Mac [Caolán McNamara]
    tdf#112292 Memory usage is steadily increasing every time when copying something to the clipboard even with 0 undo steps [Noel Grandin]
    tdf#113751 Borders for Merged Cells are Partially Shown [Armin Le Grand]
    tdf#114045 Undo after Clone Formatting changes formatting of entire table [Mark Hung]
    tdf#114173 FILESAVE XLSX Custom size of chart legend is not preserved when the file is saved as XLSX [Caolán McNamara]
    tdf#114182 FILESAVE XLSX Pie chart slice moved back by LibreOffice Calc [Markus Mohrhard]
    tdf#114217 DOCX with floating table having 100% width incorrectly imported [Mike Kaganski]
    tdf#114221 Calc corrupts password-protected XLS on save (Save as works) - newer MSO 2013 encryption saved as unencrypted file with encryption mode [Caolán McNamara]
    tdf#114306 fix unexpected page break in row-spanned table [Manfred Blume]
    tdf#114428 XHTML import: xml declaration results in plain text import into Writer [Miklos Vajna]
    tdf#114460 Some embedded PDFs not exported to pdf [Miklos Vajna]
    tdf#114466 Certain Document in Use dialog does not get focus [Mike Kaganski]
    tdf#114519 Sidebar Number Format drop down does not update cell contents on number format selection change [Jim Raykowski]
    tdf#114596 External forms for a database doesn't save data - closing form with dataloss [Michael Stahl]
    tdf#114625 Calc can not print right border of merged cells from LO 6.0 [Armin Le Grand]
    tdf#114677 Base Form titles incorrect [Szymon Kłos]
    tdf#114731 Firefox themes cannot be installed, it finds nothing [Julien Nabet]
    tdf#114815 Crash in: take_gil on paste from clipboard in Windows [Michael Stahl]
    tdf#114820 FILEOPEN XLSX VLOOKUP/HLOOKUP gives Error:504, with a reference to an external xlsx file cells [Bartosz Kosiorek]
    tdf#114824 Export to PDF and Printing: Borders of Merged Cells Flow to Page Footer [Armin Le Grand]
    tdf#114901 UI: TSCP Classification dialog: too much vertical white space and Part list too wide [Tomaž Vajngerl]
    tdf#114934 (borderline-regressions) [META] borderline regressions [Armin Le Grand]
    tdf#115013 Merge fields aren't substituted after saving/reopening DOC(X) with added mail merge fields, and running mail merge [Mike Kaganski]
    tdf#115044 Calc asks to update links, but already updated them [Vasily Melenchuk]
    tdf#115057 Color picker widget border missing when opened in dialog [Maxim Monastirsky]
    tdf#115065 Crash when dragging table with many rows to a table with less rows [Mike Kaganski]
    tdf#115080 Replace with Pattern Field misbehaves when editing a form's table control [Caolán McNamara]
    tdf#115088 Pasting multi-line text from external source behaves strangely [Tamás Zolnai]
    tdf#115090 Crashes when closing the document running the macro (itself) [Thorsten Behrens]
    tdf#115100 Assertion failed, if I set vertical align for gluepoint [Julien Nabet]
    tdf#115106 Screen corruption in Writer in FullScreen mode. (gtk2) [Caolán McNamara]
    tdf#115153 FILEOPEN: RTF: Incorrect vertical position of lines (follow-up) [Michael Stahl]
    tdf#115155 FILEOPEN: RTF: left indent is lost in second list [Miklos Vajna]
    tdf#115162 FILEOPEN XLSX SUMIFS, AVERAGEIFS, COUNTIFS, MAXIFS, MINIFS functions give Error:504, with reference to external xlsx files cells [Bartosz Kosiorek]
    tdf#115169 Calc: Rotated Cells not shown rotated when using Print/PDF/PrintPreview [Armin Le Grand]
    tdf#115208 Apparmor profile doesn't allow java execution [Olivier Tilloy]
    tdf#115221 PRINTING: CRASH immediately after choosing comment (+doc) printing in the print dialog [Noel Grandin]
    tdf#115269 LO Base Report Builder crashes on modifying Page Header Horizontal or Vertical alignment [Julien Nabet]
    tdf#115369 Icons for the cell's shadows positions are inverted [Caolán McNamara]
    tdf#115416 LibreOffice fails to build with IJG's libjpeg - error: ‘JCS_EXT_BGRA’ was not declared in this scope [Caolán McNamara]