gnurl: Update to 7.69.1
Changelog:

CHANGELOG (curl)
----------

Fixed in 7.69.1 - March 11 2020

Bugfixes:

    ares: store dns parameters for duphandle
    cirrus-ci: disable the FreeBSD 13 builds
    curl_share_setopt.3: Note sharing cookies doesn't enable the engine
    lib1564: reduce number of mid-wait wakeup calls
    libssh: Fix matching user-specified MD5 hex key
    MANUAL: update a dict-using command line
    mime: do not perform more than one read in a row
    mime: fix the binary encoder to handle large data properly
    mime: latch last read callback status
    multi: skip EINTR check on wakeup socket if it was closed
    pause: bail out on bad input
    pause: force a connection recheck after unpausing (take 2)
    pause: return early for calls that don't change pause state
    runtests.1: rephrase how to specify what tests to run
    runtests: fix missing use of exe_ext helper function
    seek: fix fall back for missing ftruncate on Windows
    sftp: fix segfault regression introduced by #4747 in 7.69.0
    sha256: Added SecureTransport implementation
    sha256: Added WinCrypt implementation
    socks4: fix host resolve regression
    socks5: host name resolv regression fix
    tests/server: fix missing use of exe_ext helper function
    tests: fix static ip:port instead of dynamic values being used
    tests: make sleeping portable by avoiding select
    unit1612: fix the inclusion and compilation of the HMAC unit test
    urldata: remove the 'stream_was_rewound' connectdata struct member
    version: make curl_version* thread-safe without using global context

Fixed in 7.69.0 - March 4 2020

Changes:

    polarssl: removed
    smtp: add CURLOPT_MAIL_RCPT_ALLLOWFAILS and --mail-rcpt-allowfails
    wolfSSH: new SSH backend

Bugfixes:

    altsvc: improved header parser
    altsvc: keep a copy of the file name to survive handle reset
    altsvc: make saving the cache an atomic operation
    altsvc: use h3-27
    azure: disable brotli on the macos debug-builds
    build: remove all HAVE_OPENSSL_ENGINE_H defines
    checksrc.bat: Fix not being able to run script from the main curl dir
    cleanup: fix several comment typos
    cleanup: fix typos and wording in docs and comments
    cmake: add support for CMAKE_LTO option
    cmake: clean up and improve build procedures
    cmake: enable SMB for Windows builds
    cmake: improve libssh2 check on Windows
    cmake: Show HTTPS-proxy in the features output
    cmake: support specifying the target Windows version
    cmake: use check_symbol_exists also for inet_pton
    configure.ac: fix comments about --with-quiche
    configure: disable metalink if mbedTLS is specified
    configure: disable metalink support for incompatible SSL/TLS
    conn: do not reuse connection if SOCKS proxy credentials differ
    conncache: removed unused Curl_conncache_bundle_size()
    connect: remove some spurious infof() calls
    connection reuse: respect the max_concurrent_streams limits
    contributors: also include people who contributed to curl-www
    contrithanks: use the most recent tag by default
    cookie: check __Secure- and __Host- case sensitively
    cookies: make saving atomic with a rename
    create-dirs.d: mention the mode
    curl: avoid using strlen for testing if a string is empty
    curl: error on --alt-svc use w/o support
    curl: let -D merge headers in one file again
    curl: make #0 not output the full URL
    curl: make the -# spaceship bar not wrap the line
    curl: remove 'config' field from OutStruct
    curl:progressbarinit: ignore column width from terminals < 20
    curl_escape.3: add a link to curl_free
    curl_getenv.3: fix the memory handling description
    curl_global_init: assume the EINTR bit by default
    curl_global_init: move the IPv6 works status bool to multi handle
    CURLINFO_COOKIELIST.3: Fix example
    CURLOPT_ALTSVC_CTRL.3: fix the DEFAULT wording
    CURLOPT_PROXY_SSL_OPTIONS.3: Sync with CURLOPT_SSL_OPTIONS.3
    CURLOPT_REDIR_PROTOCOLS.3: update the DEFAULT section
    data.d: remove "Multiple files can also be specified"
    digest: do not quote algorithm in HTTP authorisation
    docs/HTTP3: add --enable-alt-svc to curl's configure
    docs/HTTP3: update the OpenSSL branch to use for ngtcp2
    docs: fix typo on CURLINFO_RETRY_AFTER
    easy: remove dead code
    form.d: fix two minor typos
    ftp: convert 'sock_accepted' to a plain boolean
    ftp: remove superfluous checking for crlf in user or pwd
    ftp: shrink temp buffers used for PORT
    github action: add CIFuzz
    github: Instructions to post "uname -a" on Unix systems in issues
    GnuTLS: always send client cert
    gtls: fixed compilation when using GnuTLS < 3.5.0
    hostip: move code to resolve IP address literals to `Curl_resolv`
    HTTP-COOKIES: describe the cookie file format
    HTTP-COOKIES: mention that a trailing newline is required
    http2: make pausing/unpausing set/clear local stream window
    http2: now requires nghttp2 >= 1.12.0
    http: added 417 response treatment
    http: increase EXPECT_100_THRESHOLD to 1Mb
    http: mark POSTs with no body as "upload done" from the start
    http: move "oauth_bearer" from connectdata to Curl_easy
    include: remove non-curl prefixed defines
    KNOWN_BUGS: Multiple methods in a single WWW-Authenticate: header
    libssh2: add support for forcing a hostkey type
    libssh2: fix variable type
    libssh: improve known hosts handling
    llist: removed unused Curl_llist_move()
    location.d: the method change is from POST to GET only
    md4: fixed compilation issues when using GNU TLS gcrypt
    md4: use init/update/final functions in Secure Transport
    md5: added implementation for mbedTLS
    mk-ca-bundle: add support for CKA_NSS_SERVER_DISTRUST_AFTER
    multi: change curl_multi_wait/poll to error on negative timeout
    multi: fix outdated comment
    multi: if Curl_readwrite sets 'comeback' use expire, not loop
    multi_done: if multiplexed, make conn->data point to another transfer
    multi_wait: stop loop when sread() returns zero
    ngtcp2: add error code for QUIC connection errors
    ngtcp2: fixed to only use AF_INET6 when ENABLE_IPV6
    ngtcp2: update to git master and its draft-25 support
    ntlm: move the winbind data into the NTLM data structure
    ntlm: pass the Curl_easy structure to the private winbind functions
    ntlm: removed the dependency on the TLS libaries when using MD5
    ntlm_wb: use Curl_socketpair() for greater portability
    oauth2-bearer.d: works for HTTP too
    openssl: make CURLINFO_CERTINFO not truncate x509v3 fields
    openssl: remove redundant assignment
    os400: fixed the build
    pause: force-drain the transfer on unpause
    quiche: update to draft-25
    README: mention that the docs is in docs/
    RELEASE-PROCEDURE: feature win is closed post-release a few days
    runtests: make random seed fixed for a month
    runtests: restore the command log
    schannel: make CURLOPT_CAINFO work better on Windows 7
    schannel_verify: Fix alt names manual verify for UNICODE builds
    sha256: use crypto implementations when available
    singleuse.pl: support new API functions, fix curl_dbg_ handling
    smtp: support the SMTPUTF8 extension
    smtp: support UTF-8 based host names in MAIL FROM
    SOCKS: make the connect phase non-blocking
    strcase: turn Curl_raw_tolower into static
    strerror: increase STRERROR_LEN 128 -> 256
    test1323: added missing 'unit test' feature requirement
    tests: add a unit test for MD4 digest generation
    tests: add a unit test for SHA256 digest generation
    tests: add a unit test for the HMAC hash generation
    tests: deduce the tool name from the test case for unit tests
    tests: fix Python 3 compatibility of smbserver.py
    tool_dirhie: allow directory traversal during creation
    tool_homedir: change GetEnv() to use libcurl's curl_getenv()
    tool_util: improve Windows version of tvnow()
    travis: update non-OpenSSL Linux jobs to Bionic
    url: include the failure reason when curl_win32_idn_to_ascii() fails
    urlapi: guess scheme properly with credentials given
    urldata: do string enums without #ifdefs for build scripts
    vtls: refactor Curl_multissl_version to make the code clearer
    win32: USE_WIN32_CRYPTO to enable Win32 based MD4, MD5 and SHA256

Fixed in 7.68.0 - January 8 2020

Changes:

    TLS: add BearSSL vtls implementation
    XFERINFOFUNCTION: support CURL_PROGRESSFUNC_CONTINUE
    curl: add --etag-compare and --etag-save
    curl: add --parallel-immediate
    multi: add curl_multi_wakeup()
    openssl: CURLSSLOPT_NO_PARTIALCHAIN can disable partial cert chains

Bugfixes:

    CVE-2019-15601: file: on Windows, refuse paths that start with \\
    Azure Pipelines: add several builds
    CMake: add support for building with the NSS vtls backend
    CURL-DISABLE: initial docs for the CURL_DISABLE_* defines
    CURLOPT_HEADERFUNCTION.3: Document that size is always 1
    CURLOPT_QUOTE.3: fix typos
    CURLOPT_READFUNCTION.3: fix the example
    CURLOPT_URL.3: "curl supports SMB version 1 (only)"
    CURLOPT_VERBOSE.3: see also ERRORBUFFER
    HISTORY: added cmake, HTTP/3 and parallel downloads with curl
    HISTORY: the SMB(S) support landed in 2014
    INSTALL.md: provide Android build instructions
    KNOWN_BUGS: Connection information when using TCP Fast Open
    KNOWN_BUGS: LDAP on Windows doesn't work correctly
    KNOWN_BUGS: TLS session cache doesn't work with TFO
    OPENSOCKETFUNCTION.3: correct the purpose description
    TrackMemory tests: always remove CR before LF
    altsvc: bump to h3-24
    altsvc: make the save function ignore NULL filenames
    build: Disable Visual Studio warning "conditional expression is constant"
    build: fix for CURL_DISABLE_DOH
    checksrc.bat: Add a check for vquic and vssh directories
    checksrc: repair the copyrightyear check
    cirrus-ci: enable clang sanitizers on freebsd 13
    cirrus: Drop the FreeBSD 10.4 build
    config-win32: cpu-machine-OS for Windows on ARM
    configure: avoid unportable `==' test(1) operator
    configure: enable IPv6 support without `getaddrinfo`
    configure: fix typo in help text
    conncache: CONNECT_ONLY connections assumed always in-use
    conncache: fix multi-thread use of shared connection cache
    copyrights: fix copyright year range
    create_conn: prefer multiplexing to using new connections
    curl -w: handle a blank input file correctly
    curl.h: add two missing defines for "pre ISO C" compilers
    curl/parseconfig: fix mem-leak
    curl/parseconfig: use curl_free() to free memory allocated by libcurl
    curl: cleanup multi handle on failure
    curl: fix --upload-file . hangs if delay in STDIN
    curl: fix -T globbing
    curl: improved cleanup in upload error path
    curl: make a few char pointers point to const char instead
    curl: properly free mimepost data
    curl: show better error message when no homedir is found
    curl: show error for --http3 if libcurl lacks support
    curl_setup_once: consistently use WHILE_FALSE in macros
    define: remove HAVE_ENGINE_LOAD_BUILTIN_ENGINES, not used anymore
    docs: Change 'experiemental' to 'experimental'
    docs: TLS SRP doesn't work with TLS 1.3
    docs: fix several typos
    docs: mention CURL_MAX_INPUT_LENGTH restrictions
    doh: improved both encoding and decoding
    doh: make it behave when built without proxy support
    examples/postinmemory.c: Call curl_global_cleanup always
    examples/url2file.c: corrected erroneous comment
    examples: add multi-poll.c
    global_init: undo the "intialized" bump in case of failure
    hostip: suppress compiler warning
    http_ntlm: Remove duplicate NSS initialisation
    lib: Move lib/ssh.h -> lib/vssh/ssh.h
    lib: fix compiler warnings with `CURL_DISABLE_VERBOSE_STRINGS`
    lib: fix warnings found when porting to NuttX
    lib: remove ASSIGNWITHINCONDITION exceptions, use our code style
    lib: remove erroneous +x file permission on some c files
    libssh2: add support for ECDSA and ed25519 knownhost keys
    multi.h: remove INITIAL_MAX_CONCURRENT_STREAMS from public header
    multi: free sockhash on OOM
    multi_poll: avoid busy-loop when called without easy handles attached
    ngtcp2: Support the latest update key callback type
    ngtcp2: fix thread-safety bug in error-handling
    ngtcp2: free used resources on disconnect
    ngtcp2: handle key updates as ngtcp2 master branch tells us
    ngtcp2: increase QUIC window size when data is consumed
    ngtcp2: use overflow buffer for extra HTTP/3 data
    ntlm: USE_WIN32_CRYPTO check removed to get USE_NTLM2SESSION set
    ntlm_wb: fix double-free in OOM
    openssl: Revert to less sensitivity for SYSCALL errors
    openssl: improve error message for SYSCALL during connect
    openssl: prevent recursive function calls from ctx callbacks
    openssl: retrieve reported LibreSSL version at runtime
    openssl: set X509_V_FLAG_PARTIAL_CHAIN by default
    parsedate: offer a getdate_capped() alternative
    pause: avoid updating socket if done was already called
    projects: Fix Visual Studio projects SSH builds
    projects: Fix Visual Studio wolfSSL configurations
    quiche: reject HTTP/3 headers in the wrong order
    remove_handle: clear expire timers after multi_done()
    runtests: --repeat=[num] to repeat tests
    runtests: introduce --shallow to reduce huge torture tests
    schannel: fix --tls-max for when min is --tlsv1 or default
    setopt: Fix ALPN / NPN user option when built without HTTP2
    strerror: Add Curl_winapi_strerror for Win API specific errors
    strerror: Fix an error looking up some Windows error strings
    strerror: Fix compiler warning "empty expression"
    system.h: fix for MCST lcc compiler
    test/sws: search for "Testno:" header unconditionally if no testno
    test1175: verify symbols-in-versions and libcurl-errors.3 in sync
    test1270: a basic -w redirect_url test
    test1456: remove the use of a fixed local port number
    test1558: use double slash after file:
    test1560: require IPv6 for IPv6 aware URL parsing
    tests/lib1557: fix mem-leak in OOM
    tests/lib1559: fix mem-leak in OOM
    tests/lib1591: free memory properly on OOM, in the trailers callback
    tests/unit1607: fix mem-leak in OOM
    tests/unit1609: fix mem-leak in OOM
    tests/unit1620: fix bad free in OOM
    tests: Change NTLM tests to require SSL
    tests: Fix bounce requests with truncated writes
    tests: fix build with `CURL_DISABLE_DOH`
    tests: fix permissions of ssh keys in WSL
    tests: make it possible to set executable extensions
    tests: make sure checksrc runs on header files too
    tests: set LC_ALL=en_US.UTF-8 instead of blank in several tests
    tests: use DoH feature for DoH tests
    tests: use \r\n for log messages in WSL
    tool_operate: fix mem leak when failed config parse
    travis: Fix error detection
    travis: abandon coveralls, it is not reliable
    travis: build ngtcp2 with --enable-lib-only
    travis: export the CC/CXX variables when set
    vtls: make BearSSL possible to set with CURL_SSL_BACKEND
    winbuild: Define CARES_STATICLIB when WITH_CARES=static
    winbuild: Document CURL_STATICLIB requirement for static libcurl