chat/py-xmpppy: Update to 0.7.2
pkgsrc:
  - Convert to wheel.mk (NFCI).
  - Drop ssl patch cherrypicked from upstream, now in this release.
  - Add patch with attempts to remove disabling of certificate
    validation (to match behavior of 0.7.1 in pkgsrc), and comments
    about why that doesn't work, as being on the path to working with
    upstream.

2025-08-09 0.7.2
================
- Fixed ``AttributeError: module 'ssl' has no attribute 'wrap_socket'``.
  Thanks, @juanvalino.
- Ensured certificate checking is disabled to maintain backward compatibility.
  Thanks, @juanvalino.
- Added example for sending data to a MUC room. Thanks, @sebix.