Reordered the sections so that the general ones are at the beginning, followed by the ones specific to a phase. Added an "undefined reference to ..." section.