p5-Devel-PatchPerl: update to 1.52.
-----------------------------------------
version 1.52 at 2018-06-23 09:12:01 +0000
-----------------------------------------

  Change: 9987ca085ff78e37d4fb0a118a16dc6b6b11ba79
  Author: Chris 'BinGOs' Williams <chris@bingosnet.co.uk>
  Date : 2018-06-23 10:12:01 +0000

    Release engineering for 1.52

  Change: d4d87e4d9324316e1ab392619491a96885aa3fa1
  Author: Chris 'BinGOs' Williams <chris@bingosnet.co.uk>
  Date : 2018-06-23 10:03:51 +0000

    Updated hints

  Change: 95826fad7e96f573dad727374cfb9f4a8b1017ee
  Author: Bram <bram-tvguho@mail.wizbit.be>
  Date : 2017-12-08 12:56:34 +0000

    Add patch for 'Perl_fp_class_denorm'

    Patch error:

    sv.o: In function `S_hextract':

    sv.c:(.text+0xcfd): undefined reference to `Perl_fp_class_denorm'

    perl5 commit message:

    Fallbacks for Perl_fp_class_denorm().

    These may be needed if the compiler doesn't expose the C99 math

    without some special switches.

    See also: - https://rt.perl.org/Public/Bug/Display.html?id=132255 -
    perl5 commit 488307ffa67ce70fc9755e560a74dac04bdcb0e4